### ISSUE TITLE
Suggestion: Optimized tag-adding

### ISSUE THREAD

**Issue by SubJunk** [ZenPhoto20/ZenPhoto20#235]
I'm running into a problem with one of my sites: there are so many tags that the image metadata editing page in the admin panel (which loads a full list of every tag in the database, per image) that the page loads very slowly, causing Firefox to temporarily freeze when an action is performed. For example if I try to edit an image title, I will click in the input box and type a letter, then wait for it to unfreeze, then another, then wait, etc.
It only takes a second or two on my computer but it's a relatively modern computer, I tried it on a more normal one recently and it took about 20 seconds so it was unusable.

A solution to this would be to use ajax lookups/validation for the tags so they don't all exist on the page multiple times, the validation would be server-side instead of client-side.

**Comment by SubJunk** [comment]
@sbillard thanks for the optimizations. Unfortunately it's still the same. The issue is when using any input box, not just the tag one, that's why I think it's just that there is too much for Firefox to handle on the page at the same time.
I just checked and it's 4.34MB for just the HTML of that page, without externals - 87727 lines of code. Most of that is the tags being printed ten times each.

**Comment by sbillard** [comment]
Roughly how many tags are there? And where are the tags being printed? I can think of only two places--HTML metatags and tag_suggest. Maybe a link to the page would help me evaluate this.

**Comment by SubJunk** [comment]
@sbillard there are 1716 tags, but I just realized that tags are different in zenphoto20 so it doesn't really apply since I still have zenphoto's tag system. Sorry to have wasted your time.

Is there a setting in zenphoto20 to be able to edit tags for multiple images at once instead of clicking through to each individual one? Adding tags takes up enough time already without adding extra steps in between.

**Comment by sbillard** [comment]
The "bulk actions" on the image page can add tags to all the images on the page. (Number of images per page is an option.) This is also true with zenphoto.

No time wasted--the optimizations are appropriate and proper anyway, brute force searches are never good coding practice. I have also added an option to the tags_suggest plugin (for front end use only) that will allow you to exclude tags with less than "n" uses. So for instance you can suggest only tags used 3 or more times. That seemed like a good addition as well. It will be in the pull that I will shortly do to merge the other improvements.

Not sure what you mean by "still have zenphoto's tag system". Is there something ZenPhoto20 is not doing for you?

**Comment by SubJunk** [comment]
@sbillard good idea about the n uses, that will be very useful!

On a fresh install of zenphoto20 1.0.1.0, on the Images subtab of the Albums tab, it just says "No tags assigned" in the "Tags:" section, whereas on a fresh install of zenphoto 1.4.6 there's a little "+" button to add tags.

**Comment by sbillard** [comment]
Right, the tags setting by image has been moved to the single-image editing page. (I believe the zenphoto folks have done this as well.) This was done to solve your original issue.

But you can still add tags to images by using the bulk action drop-down (right hand side of the top "back", "apply"," and "reset" buttons line) on the multiple images page. Tags added this way are added to any image with a bulk actions checkbox checked.
