### ISSUE TITLE
ZPArdoise errors

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/ZenPhoto20#266]
1.0.1.1 [d61fcc34d3]
ZPArdoise
gallery set as private
image statistic strip set anything else of NONE

For non-login user, there is error:
Parse error: syntax error, unexpected T_STRING in /........../zp-core/exif/makers/olympus.php on line 75

Footer can not be displayed, so there is not link to login.

And in theme options, there is error:
Warning: Missing argument 4 for setThemeOption(), called in /net/...themes/zpArdoise/themeoptions.php on line 132 and defined in /net/.../zp-core/functions.php on line 1843

**Comment by sbillard** [comment]
I do not have olympus images, so cannot test the fix for the first issue. Please confirm that these change do fix the poblems.

**Comment by Mates-K1** [comment]
Both of errors are solved.
Thanks.
