### ISSUE TITLE
Wrong position in Google Maps

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/ZenPhoto20#327]
Hi,
I am here again.. :/

Google Maps shows wrong image position for me + all images in album have same position.
I tried rebuild DB and metadata - it didnt help.

See image (right position is marked by red circle and store in image too)
![google](https://cloud.githubusercontent.com/assets/7648991/7107188/950d6ffa-e15d-11e4-86ed-4fe404a8ca94.jpg)

You can login again. Your account is still on.
In Basic theme you can show GPS position and compare them with google maps.

Another example:
http://skaut.zamberk.cz/galerieonline/index.php?album=stredisko/vypravy/2015_03_21_rytiri
(cca 10 different position in album, but one pin in map)

**Comment by sbillard** [comment]
This is probably a locale setting issue. Can you look at the page source of one of the example. Find something that looks like 
`var map;var iw=new google.maps.InfoWindow({maxWidth:250});var lat_longs=new Array();var markers=new Array();var markerCluster;function initialize(){var myLatlng=new google.maps.LatLng(49.000000000000,16.000000000000);var myOptions={zoom:13,center:myLatlng,mapTypeId:google.maps.MapTypeId.HYBRID,mapTypeControlOptions:{mapTypeIds:[google.maps.MapTypeId.HYBRID,google.maps.MapTypeId.ROADMAP,google.maps.MapTypeId.SATELLITE,google.maps.MapTypeId.TERRAIN]},zoomControlOptions:{style:google.maps.ZoomControlStyle.LARGE}}
map=new google.maps.Map(document.getElementById("map_canvas"),myOptions);var oms=new OverlappingMarkerSpiderfier(map,{keepSpiderfied:true});oms.addListener("click",function(marker){iw.setContent(marker.get("content"));iw.open(map,marker);});oms.addListener("spiderfy",function(markers){iw.close();});google.maps.event.addListener(map,"click",function(event){iw.close();});var myLatlng=new google.maps.LatLng(49.000000000000,16.000000000000);var markerOptions={map:map,position:myLatlng,title:"002"};marker_0=createMarker(markerOptions);marker_0.set("content","<h3 class=\"map_title\">002</h3><p class=\"map_img\"><a href=\"javascript:image('stredisko/vypravy/2015_03_21_rytiri','002.jpg');\"><img src=\"/galerieonline/zp-core/i.php?a=stredisko/vypravy/2015_03_21_rytiri&i=002.jpg&s=150&cw=0&ch=0&q=85&wmk=!&check=e9214e7fcd87deb9860498bd1188de5f50045c30\" /></a></p>");google.maps.event.addListener(marker_0,"click",function(event){iw.setContent(this.get("content"));iw.open(map,this);});oms.addMarker(marker_0);var clusterOptions={gridSize:60,maxZoom:13,averageCenter:true,minimumClusterSize:2};markerCluster=new MarkerClusterer(map,markers,clusterOptions);}`

and post that string here.

**Comment by Mates-K1** [comment]
For your example ('stredisko/vypravy/2015_03_21_rytiri','002.jpg'):
GPSLatitude 49,977745
GPSLongitude 16,5689736111
EXIFGPSLatitude 49,977745
EXIFGPSLatitudeRef N
EXIFGPSLongitude 16,5689736111
EXIFGPSLongitudeRef E

There arent XMPLongitude and XMPLatitude rows in DB.

**Comment by sbillard** [comment]
Please add some debugging code into the GoogleMap plugin: zp-core/zp-extensions/googleMap.php after line 203 (`$long_f = floatval($long);`)

Add 
`var_dump($lat);
var_dump($lat_f);
var_dump($long);
var_dump($long_f);`

When you show the image it should place the output of these on the page please report exactly what is output.

Sorry that I have to have you do these things, but this is some kind of locale issue. Most likely with the handling of numeric decimal points. Since the US uses a period as the decimal point things work differently for me locally.

**Comment by Mates-K1** [comment]
<code>string(9) "49,977745" float(49) string(13) "16,5689736111" float(16) array(18) { ["decimal_point"]=> string(1) "," ["thousands_sep"]=> string(2) " " ["int_curr_symbol"]=> string(4) "CZK " ["currency_symbol"]=> string(3) "Kč" ["mon_decimal_point"]=> string(1) "," ["mon_thousands_sep"]=> string(2) " " ["positive_sign"]=> string(0) "" ["negative_sign"]=> string(1) "-" ["int_frac_digits"]=> int(2) ["frac_digits"]=> int(2) ["p_cs_precedes"]=> int(0) ["p_sep_by_space"]=> int(1) ["n_cs_precedes"]=> int(0) ["n_sep_by_space"]=> int(1) ["p_sign_posn"]=> int(1) ["n_sign_posn"]=> int(1) ["grouping"]=> array(2) { [0]=> int(3) [1]=> int(3) } ["mon_grouping"]=> array(2) { [0]=> int(3) [1]=> int(3) } }</code>


I understand that our country have it otherwise. I do not mind the complications, it may help others in need, not only in Europe. Mainly I appreciate your approach and rapid response in solving problems.

**Comment by sbillard** [comment]
Seems to be a bug in the PHP floatval() function--it is not handling your locale correctly. Please try changing the two lines above the var_dumps as follows.

`$lat_f = (float)$lat;
$long_f = (float)$long;`

and see what happens. If this does not work we will have to make the string to float conversion the hard way.

**Comment by Mates-K1** [comment]
Nothing happend...

But... the problem seems to be more complicated and confusing for me.
I found some images, which have correct position with ".". I used searching in gallery frontend and search in GPS - for example "15." or "49.". And now the complicated thing - there are images with wrong and good position in the same album.
(http://skaut.zamberk.cz/galerieonline/index.php?album=1_oddil_skautu/vypravy/vyprava_2010_12_26_kozince, http://skaut.zamberk.cz/galerieonline/index.php?album=1_oddil_skautu/vypravy/vyprava_2014_11_28_bartosovice,...).

For example in vyprava_2010_12_26_kozince:
file 01.jpg - ID4192 - good gps (with ".")
file 02.jpg - ID4191 - wrong gps (with ",")

I'm sure that I added gps in the same time, uploaded in the same time,..

(Sorry - it is 1 a.m. for me, so I go to bed and I will look at it in more detail tomorrow.)

**Comment by sbillard** [comment]
Well, that is a bit of an issue. The basic problem is that we have to convert the string into a number, so we have to know whether a period is a decimal separator or just a formatting element to delimit groups of 3 digits. According to your local information, the decimal separator is a comma so anything with a period I would expect to fail.

What did the var_dump look like after the change to `(float) ...`?

The input data needs to be consistent. I think maybe the database column type might be an issue. So please download the master from https://github.com/sbillard/ZenPhoto20-DEV/. You will need to run setup, then do a metadata refresh. See if that makes things consistent.

**Comment by Mates-K1** [comment]
var_dump after change:
<code>string(9) "49,977745" float(49) string(13) "16,5689736111" float(16) array(18) { ["decimal_point"]=> string(1) "," ["thousands_sep"]=> string(2) " " ["int_curr_symbol"]=> string(4) "CZK " ["currency_symbol"]=> string(3) "Kč" ["mon_decimal_point"]=> string(1) "," ["mon_thousands_sep"]=> string(2) " " ["positive_sign"]=> string(0) "" ["negative_sign"]=> string(1) "-" ["int_frac_digits"]=> int(2) ["frac_digits"]=> int(2) ["p_cs_precedes"]=> int(0) ["p_sep_by_space"]=> int(1) ["n_cs_precedes"]=> int(0) ["n_sep_by_space"]=> int(1) ["p_sign_posn"]=> int(1) ["n_sign_posn"]=> int(1) ["grouping"]=> array(2) { [0]=> int(3) [1]=> int(3) } ["mon_grouping"]=> array(2) { [0]=> int(3) [1]=> int(3) } }</code>

**Comment by Mates-K1** [comment]
So... after fresh instal of current master, rebuilding DB and metadata... there is no image with right gps position. This means that part of the problem is resolved. :-))

**Comment by sbillard** [comment]
Wonderful news. These kinds of issues are really difficult to analyze. I will release the change to the mainline ZenPhoto20 then.

**Comment by Mates-K1** [comment]
1.1.3.9, rebuilding DB and metadata twice.. still same wrong gps position...

<code>string(9) "49,977745" float(49) string(13) "16,5689736111" float(16) array(18) { ["decimal_point"]=> string(1) "," ["thousands_sep"]=> string(2) " " ["int_curr_symbol"]=> string(4) "CZK " ["currency_symbol"]=> string(3) "Kč" ["mon_decimal_point"]=> string(1) "," ["mon_thousands_sep"]=> string(2) " " ["positive_sign"]=> string(0) "" ["negative_sign"]=> string(1) "-" ["int_frac_digits"]=> int(2) ["frac_digits"]=> int(2) ["p_cs_precedes"]=> int(0) ["p_sep_by_space"]=> int(1) ["n_cs_precedes"]=> int(0) ["n_sep_by_space"]=> int(1) ["p_sign_posn"]=> int(1) ["n_sign_posn"]=> int(1) ["grouping"]=> array(2) { [0]=> int(3) [1]=> int(3) } ["mon_grouping"]=> array(2) { [0]=> int(3) [1]=> int(3) } }</code>

**Comment by sbillard** [comment]
Sorry, I misunderstood you. I guess the float function is just not working for your locale. I will have to find a different conversion.

**Comment by JimBrown** [comment]
Would the PHP function 'number_format' be of any help?

http://php.net/number_format

**Comment by sbillard** [comment]
Unfortunately number_format is an output conversion. Our problem is that the input conversion does not result in the correct FLOAT value.

**Comment by sbillard** [comment]
Please try master from https://github.com/sbillard/ZenPhoto20-DEV/. I have made a brute force input conversion function that should work.

**Comment by Mates-K1** [comment]
:+1:  Yes, it works!!!
Great work again.
