### ISSUE TITLE
errors for news and categories

### ISSUE THREAD

**Issue by Jens2014** [ZenPhoto20/ZenPhoto20#334]
Hi,
I'm using ZP20 1.1.4.1.
Creating a news post leads to the warning:
"Warning: Invalid argument supplied for foreach() in [...]\zp-core\zp-extensions\zenpage\class-news.php on line 148"
In the admin news overview there are two warnings displayed:
"Warning: Invalid argument supplied for foreach() in [...]\zp-core\zp-extensions\zenpage\admin-functions.php on line 476"
"Warning: Invalid argument supplied for foreach() in [...]\zp-core\zp-extensions\zenpage\class-news.php on line 148"
These warnings appaer with or without news categories. If I try to work with categories it's not possible to assign one to a news post. The db table news2cat stays empty.

Thanks for your support!
Best wishes, Jens

**Comment by sbillard** [comment]
Please look at your debug log and also your server logs. There may be additional errors in them that will help in understanding this. I have not been able to reproduce the failure. The errors you are getting would indicate that the News article's categories property is neither NULL nor an array(). It is not at all clear how this is possible unless there is some other error occurring. 

You can also add debug statements in ...zenpage/class-news.php just before line 148. Add `var_dump($this->categories);`;var_dump($categories);` and let me know the output.

**Comment by Jens2014** [comment]
Here are the logs for 1 action (showing the admin News article overview:
ZP errorlog:

{2748:Sat, 18 Apr 2015 20:06:17 GMT} ZenPhoto20 v1.1.4.1
WARNING: Invalid argument supplied for foreach() in C:\xampp\htdocs\myprojects\gallery\zp-core\zp-extensions\zenpage\admin-functions.php in line 476
URI:/myprojects/gallery/zp-core/zp-extensions/zenpage/admin-news.php?page=news&tab=articles
IP:
printNewsCategories called from admin-news.php [307]

{2748:Sat, 18 Apr 2015 20:06:17 GMT}
WARNING: Invalid argument supplied for foreach() in C:\xampp\htdocs\myprojects\gallery\zp-core\zp-extensions\zenpage\class-news.php in Zeile 149
{2748:Sat, 18 Apr 2015 20:06:17 GMT} ZenPhoto20 v1.1.4.1
WARNING: Invalid argument supplied for foreach() in C:\xampp\htdocs\myprojects\gallery\zp-core\zp-extensions\zenpage\admin-functions.php in Zeile 476
URI:/myprojects/gallery/zp-core/zp-extensions/zenpage/admin-news.php?page=news&tab=articles
IP:
printNewsCategories called from admin-news.php [307]

{2748:Sat, 18 Apr 2015 20:06:17 GMT}
WARNING: Invalid argument supplied for foreach() in C:\xampp\htdocs\myprojects\gallery\zp-core\zp-extensions\zenpage\class-news.php in line149

URI:/myprojects/gallery/zp-core/zp-extensions/zenpage/admin-news.php?page=news&tab=articles
IP:
Article->inProtectedCategory called from admin-news.php [329]

The server log shows the same Warning messages.


Here is the result of your suggested var_dump for both methods:
string(29) "`JKP_gallery_news_categories`"
So it delivers the correct name of the table as a String as far as I understood.

Hope this helps.

**Comment by sbillard** [comment]
The value from the var_dump should have been an array. I have no idea how it got set to a string of the name of the table. But maybe the following will fix the issue. (Do things a different way and hope they come out better!)

find the function `getCategories` and replace it with
`	function getCategories() {
		if (is_null($this->categories)) {
			$this->categories = array();
			$result = query("SELECT * FROM " . prefix('news_categories') . " as cat," . prefix('news2cat') . " as newscat WHERE newscat.cat_id = cat.id AND newscat.news_id = " . $this->getID() . " ORDER BY cat.titlelink", false);
			while ($row = db_fetch_assoc($result)) {
				$this->categories[$row['title']] = $row;
			}
			db_free_result($result);
		}
		return $this->categories;
	}`

If this works I will make it an official change.

**Comment by Jens2014** [comment]
In the meaning of Warnings now all seems to be fine ;-)
From perspective of the functionality now it returns an empty array. With this I can select a category to add it to a News article. After applying the checkmark is gone. Looking at the database I would expect to find an entry inside of news2cat table. But it remains empty.
I have checked it with an fresh installed version too. The results are the same.

I could imagine the cause is while creating or updating the data for a News article.

**Comment by sbillard** [comment]
The checkmark should "stick", so the category is not being added. Probably there is another error happening. There is similar code in the setCategories method to what I change above, so maybe the same problem is happening there. I can change that code as well.

But this is not normal at all. What database interface are you using? MySQL, MySQLi, PDO_MySQL? What version? I am concerned that if we do not find the root cause of this problem there will be many places that will fail.

**Comment by Jens2014** [comment]
I am using MySQLi as db interface. As far as I checked the Queries seems to be OK.
Server side I am running XAMPP with MySQL Server Version: 5.6.20 - Protokoll-Version: 10 / UTF-8 Unicode

At the moment I got stuck at admin-functions.php line 435:
```php if (isset($cats[$cat['id']])) {
			$categories[] = $cat['titlelink'];
		} ```

As far as I understand is this the place where the category will be set or updated from within the admin panel. Whatever I did this condition never comes true so I did a closer look to it. 

While trying to dump ```php $cats[$cat['id']] ``` I get an 'Undefined offset: 1'.
The content of the involved variables looks like this:

$cats: ```php
array(1) {
  [0]=>
  string(1) "1"
}```
$cats:
```php array(1) {
  [0]=>
  string(1) "1"
} ```
$cat['id']: 1
$cat:
```php array(13) {
  ["id"]=>
  string(1) "1"
  ["title"]=>
  string(31) "a:1:{s:5:"en_US";s:6:"newcat";}"
  ["titlelink"]=>
  string(6) "newcat"
  ["permalink"]=>
  string(1) "0"
  ["hitcounter"]=>
  string(1) "0"
  ["user"]=>
  NULL
  ["password"]=>
  NULL
  ["password_hint"]=>
  NULL
  ["parentid"]=>
  NULL
  ["sort_order"]=>
  string(0) ""
  ["desc"]=>
  string(0) ""
  ["show"]=>
  string(1) "1"
  ["custom_data"]=>
  NULL
}```

Hopefully this is the right place to analyze more. But for today I'm too tired. Thanks for your support!

**Comment by sbillard** [comment]
This does help. Please try version 1.1.4.2 and see if it fixes things for you.

**Comment by Jens2014** [comment]
Version 1.1.4.2 works like a charme and fixes all related issues. Tanks you very much.

**Comment by sbillard** [comment]
Thanks for the update.
