### ISSUE TITLE
Setup character set detection on Windows 8.1

### ISSUE THREAD

**Issue by JimBrown** [ZenPhoto20/ZenPhoto20#339]
I am upgrading to 1.1.5.0. Setup is showing the following:

![image](https://cloud.githubusercontent.com/assets/6067232/7232513/01ffd70a-e74a-11e4-961b-c7f2783adaf0.png)

Clicking "apply" does not change anything.

Before setup is run, my data folder looks like this:

![image](https://cloud.githubusercontent.com/assets/6067232/7232431/91d66566-e749-11e4-8827-b0d9013f3289.png)

And immediately after running setup but before doing anything else, the folder looks like this:

![image](https://cloud.githubusercontent.com/assets/6067232/7232472/c697954a-e749-11e4-935e-5ad1a5bdceec.png)

I am using a WAMP with Apache 2.2.25, PHP 5.4.34 and MySQL 5.6.14 (These are the closest versions to what is on my shared web host.)

Completing setup appears to work, as there are no issues that I can see. However, I do not have any diacritical characters in any of my file names.

Let me know if there are any steps you wish me to take to assist in debugging this. I did notice this issue on the last view releases, but ignored it until now.

Thanks.

**Comment by sbillard** [comment]
WAMP (Windows) does not use UTF-8, so the message is correct but it should have had ISO-8859-1 for the suggestion. I will see what caused this to be wrong. In the mean time, if you did have diacritical characters they would not be working correctly.
