### ISSUE TITLE
Crash after password hint answered

### ISSUE THREAD

**Issue by JimBrown** [ZenPhoto20/ZenPhoto20#342]
After answering the challenge question and clicking submit, the following error occurs:

<pre>
{7068:Fri, 24 Apr 2015 15:46:13 GMT} ZenPhoto20 v1.1.5.1-DEBUG_404
  NOTICE: Undefined index: users in D:\Documents\WebSite\RCAirGallery.dev\public_html\rcairgallery\zp-core\admin-functions.php on line 392
URI:/rcairgallery/zp-core/admin-users.php?ticket=3e05aded970e974b4814e79cd900bee67f39189be9c1a52a81a525654188&user=JamesBrown
IP:127.0.0.1
  printSubtabs called from admin-users.php [313]
{7068:Fri, 24 Apr 2015 15:46:13 GMT}
  WARNING: array_key_exists() expects parameter 2 to be array, null given in D:\Documents\WebSite\RCAirGallery.dev\public_html\rcairgallery\zp-core\admin-functions.php on line 392
URI:/rcairgallery/zp-core/admin-users.php?ticket=3e05aded970e974b4814e79cd900bee67f39189be9c1a52a81a525654188&user=JamesBrown
IP:127.0.0.1
  array_key_exists called from printSubtabs (admin-functions.php [392])
    from admin-users.php [313]
</pre>

This occurs for admin and non-admin users. Additionally, for non-admin users the phrase "You may now set admin usernames and passwords." appears.

**Comment by JimBrown** [comment]
The above commit fixed the crash. However, the alert that is displayed for non-admin users still shows this:

![image](https://cloud.githubusercontent.com/assets/6067232/7327734/8ff66ed8-ea9d-11e4-97bf-0aeb5c175360.png)

**Comment by sbillard** [comment]
Maybe I do not understand. If you supply the challenge answer you are supposed to be on the password reset screen.

**Comment by JimBrown** [comment]
Yes, you should. But, if you are not an administrator, should you be seeing "You may now set admin usernames and passwords".

On my site, I have CAPTCHA active to combat comment spam. I have also given visitors the ability to register and create an account that only allows them to view images and make comments, nothing else. Registered users do not see the CAPTCHA. That is the only thing that registering does for them. If they forget their password and correctly answer the challenge, they should go to the users tab and be able to reset their password, which is what happens. However, they should not see that "You may now set admin usernames and passwords" as they are not administrators.

Thanks.

**Comment by sbillard** [comment]
"admin" is a legacy term and does mean any user who has access to the admin pages (including the user tab to set his password.) Anyway, I am not sure of what a "proper" definition of "admin" might be since there are multiple possible privileges a user might have. I would rather not change this string since it impacts translations.

**Comment by JimBrown** [comment]
I wasn't thinking of changing the string... More along the lines of just not displaying it if the user does not have any admin privileges. In my example above, a "regular" user has only the "post comments" and "user" rights, no others. Perhaps if the logged in user does not have "admin" rights under "general", do not display that string?

**Comment by JimBrown** [comment]
Well... that was a bit more drastic than I was suggesting... ;-) But it does take care of things.

Thanks.

**Comment by sbillard** [comment]
Well, you could not actually set usernames. So the simplest thing was to just get rid of that part of the message.
