### ISSUE TITLE
Search not returning `pages`

### ISSUE THREAD

**Issue by JimBrown** [ZenPhoto20/ZenPhoto20#348]
Tested on `zenpage` theme. Search is not returning any pages that match the search terms. It is returning `news` as well as `images` and `albums`.

**Comment by JimBrown** [comment]
Never mind. I found the option that controls what is returned. Sorry about that.

**Comment by sbillard** [comment]
No problem. Thought that would be the case, but did not get a change to check before you updated the ticket.
