### ISSUE TITLE
favorite handler: multi option does not change output of printAddToFavorites

### ISSUE THREAD

**Issue by Jens2014** [ZenPhoto20/ZenPhoto20#350]
Hi,
doesn't matter if I select or deselect the favorit_multi option - function printAddToFavorites prints the text input beside the button. In the database the values seems to be correct (deselected = 0, selected = 1).
Thanks in advance.

**Comment by sbillard** [comment]
This is not the behavior I see. With multi set there is a text box for the name of the instance. Without it set there is no text box. 

However, if you have already created a named favorites instance the multi option is overridden and multi is active. Might that be the case?

**Comment by Jens2014** [comment]
Ah, I've got it. Thanks for pointing me to the right direction. You are absolutely right. I have had an already created instance. And this was the case.
Have a great day!
