### ISSUE TITLE
Fatal error in Setup

### ISSUE THREAD

**Issue by Anniedee** [ZenPhoto20/ZenPhoto20#354]
I wanted to adjust the metadata (under Options, Images tab) and add some IPTC items (headline, caption, title, credit.) I also unchecked a few metadata that did not seem necessary for my site. 

Then I got a warning when I saved my options: 
+=====================================+
ZenPhoto20 has detected a change in your installation.

setup has been requested by:
SubIFD Metadata
The change detected may not be critical but you should run setup at your earliest convenience.
+=====================================+

So when I ran setup I got this fatal error:

+=====================================+
Fatal error: Call to undefined function site_closed() in /home/donaldar/public_html/zp-core/setup/index.php on line 1389
+=====================================+

I tried setting the metadata back to the defaults, but the site is just plain unhappy now. 
It wants to run setup and it can't.

**Comment by sbillard** [comment]
This is fixed now in 1.1.6.3. However, there may well be something else wrong. The code in error is only executed when there is a problem with the version number of the .htaccess file. So this error should have shown up the very first time you installed ZenPhoto20 or something has caused a change in your .htaccess file.

Unless you have some site specific rewrite rules I recommend you remove your .htaccess file and let the ZenPhoto20 setup re-create it.

**Comment by Anniedee** [comment]
OK, thank you. I will upgrade. I don't have anything special in the .htaccess file. So I will let the program re-create it.
