### ISSUE TITLE
Parse error in functions.php during setup

### ISSUE THREAD

**Issue by Jens2014** [ZenPhoto20/ZenPhoto20#356]
Hi, while executing setup I get the following error:
`Parse error: syntax error, unexpected T_PAAMAYIM_NEKUDOTAYIM in <...>/zp-core/functions.php on line 2474`
I have tried versions 1.1.6.0 and 1.1.6.3. The PHP version is 5.2.17.
Thanks in advance.

**Comment by sbillard** [comment]
This is a PHP error. The PHP version you are running is past its end of life and no longer supported since 2011. https://www.akeebabackup.com/home/news/1501-end-of-php52-support.html

You should upgrade your PHP to version 5.3 at least.

**Comment by sbillard** [comment]
A possible solution if you cannot upgrade your PHP would be to change the line in question:

`				$exifvars = array_merge($exifvars, $handler::getMetadataFields());
`

to 
`				$handler =  $handler::getMetadataFields();
				$exifvars = array_merge($exifvars, $handler);
`

I do not know for certain that this will work as it will depend on PHP 5.2.17 which I cannot test.

**Comment by Jens2014** [comment]
Oh it was not in my mind that it is already outdated. Temporary I have managed it by running PHP 5.6 as fcgid which works fine during the migration period of my entire site. Aftterwards I will be migrated to a server with an current PHP version. Sorry for wasting your time and thanks a lot for your effort.
