### ISSUE TITLE
Can´t view images in album

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/ZenPhoto20#377]
ZP20 1.1.7.12
In zpArdroise and zpFocus theme I can´t view images in albums. Albums simly seem empty, but album thumbs are OK + image pages are OK too.

**Comment by sbillard** [comment]
Seems a general problem, not theme related. Testing the fix right now.

**Comment by Mates-K1** [comment]
Thank you for the very quick response. :)
