### ISSUE TITLE
Gray Highlights theme - two small bug

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/ZenPhoto20#389]
Lets see picture:
![grayhighlights](https://cloud.githubusercontent.com/assets/7648991/8022036/c839e80e-0cb9-11e5-96fa-e821f9aa40b4.jpg)

1. On mouse hover, images thumbs frame isnt moving (folder thumbs are OK). Tested in FF, IE, Chrome.

2. In path to actual position in gallery, name of all parent albums have first letter capitalized.

And I have small question: Is there any reason that hovered thumbs have GPS in right upper corner and non-hovered in right bottom corner?
I think it would by nice to have GPS icon in same place.

**Comment by sbillard** [comment]
#1 is a theme css incompatibility with the flaf_thumbnail plugin. The plugin inserts a `span` element into the HTML to contain the image and the gps overlay. The theme css causes the span element to be shifted. Basically, the theme and the plugin are fighting for control of the layout and neither wins.

#2 is a theme choice. The theme uses `text-transform: capitalize;` to capitalize those characters.

**Comment by sbillard** [comment]
I have managed to fix the CSS problems in the them so it is compatible with flag_thumbnail.
