### ISSUE TITLE
Public favorites album - img name problem

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/ZenPhoto20#397]
If images in public favorites album have same name, thumbs are ok, but all links are to first image with that name.

**Comment by sbillard** [comment]
Can you check if this same issue is true for dynamic albums? Favorites are just a special instance of dynamic albums.

**Comment by Mates-K1** [comment]
When creating dynamic album in backend in my main gallery:
Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 523800 bytes) in /net/home/skaut.zamberk.cz/html/galerieonline/zp-core/zp-extensions/optionalObjectFields.php on line 95

I tried it in my personal gallery and yes, there is same issue with dynamic album.

**Comment by sbillard** [comment]
for the allowed memory error we will need a full stack trace of the error. oprionPObjectFields should not be involved in a dynamic album creation. That plugin adds/removes fields from the database.

**Comment by sbillard** [comment]
can you provide a link to your favorites album with this issue? I have tried to reproduce it and all is working as expected for me. In particular, all links have the correct album as part of the link.

**Comment by Mates-K1** [comment]
Your login is still alive.
http://skaut.zamberk.cz/galerieonline/index.php?album=fotokniha_70let/katule-favorite.fav
For example second and third image in this album.

My links only contain image name: ".....fotokniha_70let/katule-favorite.fav&image=002.jpg".
(I use mod_rewrite off ???)

And this issue is in my second gallery too - same provider, but another server,...

**Comment by sbillard** [comment]
Analysis of the problem:

Favorites albums and Dynamic albums "mimic" physical album folders. The link naming conventions take advantage of the fact that there can be only one file of a given name in a folder, thus the album name/image name is a unique combination. To preserve the album folder parigam the links for images within a dynamic album or favorites album use the "album name" of the object in place of a physical folder name. There is no information available as to "which" instance of a non-unique named image is being referenced.

A potential solution to the situation would be to add a parameter to the link to indicate the instance number. This would most likely need to be as a query parameter, e.g. &instance=3. This would, however, make "ugly" links, specially for people who use mod_rewrite. It should be possible to omit this parameter when there are no conflicting names. BUT, all this will add overhead that will be useless for most sites.

At the moment I am still considering if such a change should be made.

**Comment by sbillard** [comment]
I have found a satisfactory fix. It is in the 1.1.9.1 support build. Please give it a try.

**Comment by Mates-K1** [comment]
Yes, it works. :)

Thank you very much.
