### ISSUE TITLE
Wrong Czech character in image desctiprion - TinyMCE issue?

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/ZenPhoto20#401]
![char](https://cloud.githubusercontent.com/assets/7648991/8512497/69545052-2345-11e5-90ac-a73f6b6a7065.jpg)
All images descriptions younger than about two months have wrong Czech characters - some are missing, some are replaced by HTML entities. For example á, š, Á, é...
In backend, all is ok.

When I disable TinyMCE editor for zenphoto and manually repair description, characters are displaying ok. Set different TinyMCE setting didnt helped (Ribbon, Slim,...). When I turn TinyMCE on and saved description again, issue is back.

Filesystem Charset: Unicode (UTF-8)

See example:
http://skaut.zamberk.cz/galerieonline/index.php?album=stredisko/zavody/2015_05_02_svojsikuv_zavod_letohrad&image=019.jpg

**Comment by sbillard** [comment]
Could you make this page unprotected? I can never remember the user/password for your site.

This appears to be a problem with PHP handling of decoding/encoding of html entities on some servers. It works locally on my Windows system but fails on my server test site. Check the html source and see if the š is encoded `&amp;scaron;`. If so, then it is the same issue I have found on my server test site.

**Comment by Mates-K1** [comment]
Your fix in 1.1.9.3 works for me.
Thanks for fast response. :+1:
