### ISSUE TITLE
Problems with a new bilingual website

### ISSUE THREAD

**Issue by michgagnon** [ZenPhoto20/ZenPhoto20#405]
Hello,

Last time I installed a Zenphoto20 gallery, it was around version 1.0.x. I had also upgraded an older Zenphoto gallery, but all of them were in a single language: either French or English.
Yesterday night, I started to develop a brand new CMS that will be used equally for text and photos ; but the trick is that it has to be bilingual (French-English).

Setup installation: 
–  Windows 7 Professional 64 bit French, with XAMPP 5.6.8, albeit using PHP 5.4.7.
(I have an issue with PHP 5.6.8 on XAMPP: gettext doesn't work, so I'm back to 5.4.7).
– Zenphoto20 version 1.1.9.5 (official) – taken from Github (download zip) on 2015-07-06 (dc587579cf)
– Browser : Firefox in French, with French as preferred language (English in second)
– During installation, I defined the "Administrator" language as French, and installed languages French, English, and http_Accept_Language. I also checked multilingual interface.
– Finally, I also checked with another brand new installation that was only in French (only language checked: French). So far, all language-related issues only appear on a bilingual website.

First comment: WOW! Even though not much has changed on the surface compared to the old days, I notice a steep increase in flexibility and customization. Over all, it seems to work correctly, but I still have to fine-tune the theme and upload some "practice stuff" locally before I dump everything on the production site. However, I found quite a few bugs – all but three are related to the mutilingual situation. So here is my list, with illustrations all along.

#### Initial ZenPhoto20 Install screen.
Check marks appear all along, but there is a missing symbol when a step hasn't been performed yet.
![zp20-01-installscreen](https://cloud.githubusercontent.com/assets/2497527/8553119/4095f286-24af-11e5-9a51-a16e7c2d73c1.png)

### English-only Gallery page
Right after I finished the setup, I am asked to define the Administrator account. This is what I see once I logout, and also if I load from scratch at "npdo.localhost/site". Note that there is no content yet in the site, but the two strings "Gallery" and "You can insert..." have been translated.
![zp20-02-installscreen](https://cloud.githubusercontent.com/assets/2497527/8553191/b77e1ef0-24af-11e5-8824-97ac0c4cf264.png)
*Note: Appears in French in a French-only installation –> OK*

### In the administrative pages, under "Plugins – Information box for various extensions:
There is a fatal error listed at the bottom of the following extensions:
– bxslider_thumb_nav 
– class-video : description is empty
– GalleryArticles (shown below)
– paged_thumbs_nav
– slideshow
– slideshow2
– viewer_size_image
– xmpMetadata : description is empty
![zp20-03-configextensionswithnewinstall](https://cloud.githubusercontent.com/assets/2497527/8553243/0e95a618-24b0-11e5-8691-f194d9cee216.png)
*Note: Similar problems in a French-only installation*

### Challenge phrases appear in English only, but only in the French dialog box
For the 1st one, I copied the question from the French box to the English box; I haven't done so – yet – for the other phrases.
By the way, I have a question relative to translation: do the questions need to be the same in all languages? If one changes language at some point, how would ZP20 correlate, say, a question in English with a reply in French?
![zp20-04-challengephrasesinfrenchnotinenglishalsoforcontacts](https://cloud.githubusercontent.com/assets/2497527/8553653/e3a9b1ee-24b2-11e5-92bb-62c480c8e86a.png)
*Note: Challenge phrases appear in French in a French-only installation –> OK*

### Content of the Contact Form only in English; however it appears only in the French dialog box
I have seen a similar problem in other plugins. Basically all the places where multilingual user-sentences exist, they don't seem to appear (and yes, I definitely know that these sentences were translated).
![zp20-06-contactformphrasesinenglishonly](https://cloud.githubusercontent.com/assets/2497527/8553720/43cd6d18-24b3-11e5-8590-38aa2c4c1999.png)
![zp20-07-pagedthumbstextissues](https://cloud.githubusercontent.com/assets/2497527/8553761/9b3252bc-24b3-11e5-9f5f-d279db89bdd3.png)
 *Note: Contact Form and Paged Thumbs contents appear in French in a French-only installation –> OK*

### Number of cached processes
Back in Zenphoto 1.4.5, there was a slider. I think there should either be a slider or a dialog box, otherwise there is no point in this line.
![zp20-05-cachingconcurrency-noinputvalue](https://cloud.githubusercontent.com/assets/2497527/8553726/5b2f3086-24b3-11e5-8cb0-4cf67710a798.png)
*Note: Same problem in a French-only installation*

### A suggestion
Finally, one suggestion. Under Options –> Plugins, plugins are now configured one at a time, which makes sense to avoid problems with server overload. I wonder if it would be possible to add "previous – next" buttons at the bottom to help with configuration.

Thanks

**Comment by sbillard** [comment]
Lots of stuff here. I will try to address these one at a time.

*missing symbols when setup has not been performed*

These symbols are "filled in" when the browser receives the image. It is generated by the plugin setup process if all goes well. So one of two things has happened here. There were errors in the plugin setup  or the browser  has not waited long enough for the server to serve the images. Errors in the setup could be because too many processes are being run. These can be limited by the cache concurrency setting. All this is basically the same as zenphoto 1.4.5, though. If there were actual errors the symbols should have become red Xes.

**English-only Gallery page**

Does this happen only with http accept from the browser? What happens if you select French via the dynamic locale plugin? If you enable the **debug** plugin you can list out the browser HTTP accept settings to be sure that they are what you think.

**Plugins – Information box**

I can reproduce this, I will look into it after finishing this response.

**Challenge phrases appear in English only**

Could you by chance have run setup first on a install where gettext did not work? Setup attempts go collect the translations for these items. It is also possible that there are no language translations for them. There may also be a bug in handling this situation. I will add that to the list to check out.

**Contact Form only in English**

Probably the same issue as above.

**Number of cached processes**

This is a bug, there should be a slider.

**previous – next plugin**

Sounds like a good addition, I will add it to the list.

**Comment by michgagnon** [comment]
Hello,

Thanks for the feedback. You nailed it correctly! 
I had run the initial setup when gettext did not work. I discovered the problem once I had configured the Administrator's account. It is only at that point that I realised that gettext was not working. So I went back to PHP 5.4.7 and ran Setup again, but it seems those strings were not updated when I ran again Setup.
BTW, I *think* I didn't see an error message in the initial setup because php_gettext was there in php 5.6.8; it just doesn't work!

To make a long story short, I did a completely new install (new files, new database) using PHP 5.4.7 all along, so Gettext is working from the start. My gallery and administrator setup is exactly the same as previously, that is:
– Browser : Firefox in French, with French as preferred language (English in second)
– During installation, I defined the "Administrator" language as French,
– Under Options –> General, installed languages French, English, and http_Accept_Language. I also checked multilingual interface (like before)

This time, I get much better results. Generally speaking, strings are populated correctly, with the proper language in each place. So most of the problems are gone. I still can identify one or two minor language-related issues. For completeness, I will go back on each of them in the same order

####Initial ZenPhoto20 install Screen
Problem with empty image boxes. I'm aware that the check mark comes from the various plugins as they are configured. It is just that I thought that there would be another icon before that (something like (...)) and that the icon was missing.

####English-only initial gallery page... and challenge phrases
Appears correctly in French.
In the administrative panel, under "Options –> Gallery", I see that the Title and Description appear in French (adequately: French text in the French dialog boxes), but nothing appears in the other languages. 
In other words, the default English title and description are blank; I think they should have a default description in English too.

I have the same problem with the Challenge phrases found under Options –> Security. The French default questions appear under the French language, but nothing appears in the other languages.

#### Under Options –> Plugins: Contact form, Zenpage,,,
Key sentences in these plugins correctly appear in all languages, including those I have not checked in.


So in hindsight, sorry for the initial feedback. I never thought that not having a functional gettext function would create a problem that would not be corrected by a second run of the Setup process.

In the meantime, I have also identified a couple of translation errors – words that are not used the way I thought they were. Nothing serious. I will also send you a couple of suggested improvements to the user guide.

I will probably run another setup from scratch tomorrow night with the updated CMS.

Thanks.

**Comment by sbillard** [comment]
I have fixed the **Plugins – Information box** issues. I think the root problem may also have caused the setup icon issue, but not sure.

**Number of cached processes** for some reason the slider does not show up in some installs. It works correctly on my WAMP Windows 7 test bed but not on my hosted test beds. The code, etc. is all there, so it is some configuration difference. I do not know what yet, but in the mean time I am adding an input box so at least the value can be changed.

Still investigating other issues. I will have some fixes up tonight, at least, so best use that build for your testing tomorrow.

**Comment by sbillard** [comment]
fixes are up. Probably best to start a new ticket and close this one. Maybe multiple tickets, on per issue. Those are more easily dealt with.

**Comment by sbillard** [comment]
A couple of "observations" with regards to the language strings.

These are all "option" type strings that have their defaults set during initial setup. If there is already an option present, as there would be on a subsequent setup run the original values will not be overridden (even if they were setup wrong in the first place!) That is because there is no reasonable means to know if they have been modified by the user. This would not be an issue anyway were it not for the bug(s) that caused them to be wrong in the first place.

Second, the original way of creating translation sets had a flaw. If you setup you site with a language other than English and there is no language alternatives to the English text the end result would be that the English text was stored under your setup language. That but has now been fixed. English text will go ONLY under English.

**Comment by michgagnon** [comment]
OK. Thanks for the explanations and thanks for the quick fixes. The (not so) funny thing is that I had upgraded XAMPP about 2 months ago, but since then I had only used it for regular, single-language websites. So it is only yesterday that I discovered a problem with gettext. I have asked for support on the XAMPP forum and will see how it goes from there.

Your explanations regarding the problem make sense. If I had thought about it, I would have done a new setup. It would have saved time to both of us,

**Comment by sbillard** [comment]
Well, even though the problem was with gettext it did uncover a different issue with the English text being assigned to French, so a positive benefit.

**Comment by sbillard** [comment]
Michael:

Perhaps you can help with debugging the missing slider--ticket #408.

It is not failing on my local install and my hosted test base does not give me access to the apache access log.

One possible cause would be the jqueryui css not getting loaded. Can you look in your access logs to see if it is being loaded for you? Follow up on the #408 ticket.

**Comment by michgagnon** [comment]
Hello,

I replied in the ticket 408 (it won't show directly because it is not open).

Michel Gagnon – michel@mgagnon.net <mailto:michel@mgagnon.net>
Montréal (Québec, Canada) – mgagnon.net <http://mgagnon.net>
