### ISSUE TITLE
jqueryui sliders do not show in some installations

### ISSUE THREAD

**Issue by sbillard** [ZenPhoto20/ZenPhoto20#408]
They show up and work on my WAMP Windows 7 test bed but not on my hosted testbeds. So far as I can see the HTML of the two sites is equivalent.

**Comment by michgagnon** [comment]
It is not failing on my local install and my hosted test base does not give me access to the apache access log. One possible cause would be the jqueryui css not getting loaded. Can you look in your access logs to see if it is being loaded for you? Follow up on the #408 ticket.
—--
Hello,

I checked with last night's installation and the file is NOT being loaded. I see the following files being loaded, but nowhere do I see a file called "jqueryui.css":
127.0.0.1 - - [09/Jul/2015:13:36:34 -0400] "GET /site/zp-core/js/jqueryui/jquery-ui-zenphoto.css HTTP/1.1" 200 30021 "http://npdo.localhost/site/zp-core/admin.php" 
127.0.0.1 - - [09/Jul/2015:13:36:34 -0400] "GET /site/zp-core/js/jqueryui/jquery-ui-zenphoto.js HTTP/1.1" 200 240427 "http://npdo.localhost/site/zp-core/admin.php" 
127.0.0.1 - - [09/Jul/2015:13:37:11 -0400] "GET /site/zp-core/js/jqueryui/i18n/datepicker-fr.js HTTP/1.1" 200 1290 "http://npdo.localhost/site/zp-core/admin-edit.php" 
127.0.0.1 - - [09/Jul/2015:13:37:33 -0400] "GET /site/zp-core/js/jqueryui/images/ui-bg_glass_75_e6e6e6_1x400.png HTTP/1.1" 200 262 "http://npdo.localhost/site/zp-core/js/jqueryui/jquery-ui-zenphoto.css" 
127.0.0.1 - - [09/Jul/2015:13:37:33 -0400] "GET /site/zp-core/js/jqueryui/images/ui-icons_222222_256x240.png HTTP/1.1" 200 6922 "http://npdo.localhost/site/zp-core/js/jqueryui/jquery-ui-zenphoto.css" 
127.0.0.1 - - [09/Jul/2015:13:37:58 -0400] "GET /site/zp-core/js/jqueryui/jquery-ui-zenphoto.js HTTP/1.1" 200 240427 
127.0.0.1 - - [09/Jul/2015:13:37:58 -0400] "GET /site/zp-core/js/jqueryui/jquery-ui-zenphoto.css HTTP/1.1" 200 30021 "http://npdo.localhost/site/zp-core/admin-options.php?page=options&tab=image"

I have put the complete access and error log here:

**Comment by sbillard** [comment]
Turns out it was a javascript error. Not at all sure why it worked some places and not others.

**Comment by michgagnon** [comment]
Thanks.

I will try tonight with yet another new version.

Regards,

Michel Gagnon – michel@mgagnon.net <mailto:michel@mgagnon.net>
Montréal (Québec, Canada) – mgagnon.net <http://mgagnon.net>
