### ISSUE TITLE
Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/ZenPhoto20#417]
1. Lets make some search.
2. Choose one of images.
3. Open image for editing.
4. Save image.
5. After returning to frontend, you get:
Warning: Invalid argument supplied for foreach() in .............../zp-core/class-search.php on line 1738

6. For another search, search-used texts are excluded from searching (= 0 hit for another searching).

ZenPhoto20 1.1.9.3

**Comment by sbillard** [comment]
#5 should be fixed in the current support build.

I do not understand #6. If you do a search from the result of a prior search, the search is limited to the scope of that prior search unless you override the "within" selection.

**Comment by Mates-K1** [comment]
Nr. 5 - thanks, it works. :)
Nr. 6 - this strange behavior disappear with nr. 5 fix
I did step 1 - 5, after that I went to main page of gallery and made new search. All previous searches ending with "zp-core/class-search.php on line 1738" had 0 hit in new search.

**Comment by sbillard** [comment]
Ok, maybe it was a side effect of the bug. I will close this ticket. If #6 comes back open a new one.
