### ISSUE TITLE
Slideshow plugin loses jquery setting on update

### ISSUE THREAD

**Issue by nerdykit** [ZenPhoto20/ZenPhoto20#421]
Every time I do another update using the extract.php.bin I find that the Slideshow plugin has reverted to the jquery Colorbox setting and I have to change it back to the setting I use (jquery Cycle).  Either this is normal in which case this issue can be closed immediately or else the Slideshow plugin should be retaining its setting on that basic menu and isn't.

Thanks

NK

**Comment by sbillard** [comment]
It should not do that. But at the moment I cannot figure out why it is changing.
