### ISSUE TITLE
zpMobile theme - bad gps icon align + page link

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/ZenPhoto20#426]
1)
![zp_mobile_gps](https://cloud.githubusercontent.com/assets/7648991/9068235/8514b138-3ae2-11e5-96e2-cb2bd72695a1.jpg)

2) Pages link in top menu has "error loading page". Link in sidebar is OK.

(W 8.1, Chrome, IE, Firefox)

**Comment by sbillard** [comment]
It would really help if you made separate tickets for separate problems. The fix for the pages link is quite simple so easily made but the gps icon is some kind of CSS issue with zpMobile and therefore more difficult and time consuming to find and fix. So we have one fix but cannot close its issue.

**Comment by Mates-K1** [comment]
Ok. Sorry for that.
Next time I will do it better.
