### ISSUE TITLE
Album password deleted automatically

### ISSUE THREAD

**Issue by ariep** [ZenPhoto20/ZenPhoto20#430]
One can set an album password (on the album option page). This works: guests need to provide the password to view the album.

However, if you as admin revisit the album options page, the password field is empty. (The hint is still there.) If you change any other options on the page and click on "Apply", the password is indeed unset and anyone can view the album.

This is bad.

**Comment by sbillard** [comment]
I do not see this behavior.

You should see an **Album password** link with a "locked" lock icon. So long as you do not click on this link saving should not reset the album. But if you click on the link and it is open when you save the album it will indeed set the password to empty unless you supply one.

For security reasons all passwords in ZenPhoto20 are hashed before being stored. For this reason the password field cannot be populated with the original password, thus the "closed" (meaning don't change) password field.

**Comment by ariep** [comment]
You are right: this is user error, not a bug. I wanted to check that the password was set by clicking on the "Album password" link on the left, but as you explained, this does not show the password, but instead clears it.

I find the interface a bit confusing. [This pull request](https://github.com/sbillard/ZenPhoto20-DEV/pull/2) adds some text next to the lock icon to clarify this behaviour a bit. (It also fixes an unrelated error in the SQL query syntax that popped up for me.)
