### ISSUE TITLE
Choice of chroma subsampling

### ISSUE THREAD

**Issue by Beep6581** [ZenPhoto20/ZenPhoto20#436]
Hey

I need to disable JPEG chroma subsampling (4:4:4) so that the color of pixel-wide details (screenshots, watermark image, watermark text) are not ruined. ZenPhoto lets me only set JPEG compression, not chroma subsampling. Is this something ZenPhoto20 can let the user choose? If not, please consider this a feature request.

**Comment by sbillard** [comment]
There are two possible image handling libraries for PHP, the GD library and Imagic.

There is no control over the chroma sampling with the GD library. I am not very familiar with the Imagic library, but a quick search of its functions did not turn up anything that might do.

If you can discover a means of controlling this sampling we will gladly add an option to ZenPhoto20 to do so.

**Comment by sbillard** [comment]
Not apparently possible.

**Comment by Beep6581** [comment]
Chroma subsampling is controlled via imagemagick using "-sampling-factor 1x1" for example.

Issue opened for GD:
https://bitbucket.org/libgd/gd-libgd/issues/141/jpeg-chroma-subsampling

I don't know what "Imagic" is or what their homepage/issue tracker is, could you help?

**Comment by sbillard** [comment]
imagemagick is an image processing software. There is an Imagic extension to PHP for using imagemagick and ZenPhoto20 provides for use of that extension as an alternative to the standard GD library. Your server may or may not have Imagic installed. 

With your find I have found the PHP function setsamplingfactor() http://php.net/manual/en/imagick.setsamplingfactors.php 

Note that there is no description of what the parameters might mean. If you think that this can work for you we can add an option to the Imagic library to allow you to set these values. But probably we need to have some description for what each of them does.

**Comment by Beep6581** [comment]
That's great!

The parameters are standard stuff.
4:4:4 = 1x1 = no chroma subsampling
4:2:2 = 2x1 = chroma sampling with half horizontal resolution
4:4:0 = 1x2 = chroma sampling with half vertical resolution
4:2:0 = 2x2 = chroma sampling with half vertical and half horizontal resolution

More info:
https://en.wikipedia.org/wiki/Chroma_subsampling
The examples on that Wikipedia page are really bad, I'll update them some time.

You really want to use 4:4:4 (1x1) when uploading images with 1-pixel-wide (or 1-pixel-tall) color details. This usually includes screenshots or photos with some overlaid pixel-wide text or watermark. Using no chroma subsampling on normal photos without such overlaid stuff is usually a waste of disk space and bandwidth as you won't see a difference unless you're looking for it.

**Comment by sbillard** [comment]
The api example is: `$imagick->setSamplingFactors(array('2x2', '1x1', '1x1')); ` but it does not say how that maps to what you have shown above. Does this map to 2:1:1? Have to know the mapping to translate the option to the parameter list.

Anyway, I do not have access to the Imagic extensions so cannot test any changes. I can provide them for you to test, though, it that is ok.

**Comment by Beep6581** [comment]
I have to put my website aside for a few weeks so I won't be able to test yet, but I can help you here if I can.

This PDF explains chroma subsampling very well:
http://dougkerr.net/Pumpkin/articles/Subsampling.pdf

Based on it, I presume:
1x1 1x1 1x1 = 4:4:4 = 1/1
2x1 1x1 1x1 = 4:2:2 = 2/1 = 4x1 2x1 2x1
1x2 1x1 1x1 = 4:4:0 = 1/2 = 1x4 1x2 1x2 = 2x2 2x1 2x1
2x2 1x1 1x1 = 4:2:0 = 2/2 = 4x4 2x2 2x2

**Comment by sbillard** [comment]
You can try this out from https://github.com/sbillard/ZenPhoto20-DEV

Note that I cannot test as I do not have Imagick capabilities. There is now an option for "Chroma sampling" on the image options tab if Imagick is enabled.

**Comment by Beep6581** [comment]
I can't test it out practically for a while, but I looked at your patch and it looks great, thank you!

By the way, looks like there is a typo "$decending" which should be "$descending" in https://github.com/sbillard/ZenPhoto20-DEV/commit/7d41f59baa38cc5bfa8d2642dc248dfd97a49aed

**Comment by sbillard** [comment]
This can be reopened if needed, but it is pointless to keep it open at this point.
