### ISSUE TITLE
"Object not found" for full image

### ISSUE THREAD

**Issue by ariep** [ZenPhoto20/ZenPhoto20#438]
When trying to access a full image for the first time, I get to see it after a short delay. I checked, and indeed a symlink is created for this full image under the cache directory.

However, when I browse the gallery a bit more and then return to this same full image, I get a Zenphoto error page with the following text:
```
Error: the requested object was not found.
Album: cache/Promotie%20Arie%20%282015%29
Image: 22f1fc32[...].IMGP6009_FULL.jpg
```
The URL of this error page containes doubly URL-encoded characters: the space character in the name of the album is represented by `%2520`, for example. When I manually remove all the `25`s, indeed the full image is presented instead of the error.

I'lltry to fix this myself later when I have some time, but maybe someone else knows where to look for the cause of this error right away.

BTW, I have the "Obscure cache filenames" option set, as you may have guessed from the image file name.

**Comment by sbillard** [comment]
I have tried this with the "basic" theme and it does not double encode these URLs. What theme are you using? 

Look to where `getFullImageURL()` is being used in the theme. That is a "raw" version of the URL. The code to use it as a link should be `html_encode(pathurlencode($fullimage))`

**Comment by ariep** [comment]
I also have the 'basic' theme. Not sure why this happens for me but not for you; maybe some setting? I just updated to latest git version.

Debugging shows that `getFullImageURL()` (in the case where a symlink to the full image already exists) returns a path like
```
/pixra/cache/Promotie%20Arie%20%282015%29/5b4035f3[...].IMGP6057_FULL.jpg
```
, so it is already URL-encoded.

**Comment by ariep** [comment]
Digging around a little, I think I found the culprit.

The function `getProtectedImageURL` (in `template-functions.php`) contains this line:
```
return WEBPATH . '/' . CACHEFOLDER . pathurlencode(imgSrcURI($cache_file));
```
By itself, this seems OK, but if this path is later again URL-encoded, things go wrong. I guess (from the fact that the double encoding happens only in this particular case) that the encoding in the above code fragment should be removed.

**Comment by sbillard** [comment]
Thanks. Indeed functions should always return un-encoded URLs. The general rule of thumb should be:

Decode when things are fetched from $_GET and $_POST arrays.
Encode when the item is output to the web page. 

Otherwise we get issues like you found and they are particularly difficult to find.
