### ISSUE TITLE
mediaelementjs player has stopped working

### ISSUE THREAD

**Issue by nerdykit** [ZenPhoto20/ZenPhoto20#444]
For the first year or so of ZP20 development the 3rd party plugin player mediaelementjs_player was working with ZP20 but I've just noticed that it's now broken and only the jplayer video player will work.  Any ideas about which recent mods to ZP20 running the basic theme might have broken the mediaelementjs player?

Thanks

NK

**Comment by sbillard** [comment]
Looks like it uses a deprecated function. I have not tried the fix, though.

Did uncover an issue with the LegacyConverter function--that is fixed in 1.2.1.7. Run the converter on the plugin and hopefully the function is the only problem.

**Comment by nerdykit** [comment]
Thanks.  Did as you suggested and that resolved the problem immediately.  I'm smiling again!

Cheers

NK
