### ISSUE TITLE
Suggestion: for image edit page access

### ISSUE THREAD

**Issue by nerdykit** [ZenPhoto20/ZenPhoto20#446]
Not an issue but a suggestion.  The link that lets you move forward through many pages of images in the multiple image edit mode appears only at the bottom of the page, it would be helpful to have it also repeated at the top of the list of images.  Would mean that you don't have to scroll all the way down to change pages when you've got it set for a large number of images per page.

Thanks

NK

**Comment by sbillard** [comment]
Sounds reasonable.
