### ISSUE TITLE
Cant find czech letters in image description

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/ZenPhoto20#449]
Searching can´t find some czech letters in image description (non-case-sensitive). Searching in title works fine.

When description is "Žáža" and searching is "Žáža", result is 0 hits.
When description is "Zaza" and searching is "Zaza" or Žáža", result is ok.

Some of czech letters which I am not able to find: ěščřžýáíéúů

**Comment by sbillard** [comment]
This appears to be caused by the text of the description encoding the á character into an html entity. That should not be happening, but even when fixed your database entries may still have the encoded version.

**Comment by Mates-K1** [comment]
TinyMCE WYSIWYG editor cause this problem.

When I edit description with TinyMCE, HMTL entites are saved in DB. When I disable TinyMCE, description is OK and is searchable.

**Comment by sbillard** [comment]
You are correct, and the fix is a change to the configuration of the tinyMCE editor. You will have to re-save any descriptions that contain these characters.

**Comment by Mates-K1** [comment]
Thanks for fast fix.

I have a several thousand of this description. :) Is there any solution to do it a little bit automatically?

**Comment by sbillard** [comment]
Right off hand, the only thing I can think of is SQL queries that replace the html entity with the actual character. But for that you will need to know which characters and what the html entity is.

**Comment by Mates-K1** [comment]
I tried replacing in DB but now desc length changed, so searching works fine, but desc is not shown neither in backend nor frontend.

**Comment by sbillard** [comment]
My fault. Sorry those are serialized arrays. I guess editing/saving is really the only practical way to fix these.

**Comment by Mates-K1** [comment]
We can do it. :-) One of editors resaved most of images in two hours. :+1:
