### ISSUE TITLE
Favorites vs. Search - browsing results

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/ZenPhoto20#450]
When I browse search results and clicks NEXT (for next image), next result shows.
But when I browse favorites results and clicks NEXT, I get next image from album from which previous image was.

As user I would expect same behavior as in searching.

Is possible to make it in the same way?

**Comment by sbillard** [comment]
Favorites really is not the same as searching. Favorites is a catalog of thumbnails of your favorites, pointing to where they actually reside. So when you click on a thumbnail in your favorites catalog it takes you to the actual image.

Searches take the image out of context. It "belongs" to the search for the duration of the search.

It sounds like you want something that contains your favorites but behaves like an album. That is exactly the functionality the favoritesAlbums plugin provides. Please check it out and see if it meets your needs.

**Comment by Mates-K1** [comment]
Oh, yes. It is one more step, but meets my needs.
Thank you for the explanation.

**Comment by sbillard** [comment]
Thanks, I will close this, then.
