### ISSUE TITLE
" in title prevents displaying text on mouse over

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/ZenPhoto20#453]
Themes: Garland, Gray Highlights, zpArdoise, zpBootstrap, zpEnlighten, zpFocus, zpMasonry, zpMinimal, zpskeleton

Where: frontend screen with images thumbs and album thumbs.

If there is " in title (album or image), all text after this symbol is not displayed on mouse over.

**Comment by sbillard** [comment]
Note that there are many instances of missing html encodings. The fix is being staged at https://github.com/sbillard/ZenPhoto20-DEV/ because the magnitute of changes makes it vulnerable to typographic errors. Please try that build and report on any issues.

**Comment by Mates-K1** [comment]
It doesnt work in:
- zpMasonry (album thumbs), zpMinimal (album thumbs),
- zpMobile (ALL album thumbs - NO TITLE),
- Effervescence+ (album thumbs - &quot; instead of "),
- zpBootstrap (img thumbs),
- zpEnlighten (ALL album thumbs - three dots instead of titlle).

**Comment by sbillard** [comment]
Pass two is now available, same link.

**Comment by Mates-K1** [comment]
It doesnt work in:
Effervescence+ -- album thumbs - `&quot;` instead of "
(sorry for bad formating in previous post)

**Comment by sbillard** [comment]
Should fix EF+. same link.
Thanks for your patience in testing these changes.

**Comment by Mates-K1** [comment]
Yes, now it works fine. :+1:
