### ISSUE TITLE
getRandomImagesAlbum not working the way it used to.

### ISSUE THREAD

**Issue by JimBrown** [ZenPhoto20/ZenPhoto20#458]
It would appear that `getRandomImagesAlbum` is NOT searching subalbums anymore IF a root album folder name is passed to it. It used to. It does find images in the root album, but does not find images in any subalbums.

If no root album folder name is passed, it does search all subalbums.

**Comment by JimBrown** [comment]
Doing a compare of the latest file with an old copy, this appears to be the commit that changed the function: https://github.com/ZenPhoto20/ZenPhoto20/commit/16dc9a9c5ad5322d7dd53b3bee7d8db0c3276638

**Comment by sbillard** [comment]
It does not make any difference what is passed. Only first level album images are looked at. But the 0ba8e85f90cd16ffed36f95eeea320a0b375a0a8 will look in subalbums if there are no images in the primary album.

**Comment by JimBrown** [comment]
Ok, it is working now.

Thanks.
