### ISSUE TITLE
PHP Sessions are required

### ISSUE THREAD

**Issue by Heart1010** [ZenPhoto20/ZenPhoto20#465]
I want to update ZenPhoto20 to latest version and get this error on the update check page...
```
PHP Sessions-Unterstützung [scheint nicht zu funktionieren]
Fehler!

PHP Sessions are required for administrative functions. Check your session.save_path (/tmp) and the PHP configuration [session]settings
```
But sessions are enabled!?
![sessions](https://cloud.githubusercontent.com/assets/1481680/11898869/6620fb00-a59b-11e5-9e37-d5fbdc5e6efc.png)

**Comment by sbillard** [comment]
There are a couple of reasons this might occur. But first please be sure you are using the 1.2.2.6 build as there have been some fixes in this area.

Should that not work check the file PHP.ini file for the session save path and make sure it is accessable by ZenPhoto20.

**Comment by Heart1010** [comment]
...latest release here is 1.2.2.0!?

https://github.com/ZenPhoto20/ZenPhoto20/releases

**Comment by sbillard** [comment]
I am referring to the support build you can download from the download button at https://github.com/ZenPhoto20/ZenPhoto20

**Comment by Heart1010** [comment]
So you mean downloading the master branch and overwrite every existing file on the server?

**Comment by sbillard** [comment]
Thanks for the update. I guess I should make a release of the support build.

**Comment by Heart1010** [comment]
:+1:
