### ISSUE TITLE
Bugs with Menu_manager and Dynamic_Locale

### ISSUE THREAD

**Issue by michgagnon** [ZenPhoto20/ZenPhoto20#469]
Hello,

In the latest version (1.2.3), I found the following bugs:

–  Dynamic Locale plugin

I have not tried it as it is poorly supported by my local installation, but I wonder if the description of the "Language links" buttons should be corrected. Right now, I see:
– Select Use subdomains and links will be in the form language.mg.localhost where language is the language code, e.g. fr for French.
– Select URL and links paths will have the language selector prepended in the form mg.localhost/language/...

I think they should take into account the path to the gallery, so they would be respectively "language.mg.localhost/photos/" and "mg.localhost/photos/language/..." (and not mg.localhost/fr/photos/...)
 –> It would need you would have to change the definition of %1$s.

*********************************

– Menu Manager Plug-in

When activated, it creates a "Menu" tab. When I look at it, is allows me only to edit the following themes: Effervescence, Garland, Zenpage and Zenpage_sja_mg (a copy of the former),

a. Edit the menu "Garland" –> it is always the menu that appears at first, even though I don't use the theme.
b. For both Effervescence and Garland, the first two items appear correctly. The 3rd one, "Règle pour les articles d’actualité (News Articles Rules) is broken. (see image below)

c. If I configure the menu for the Zenpage theme, it works correctly.

Finally, how do I use the extension on another theme, such as zpSkeleton or zpMasonry, which both use pages?  Thanks

Note. I have configured the database in French, with 2 languages available: French and English. I see the same error whether I use it in English or French. The name of the offending rule is:
Règle pour les articles d’actualité (News Articles Rules) – [I use a curly, typographical quote]

![menu_manager_screen](https://cloud.githubusercontent.com/assets/2497527/12072263/2656c752-b0a4-11e5-9e0c-67c2317f5cf1.png)

**Comment by sbillard** [comment]
With regard to your question of how to use menu manager on another theme:

Themes must be programmed to use menu manager. You place ```printCustomMenu()``` on the theme scripts where you want the custom menu to appear.

The included themes that use menu manager all have options to use custom menus (and in some cases which menu to select) the menu is displayed based on the option, usually suppressing the alternate.

Themes also can define specific menus in there themeOptions script. Garland, Efferevescence+ and Zenpage can be used as example implementations.

**Comment by michgagnon** [comment]
Thank you.
