### ISSUE TITLE
Bug with Google Maps and display of EXIF data (continued)

### ISSUE THREAD

**Issue by michgagnon** [ZenPhoto20/ZenPhoto20#477]
Sorry, I couldn't reopen issue #474 so I opened a new one.

Hello,

Long story short, it doesn't work. Both locally on my XAMPP installation and on the live server which uses PHP 5.6 on Apache. I have put one of the basic themes (Zenpage), so you can access the Google Map both for the photo and the album

**Steps done**
– Uploaded all files (zp-core, plugins and themes).
– Reran setup
– Rebuilt both the database and the metadata.

Same photo as before (issue #474):
http://mgagnon.net/photos/fresques2/DSD_4517.JPG.html

(Note that the same problem happens with a few freshly uploaded photos in http://mgagnon.net/photos/fresques2 )

Now I get a different Google Map... still with the wrong data:

Actual latitude and longitude:
Latitude:      45.512625 N
Longitude:   73.566170 W

Location of the Google Map in Zenphoto20 when I showed only the default fields
Latitude:     45.582659
Longitude: -72.442255
https://goo.gl/maps/9yL2CGejou22

Location of the Google Map in Zenphoto20 when I visited Options –> Image –> Exif to show all fields:
Latitude:     45.512625 N
Longitude: -72.433838 W
https://goo.gl/maps/NtohFye52Ws

At first glance, it seems to be an error on the sign of the decimals which would affect negative latitudes and longitudes.
Latitude = 45° 30.7575' (i.e. those are decimal minutes because of the point)
Longitude = -73° 33.9702'

For the Longitude, I think what is done is: (-73) + (33.9702 / 60) = 72.43383°
whereas it should be:  - (73 + (33.9702 / 60)) = -73.566170°

But apart from solving the bug, it should be noted that to apply the solution one needs to actually change which EXIF fields are displayed so that part of the database is actually refreshed.

********************

**Display of EXIF values.**

Again, please refer to bug #474 

If I read the data directly from the jpg file (with Notepad++), I see the following:
```
<rdf:Description rdf:about=''
  xmlns:exif='http://ns.adobe.com/exif/1.0/'>
  <exif:DateTimeDigitized>2015-06-20T14:52:53-04:00</exif:DateTimeDigitized>
  <exif:DateTimeOriginal>2015-06-20T14:52:53-04:00</exif:DateTimeOriginal>
  <exif:GPSAltitude>27/1</exif:GPSAltitude>
  <exif:GPSAltitudeRef>0</exif:GPSAltitudeRef>
  <exif:GPSLatitude>45,30.757499N</exif:GPSLatitude>
  <exif:GPSLongitude>73,33.970184W</exif:GPSLongitude>
  <exif:GPSMapDatum>WGS-84</exif:GPSMapDatum>
  <exif:GPSTimeStamp>2015-06-20T18:52:53Z</exif:GPSTimeStamp>
  <exif:GPSVersionID>2.2.0.0</exif:GPSVersionID>
 </rdf:Description>
```
If you look at the "Image info" data as printed by ZenPhoto20 (complete data is in the previous bug), the following are not OK (displayed with full date, format YYYY-MM-dd HH:mm, but changing the format doesn't solve the issue):
```
Date Created:			-1-11-30 00:00
Digital Creation Date:	-1-11-30 00:00
Digital Creation Time:	-1-11-30 00:00
Original Time Taken:	2015-06-20 14:52	(this is good)
Time Created:			-1-11-30 00:00
Time Digitized:			2015-06-20 14:52	(this is good)

Latitude:	:			45° 30' 45" N	(this value is now OK)
Latitude Reference:		N
Longitude:				73° 33' 58" W	(this value is now OK)
Longitude Reference:	W
```
The "bad" values should probably be the same as "Time Digitized", unless they technically are blank values, in which case it should not be -1-11-30.

Thanks.

**Comment by sbillard** [comment]
1.2.3.5 has a fix for the min-computation of the latitude. 

I need some more details on those dates which are displayed wrong as I have not been able to reproduce them. Look at the HTML for the page where they are displayed. There will be a class on the TD tag that begins with "medtadata_tag". I need to know the tag as it will tell me where the values are coming from. My best guess at this point is that they are unpopulated values that the date formatting is not treating correctly. You can also look at the database record for the image and see if these values show there.

**Comment by michgagnon** [comment]
Hello,

In the HTML page at http://mgagnon.net/photos/fresquesurbaines/DSD_3534.jpg.html I see the following tag, where all the data is displayed: div id="imagemetadata_data".
I do not see any "metadata_tag".

**Database Information**
Here is the database information for photo DSD_3534, as seen through phpMyAdmin
```
id				52
albumid			4
filename		DSD_3534.jpg
title			DSD_3534
desc			NULL
commentson		1
show			1
date			2015-06-20 14:52:53
sort_order		(blank)
height			4000
width			6000
rotation		1
GPSLatitude		45,512624990001 	
GPSLongitude 	-73,566169739953
GPSAltitude		27m
thumbX			NULL
thumbY			NULL
thumbW			NULL
thumbH			NULL
mtime			1434826372
publishdate		2016-01-02 14:23:25
expiredate		NULL
hitcounter		5
total_value		0
total_votes		0
used_ips		NULL
rating			NULL
rating_status	3
hasMetaData	1
owner		administrateur
filesize		NULL
user		NULL

**Comment by sbillard** [comment]
Sorry, It is the image admin page that has those tags. But if the list above is the complete database entry it may lend a clue. No digital date and time fields are there.

**Comment by michgagnon** [comment]
Sorry for the delay, I had a couple of other interruptions. I am not 100% sure of the correspondence between each field in the EXIF vs Zenphoto20, but I understand that when a value is "0" (ex.: IPTCTimeCreated), the EXIF printout shoud either be the same, or n/a (not available, sans objet...), or a blank space.

**Data in the Image Admin Page** as seen in the browser window:
```
35mm Focal Length Equivalent: 	75
Altitude: 	 	 	 	27m
Altitude Reference: 	+
Aperture: 	 	 	 	f/5,6
Artist: 	 	 	 	Michel Gagnon
Byline: 	 	 	 	Michel Gagnon
Camera Maker: 	 	 	Nikon Corporation
Camera Model: 	 	 	NIKON D7100
City: 	 	 	 	 	Montréal
Copyright Holder: 	 	Michel Gagnon
Copyright Notice: 	 	Michel Gagnon
Country/Primary Location Code: 	CAN
Country/Primary Location Name: 	Canada
Date Created: 	 	 	0000-00-00 00:00:00
Digital Creation Date: 	0000-00-00 00:00:00
Digital Creation Time: 	0000-00-00 00:00:00
Exposure Compensation: 	0,67 EV
Exposure time: 	 	 	1/125 sec
Flash Fired: 	 	 	No Flash
Focal Length: 	 	 	50 mm
ISO Sensitivity: 	 	160
Latitude: 	 	 	 	45° 30' 45" N
Latitude Reference: 	N
Lens Info: 	 	 	 	17-50mm f/2,8
Lens Type: 	 	 	 	AF-D G VR
Longitude: 	 	 	 	73° 33' 58" W
Longitude Reference: 	W
Metering Mode: 	 	 	Center Weighted Average
Orientation: 	 	 	Normal (0 deg)
Original Height: 	 	4000 pixels
Original Time Taken: 	2015-06-20 14:52:53
Original Width: 	  	6000 pixels
Province/State: 	 	Quebec
Software: 	 	 	 	Ver.1.02
Sub-location: 	 	 	Ville-Marie (rue Ontario Est)
Time Created: 	 	 	0000-00-00 00:00:00
Time Digitized:  	 	2015-06-20 14:52:53
```

Thanks

**Comment by sbillard** [comment]
The bug is actually in the PHP date formatter. Formatting 0000-00-00 00:00:00 in the "preferred date representation" for the French locale seems to give a "year" of -1. Probably no fix for that, but these dates should be treated as empty data and not displayed. So that fix will be up shortly.

**Comment by michgagnon** [comment]
Thanks.

The fix works great, both for the online version on Apache (Unix) with PHP 5.6 and the local version on XAMPP with PHP 5.4 (running on Windows 7 French Canada).

To make it work, I had not only to refresh metadata (it worked for a few photos) but also to flush the "cache" folder. Then all photos were properly placed.
You can see the general map here: http://mg.localhost/photos/fresquesurbaines/
(sorry, but the "google map" button is not yet on individual pages).

**Comment by sbillard** [comment]
Thanks for the update. But I cannot visit "localhost" to see the results. I did not think about the cache folder, but makes sense. The HTML needs to be regenerated with the correct values.
