### ISSUE TITLE
Albums aren't cleared properly in zpskeleton theme for gallery.php

### ISSUE THREAD

**Issue by jagerman** [ZenPhoto20/ZenPhoto20#480]
themes/zpskeleton/gallery.php has this in it:

    if ($c == 3) echo '<br class="clear" />';

but that should be:

    if ($c == 3) { echo '<br class="clear" />'; $c = 0; }

The current code adds a clearing <br> after the third album, but then never again.  As a result, when there are more than six albums, this is failing to add a clearing <br> after the 6th, 9th, etc., and so you get a messed up album display: I had a longer metadata and description in the 5th album than the 6th, which resulted in the 7th album getting tucked under the 6th instead of under the 4th.

Inside albums, however, subalbums don't have this same problem because album.php (which does essentially the same thing to display subalbums) has:

    if ($c == 3) {
        echo '<br class="clear" />';
        $c = 0;
    }

And so it appears that the "$c = 0;" part was just missed for gallery.php.

An alternative solution is to change both to the slightly cleaner:

    if ($c % 3 == 0) ...

without the $c = 0 on either.  (This was my first fix, before I noticed the "$c=0" bit in album.php).

**Comment by sbillard** [comment]
Thanks for this. Your change will be in the next update
