### ISSUE TITLE
PHP warning

### ISSUE THREAD

**Issue by jagerman** [ZenPhoto20/ZenPhoto20#482]
Running under PHP7, when viewing image details of an image via a dynamic album that includes the image, I get the warning:

WARNING: "array_keys() expects parameter 1 to be array, null given" in /srv/imaginary.ca/www/photos/zp-core/class-image.php on line 1021 

Lines 1020-1021 are:

        if ($this->albumnamealbum->isDynamic()) {
            $matches = array_keys($this->albumnamealbum->imageNames, $image);

The fix for the warning is to change the if as follows:

        if ($this->albumnamealbum->isDynamic() && !is_null($this->albumnamealbum->imageNames)) {
            $matches = array_keys($this->albumnamealbum->imageNames, $image);

That said, I don't understand the code well enough to determine whether imageNames being unset is not a deeper issue: my fix above could just be masking some deeper issue.

**Comment by sbillard** [comment]
I suspect that this is a deeper bug. I don't think the imageNames property should be NULL, so probably it has not been setup. Do you have a process that will duplicate this error so I can further investigate?

Be as specific as you can on what steps led up to the error.

**Comment by jagerman** [comment]
Scratch this being a PHP 7 issue; I'm getting the same warning under PHP 5.6.  Apparently I just didn't notice it until now.  I'll attempt to recreate on a fresh install and repost shortly.

**Comment by jagerman** [comment]
# Steps to recreate

From a new installation under PHP 5.6.17-1 on Debian, using current github master checkout.

(Everything unspecified in the below steps is left at default values.)
1. Set the theme to zpskeleton.
2. Create an album named "album 1"
3. Upload an image into album 1.
4. Upload another image into album 1.
5. Add "tag1" tag to both uploaded images.
6. Add a dynamic album "dynamic album", using Search criteria: "tag1"; Search fields: Tags.
7. View the dynamic album on the user side and then click one of the images:

WARNING: "array_keys() expects parameter 1 to be array, null given" in /srv/imaginary.ca/www/zp2test/zp-core/class-image.php on line 1021.


The warning is coming up in the zpskeleton slideshow code (function `printPPSlideShowLink`), in particular from its `getLink()` call on line 189.  (Hence uploading a second image is required, as the slideshow is skipped unless there are at least 2 images in the album).

I tried debugging this a little more before I gave up:

Inside `printPPSlideShowLink`, `$_zp_current_album` is set to the dynamic album as expected, but its `$_zp_current_album->imageNames` member is null.  As a result, when it creates an image object using `$imgobj = newImage($_zp_current_album, $image);` it gets back an object with `->albumnamealbum` set to `$_zp_current_album` (which seems write), but then causes the warning because `$imgobj->albumnamealbum->imageNames` is null where it is used on class-image.php:1021 that I mentioned in the initial report.

**Comment by jagerman** [comment]
Once more piece of the puzzle: if I add a call to getImages(), like this, the warning goes away:

        if ($this->albumnamealbum->isDynamic()) {
            $this->albumnamealbum->getImages();
            $matches = array_keys($this->albumnamealbum->imageNames, $image);

It appears that getImages() was never called on $_zp_current_album, and so imageNames was never set up.

**Comment by sbillard** [comment]
Thanks. That confirms that the imageNames array was not initialized. I think the fix you note above is the correct one.
