### ISSUE TITLE
array_key_exists() expects parameter 2 to be array,..

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/ZenPhoto20#494]
When upgrading from 1.2.6.13 to 1.2.6.17 I got warning about tables (...table appears not have a proper UNIQUE key...). When I ran setup again, I got same warnings + some new (array_key_exists() expects parameter 2 to be array,..).
Now when I run setup again I get both of warnings again.

See attached PDF with all warnings.
[ZenPhoto20 aktualizace.pdf](https://github.com/ZenPhoto20/ZenPhoto20/files/170432/ZenPhoto20.aktualizace.pdf)

In setup log, there are two kinds of notes repeating:
```
{4373:Sat, 12 Mar 2016 13:46:23 GMT}
  POZNÁMKA: "Undefined index: keys" in /net/home/skaut.zamberk.cz/html/galerieonline/zp-core/setup/database.php on line 232
 URI:/galerieonline/zp-core/setup/index.php?checked&update&mod_rewrite=ON
.......
.......
  require_once called from index.php [1670]
{4373:Sat, 12 Mar 2016 13:46:23 GMT}
  UPOZORNENIE: "array_key_exists() expects parameter 2 to be array, null given" in /net/home/skaut.zamberk.cz/html/galerieonline/zp-core/setup/database.php on line 232
 URI:/galerieonline/zp-core/setup/index.php?checked&update&mod_rewrite=ON
.......
.......
  array_key_exists called from require_once (database.php [232])
    from index.php [1670]
```

**Comment by Mates-K1** [comment]
And many of these errors:
```
Query Failed: ALTER TABLE `galerieonline_plugin_storage` ADD INDEX `type` (`type`) COMMENT 'zp20'; 
 Error: Va-Be syntaxe je njak divn bl-Bzko 'COMMENT 'zp20'' na dku 1
Query Failed: ALTER TABLE `galerieonline_plugin_storage` ADD INDEX `aux` (`aux`) COMMENT 'zp20'; 
 Error: Va-Be syntaxe je njak divn bl-Bzko 'COMMENT 'zp20'' na dku 1
Query Failed: ALTER TABLE `galerieonline_search_cache` ADD INDEX `criteria` (`criteria` (255)) COMMENT 'zp20'; 
 Error: Va-Be syntaxe je njak divn bl-Bzko 'COMMENT 'zp20'' na dku 1
Query Failed: ALTER TABLE `galerieonline_tags` ADD UNIQUE `name` (`name`) COMMENT 'zp20'; 
 Error: Va-Be syntaxe je njak divn bl-Bzko 'COMMENT 'zp20'' na dku 1
Setup found the field "custom_data" in the "administrators" table. This field is not in use by ZenPhoto20.
Setup found the field "location" in the "albums" table. This field is not in use by ZenPhoto20.
Setup found the field "codeblock" in the "albums" table. This field is not in use by ZenPhoto20.
Setup found the field "location" in the "images" table. This field is not in use by ZenPhoto20.
```

**Comment by Mates-K1** [comment]
And... I cant saving any changes. For examle when I switch theme color from dark to light and hit Save, there is  text Changes saved, but in options there is dark theme. And in DB in table Options there is about 200 new rows (in this table I have 4497 rows now ???).

It looks like my DB is coming out. :(

**Comment by sbillard** [comment]
Can you please translate the query error message? Do these seem to be happening on each table for add index?

What is the specific order of the error messages? Does the "UPOZORNENIE: "array_key_exists() expects parameter 2 to be array" come first?

Anyway, your line numbers do not match up with mine which is strange. I have that line on line 234.

**Comment by Mates-K1** [comment]
Rough translation: "Your syntax is strangely close 'COMMENT' zp20 '' on the line 1."

First is:
`Undefined index: keys" in /net/home/skaut.zamberk.cz/html/galerieonline/zp-core/setup/database.php on line 232...`
Then:
`"array_key_exists() expects parameter 2 to be array, null given" in /net/home/skaut.zamberk.cz/html/galerieonline/zp-core/setup/database.php on line 232`

**Comment by Mates-K1** [comment]
> Do these seem to be happening on each table for add index?

 Yes.

When I open file database.xxx (date 5.3.2016) propably I have lines similar to you.

```
line 232: 	if (array_key_exists($key, $database[$tablename]['keys'])) {
line 233: 	   if ($index != $database[$tablename]['keys'][$key]) {
line 234:	       $dropString = "ALTER TABLE " . prefix($tablename) . " DROP INDEX `" . $index['Key_name'] . "`;";
```

**Comment by sbillard** [comment]
I have attempted to reproduce this and was not able to. I started with a new install of 1.2.6.0, then upgraded to 1.2.6.13. Then I upgraded to 1.2.6.17 (from the attached zip file.) As I have mentioned, the line numbers on your install do not match up with mine for this version, so maybe there was an issue with the install files.

The sql error appears to be a problem with adding a comment to the index. So these indexes were probably not created. That is probably the problem with not being able to save things. There is no Unique Index, so duplicates are being made.

Are there any indexes in the database after this install?

What happens if you re-install 1.2.6.13? Check the database and see if the indexes have comments attached to them.

One other thing to try is to do the experiment with a clean install of 1.2.6.17. It is possible that your database had duplicate entries in it originally. If so the unique keys could not be created. But that does not explain the specific errors you provide since those are not unique keys.

[setup-1.2.6.17.zip](https://github.com/ZenPhoto20/ZenPhoto20/files/170517/setup-1.2.6.17.zip)

**Comment by sbillard** [comment]
What version of MySql are you running? Maybe the Comment for indices is not supported.

**Comment by Mates-K1** [comment]
MySQLi verze: 5.1.66
PHP verze: 5.3.29

**Comment by sbillard** [comment]
Ok, I think that index comments were added in MySQL version 5.5.0. I am working on a fix.

**Comment by Mates-K1** [comment]
> Are there any indexes in the database after this install?

Sorry, dont understand. My knowledge about DB is very small. Can you explain it a little bit?

> What happens if you re-install 1.2.6.13?

Same errors as in 1.2.6.17. If I install 1.2.6.0, there are only three errors when running setup:
```
Warning: the galerieonline_administrators table appears not to have a proper UNIQUE key....
Warning: the galerieonline_options table appears not to have a proper UNIQUE key.... 
Warning: the galerieonline_tags table appears not to have a proper UNIQUE key....
```

And still cant save setting.

**Comment by Mates-K1** [comment]
Fresh install has following error:

Done with table update with errors. See the setup log for details.
`Fatal error: MySQLi Error: ( SHOW KEYS FROM `gpokus_administrators` ) failed. MySQLi returned the error Table 'skautzamberk.gpokus_administrators' doesnt exist in /net/home/skaut.zamberk.cz/html/gpokus/zp-core/functions-common.php on line 47`

**Comment by sbillard** [comment]
Problem is that the version of MySQL you are using does not support the syntax for creating an index with a comment (The query error you got.) Until your report I did not know that the syntax was introduced into MySQL v 5.5.0. 

Please give this a try. But note your database is probably corrupt, so you need to roll back to how it was before the first update to 1.2.6.17. If you are on 1.2.6.13 you can drop your tables, run setup, then run the backup/restore to re-load the tables. Just be sure to pick a backup from before the first update.

[setup-1.2.6.19.zip](https://github.com/ZenPhoto20/ZenPhoto20/files/170600/setup-1.2.6.19.zip)

**Comment by Mates-K1** [comment]
When installing fresh 1.2.6.19 i get:

Done with table update.
	
Mod_rewrite
X (red cross)

`Fatal error: MySQL Error: ( INSERT INTO `g1_administrators` (`user`, `valid`, `date`) VALUES (''administrators'', ''0'', ''2016-03-12 21:30:27'') ) failed. MySQL returned the error Your syntax is strangely close to 'administrators'', ''0'', ''2016-03-12 21:30:27'')' on the line 1 in /net/home/skaut.zamberk.cz/html/g1/zp-core/functions-common.php on line 47`

**Comment by Mates-K1** [comment]
Hmm...Strange... I am not able to install fresh ZP20 1.2.3.

**Comment by Mates-K1** [comment]
MySQL verze: 5.5.47
PHP verze: 5.3.29

I am able to install:
1.1.4.

I am not able to install:
1.2.6

**Comment by sbillard** [comment]
[setup-1.2.6.20.zip](https://github.com/ZenPhoto20/ZenPhoto20/files/170697/setup-1.2.6.20.zip)


I do not understand the SQL errors you are getting in your last two posts. The syntax shown to be in error is correct. Is the install of 1.2.6.19 still on MySQL 5.1.66? 

Does the debug log have a trace history of the error? I think I know where the statement is executed, but It would be nice to be sure. Any other errors in the logs?

**Comment by sbillard** [comment]
I see in my e-mails two other post that do not show up here:

> Hmm...Strange... I am not able to install fresh ZP20 1.2.3.

and 

> MySQL verze: 5.5.47
PHP verze: 5.3.29

I am able to install:
1.1.4.

I am not able to install:
1.2.6

Are these issues gone?

**Comment by Mates-K1** [comment]
Progress...
when upgrading to 1.2.6.20 i get only 1x:
`Warning: array_key_exists() expects parameter 2 to be array, null given in /net/home/skaut.zamberk.cz/html/galerieonline/zp-core/setup/database.php on line 222`

and 1x 
`Warning: the galerieonline_options table appears not to have a proper UNIQUE key. There are probably duplicate entries in the table which can cause unpredictable behavior. This can normally be corrected by creating a ZenPhoto20 backup, dropping the table, running setup to restore the table, and then restoring from the backup. Note, however, that the duplicate entries will be lost.`

and 1x
```
{8709:Sun, 13 Mar 2016 00:38:03 GMT}
  POZNÁMKA: "Undefined index: keys" in /net/home/skaut.zamberk.cz/html/galerieonline/zp-core/setup/database.php on line 222
 URI:/galerieonline/zp-core/setup/index.php?checked&update&mod_rewrite=ON
 IP `87.249.128.78`
 uživatel:Mates
  require_once called from index.php [1686]
{8709:Sun, 13 Mar 2016 00:38:03 GMT}
  UPOZORNENIE: "array_key_exists() expects parameter 2 to be array, null given" in /net/home/skaut.zamberk.cz/html/galerieonline/zp-core/setup/database.php on line 222
 URI:/galerieonline/zp-core/setup/index.php?checked&update&mod_rewrite=ON
 IP `87.249.128.78`
 uživatel:Mates
  array_key_exists called from require_once (database.php [222])
    from index.php [1686]
```

**Comment by Mates-K1** [comment]
> Are these issues gone?

Yes, sorry for posting.

**Comment by sbillard** [comment]
Not a problem, but best in the future just edit or post that the you revoke these. Less confusion that way.

Your second error is because of some database "corruption". This could have happened almost any time in the past. But likely caused by the 200 new rows you mention above. ZenPhoto20 is not able to create the unique key for this table based on the "valid" and "user" columns. You will have to fix this problem by editing your database. (You can try the suggested solution as well.)

I suspect that the first error (and third, they are the same) is related. I will do some more investigation.

**Comment by sbillard** [comment]
[setup-1.2.6.21.zip](https://github.com/ZenPhoto20/ZenPhoto20/files/170701/setup-1.2.6.21.zip)

You will still get some errors until the duplicates are removed from your administrator table. You will get an SQL error that basically says it cannot create the unique index because there are non-unique entries in the table. Then you will get the warning above.

**Comment by Mates-K1** [comment]
Ok, I wil do it your way.

As I wrote in my third post, I had 4497 lines in Options table, now (after several upgrades) I have 15212 lines.I tried suggested solution, but I have wrong versions of backups. How i find which entries I can delete in _options table? Are those first of repeating entries OK?

After upgrade to 1.2.6.21 I have only `Warning: the galerieonline_options table appears not to have a proper UNIQUE key. error.` :+1:

**Comment by sbillard** [comment]
You can delete all the "new" entries. They will all be at the end of the table when sorted by the ID, presumably starting about 4297.

If that does not clean everything up the only is to keep executing the SQL statement that tries to create the index. You should see it in you setup log with the error that says what was duplicated. Easiest will be to run if from your phpMyAdmin console. If it fails it will give you the duplicate key. Search for instances of that and remove all but one.

You can also delete the option table. That will, of course, set everything back to default.

**Comment by Mates-K1** [comment]
I deleted all entries, but error persist. Only deleting option table helps.
So I am back online. I think it was also a consequence of my previous problems with the database too (if you remember).

Thanks for fast help. :+1:

**Comment by sbillard** [comment]
Sorry you had the problems. Glad things are back working.

Thanks for your help in testing this. You found some issues I could not have known of without your help.
