### ISSUE TITLE
Hiding tabs when user has not permisions to edit albums and pages

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/ZenPhoto20#498]
When user cant edit any albums or pages, he can still acess to these tabs in Admin menu. Of course there is nothing here. But it is a little bit confusing.
![album](https://cloud.githubusercontent.com/assets/7648991/13763590/91ff7864-ea47-11e5-859c-6f7af6fa4602.jpg) ![menu](https://cloud.githubusercontent.com/assets/7648991/13763615/ca4028ea-ea47-11e5-9a0c-7dc1f1649672.jpg)

Is possible to hide these tabs or add them to General rights and have chance to un-checked them?
![general](https://cloud.githubusercontent.com/assets/7648991/13763529/1de87250-ea47-11e5-85e4-4e53fa5a62dc.jpg)

**Comment by sbillard** [comment]
Can you provide some more information? What are the rights for the user for: Alums, News, and Pages?

Does the user have any managed albums (pages, categories) in "manages..." lists? Does the  user have any "favorites" album or has he in the past ever created a page or article?

For me when the user really cannot manage any albums, etc. the tabs do not show up.

**Comment by Mates-K1** [comment]
Rights are set:
![rights1](https://cloud.githubusercontent.com/assets/7648991/13771947/a618768a-ea91-11e5-9c1a-d0c8f21daa34.jpg)
![rights2](https://cloud.githubusercontent.com/assets/7648991/13771950/a7dbae9c-ea91-11e5-818f-964d339fcc2c.jpg)

User has favorites, never created page or article.
When I remove all favorites, tabs are still here.

**Comment by sbillard** [comment]
Thanks, I see the situation. I believe we can handle this and not display the tabs. May take some time, though. Complex area of code.

**Comment by sbillard** [comment]
You will have to change the managed objects, save them, then change them back because one of the problems is the right to view the tabs (a hidden right) was set if there were managed objects even if none could be edited. (There was also a bug in the albums handling of logon that forced the albums tab.)
