### ISSUE TITLE
Cant add tags on single image page

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/ZenPhoto20#502]
1.2.6.24
Cant add tags on single image page. There are not fields for this.
User log as admin.
![untitled 1](https://cloud.githubusercontent.com/assets/7648991/14062667/c966208c-f3a7-11e5-87ad-79250fba759a.jpg)

Tab Tags is ok - I can add tags etc.

**Comment by sbillard** [comment]
Most likely you do not have the "optionalObjects" plugin enabled. That plugin adds "fields" to objects, including the Tags field for images and albums.

**Comment by Mates-K1** [comment]
Thank you very much.

I am sorry - still tunning setting after deleting options table in DB.
