### ISSUE TITLE
Plugin info - warnings and fatal errors

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/ZenPhoto20#506]
When I click on info icon in list of plugins I get
```
Warning: require_once(/net/home/skaut.zamberk.cz/html/galerieonline/zp-core/setup/setup-functions.php) [function.require-once]: failed to open stream: No such file or directory in /net/home/skaut.zamberk.cz/html/galerieonline/zp-core/pluginDoc.php on line 38

Fatal error: require_once() [function.require]: Failed opening required '/net/home/skaut.zamberk.cz/html/galerieonline/zp-core/setup/setup-functions.php' (include_path='.:/usr/lib/php') in /net/home/skaut.zamberk.cz/html/galerieonline/zp-core/pluginDoc.php on line 38
```

and in debug log:

```
  WARNING: "require_once(/net/home/skaut.zamberk.cz/html/galerieonline/zp-core/setup/setup-functions.php) [<a href='function.require-once'>function.require-once</a>]: failed to open stream: No such file or directory" in /net/home/skaut.zamberk.cz/html/galerieonline/zp-core/pluginDoc.php on line 38
 URI:/galerieonline/zp-core/pluginDoc.php?extension=accessThreshold

 user:Mates
  require_once called from pluginDoc.php [38]
```

This applies to all plugins.
1.2.6.27

**Comment by Mates-K1** [comment]
When upgrading from 27 to 28, cant run setup and get
`Fatal error: Cannot redeclare getDBTables() (previously declared in /net/home/skaut.zamberk.cz/html/galerieonline/zp-core/functions-common.php:32) in /net/home/skaut.zamberk.cz/html/galerieonline/zp-core/setup/setup-functions.php on line 560`

**Comment by sbillard** [comment]
That function was removed from setup-functions by commit 63961fda84cb184ebd487965c775afdc1cca16b2 so be sure that you are not somehow running old versions of the setup scripts.

I suggest you install from: https://github.com/ZenPhoto20/ZenPhoto20/releases/tag/ZenPhoto20-1.2.6.28

**Comment by Mates-K1** [comment]
Thanks, re-upload helps. :)
