### ISSUE TITLE
Issue with getFullImage

### ISSUE THREAD

**Issue by Bruno21** [ZenPhoto20/ZenPhoto20#512]
Hello,

I'm using:
$randomImage = getRandomImages();
echo $randomImage->getFullImage()

but it return nothing.

**Comment by sbillard** [comment]
The getFullImage() method will normally return string which is a WEP path to the image. But if your albums are designated "external" such a path is not possible so it returns FALSE.

Also possible is some kind of error. Have you checked all your logs?

Does the Effervescence+ theme show its random image on the index page? That uses the random image, but not the full image.

**Comment by sbillard** [comment]
I looked a bit further. The getFullImage() method is private to the image object so you should have got an error trying to use it. The method you want is getFullImageURL().

**Comment by Bruno21** [comment]
> Le 6 mai 2016 à 15:57, Stephen <notifications@github.com <mailto:notifications@github.com>> a écrit :
> 
> The getFullImage() method will normally return string which is a WEP path to the image. But if your albums are designated "external" such a path is not possible so it returns FALSE.
> 
> Also possible is some kind of error. Have you checked all your logs?
> 

Don't see any error in logs.

> Does the Effervescence+ theme show its random image on the index page? That uses the random image, but not the full image.
> 

Yes, I see the random image.

**Comment by Bruno21** [comment]
> Le 6 mai 2016 à 17:37, Stephen <notifications@github.com> a écrit :
> 
> I looked a bit further. The getFullImage() method is private to the image object so you should have got an error trying to use it. The method you want is getFullImageURL().
> 
> 


getFullImageURL() work fine !

With "official" zenphoto, getFullImage() and getFullImageURL() returns the same string.


Thanks.

**Comment by sbillard** [comment]
The base getFullImage() method does not apply filters to the URL, so plugins like TinyURL will not work if you use it. It is "deprecated" in the sense it was replaced with the getFullImageURL() method. With ZenPhoto20 the function is private to the image object so you will get an error using it. (Probably the error is in your server logs. These errors generally stop script execution, so ZenPhoto20 cannot trap and record them.)

There is a plugin named "legacyConverter" that you can use to clean up issues like this in your theme. It will find and replace flawed and deprecated Zenphoto function use with the proper function/method.
