### ISSUE TITLE
Back button link broken

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/ZenPhoto20#522]
ZenPhoto20 version 1.3.2.3
PHP version: 5.3.29
MySQLi version: 5.1.66
theme zpArdoise (version 1.4.6, 31/03/2014)
more then 10 images in album

1. Frontend:
view image,
click Edit image in right menu.

2. Backend
click image thumb to crop,
click Back button.

Displayed page is last page with images (depends on images per page setting), not single images page or page with another images includes edited image.

Example:
10 images per page, 156 images in album
edit thumb for image nr. 057 = displayed page after back starts with image 151

Editing via crop button (not image thumb) is OK.
Editing via only backend is OK.

**Comment by sbillard** [comment]
Thanks for reporting this.
