### ISSUE TITLE
Options to disabling challenge phrases

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/ZenPhoto20#525]
Hello,
please add option to disable challenge phrases - from user page and from page for reseting password.

Thanks.

**Comment by Mates-K1** [comment]
Thanks for this option.

But now when challenge phrases are disable there is no link to reset password via mail.

With phrases:
![untitled 2](https://cloud.githubusercontent.com/assets/7648991/18044293/76947d5e-6dcd-11e6-81c2-b499d2e699e5.jpg)

Without phrases:
![untitled 1](https://cloud.githubusercontent.com/assets/7648991/18044302/82646950-6dcd-11e6-8d67-331d3bdc8f4d.jpg)

**Comment by sbillard** [comment]
You have to enter a user name before any of the reset things can work--otherwise don't know whom to send the e-mail.

**Comment by Mates-K1** [comment]
Sorry, I am still not able to reset password when challenge phrases are off.
I lost my passw, so what now?
In zpArdroise theme I click Login (in bottom), I see windows from my last post (without phrases).

I write my name to User (dont write password), and then click Login - window is updated and: "There was an error logging in. Check your username and password and try again.". It is ok.

But write user name and click the Reset button does nothing.

Where is my mistake?

**Comment by sbillard** [comment]
Reset just resets the form. After you attempt to login with the wrong password the link at the bottom of the form for requesting a reset by e-mail should appear. It probably should be there always. I have another change that will cause this, but not allow the password reset request unless there is a user name entered. I will get that released shortly so you can try it.

**Comment by sbillard** [comment]
There is a test version of this change at https://github.com/sbillard/ZenPhoto20-DEV 

Please see how it works for you.

**Comment by Mates-K1** [comment]
Nothing has changed. :(

**Comment by sbillard** [comment]
Please visit http://testalbum.sbillard.org/zp-core/admin.php and see if you can try an e-mail reset. It seems to work for me. Of course you have no user id there, so only the request will work. Also for anti SPAM reasons I have not configured an e-mail handler, so you will get a message to that effect.

**Comment by Mates-K1** [comment]
Yes, it works. I found it works in my gallery too. Problem is when I try reset password from theme (without entrering direct address). My pictures are from popup windows - and when challenges phrases are off, there is not link to reset.

**Comment by sbillard** [comment]
Please try the DEV build again.

**Comment by Mates-K1** [comment]
Works perfectly. Thank you very much. 👍
