### ISSUE TITLE
Typing error and note to fullscren in TinyMCE

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/ZenPhoto20#534]
I think there is a small typing error in Usage tips (main Page and Article).

> Click the exp**A**nd icon of editor’s control bar, near ZP icon

And there is not ZP icon in TinyMCE, there is only button called "Fullscreen". But this button is not in all version, it is not in "light" version of TinyMCE. There is shortcut CTRL+SHIFT+F which works for all.

I think that the sentence could be:
_Click the fullscreen icon of editor's control bar or use CTRL+SHIFT+F._

**Comment by sbillard** [comment]
Can you provide more details? Where is this text found?

**Comment by Mates-K1** [comment]
![untitled 1](https://cloud.githubusercontent.com/assets/7648991/18560604/a3d86002-7b7c-11e6-9e6c-18695ad6b515.jpg)

**Comment by sbillard** [comment]
Thanks. Fix is on the way.
