### ISSUE TITLE
Use of undefined constant ZENPHOTO_RELEASE

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/ZenPhoto20#536]
When one of mine user with no admin rights launched setup:

```
{32075:Thu, 15 Sep 2016 19:54:04 GMT} ZenPhoto20 v1.3.3.3
  NOTICE: "Use of undefined constant ZENPHOTO_RELEASE - assumed 'ZENPHOTO_RELEASE'" in /net/home/skaut.zamberk.cz/html/galerieonline/zp-core/zp-extensions/security-logger.php on line 132
 URI:/galerieonline/zp-core/setup/index.php?autorun=gallery

  security_logger::Logger called from security_logger::log_setup (security-logger.php [412])
    from call_user_func_array (unknown)
      from zp_apply_filter (functions-filter.php [149])
        from index.php [409]
```

After that I launched setup with admin rights there wasnt another error.

**Comment by sbillard** [comment]
This error is an indication that the files in the zp-core/setup/ folder are from an older build. If you can re-produce the problem again please remove all the files in the setup folder and reload from the 1.3.3.3 release build. If you get this error from any other script file you should be sure that all the files are from the 1.3.3.3 release. 

This is one of the possible issues from using support builds that do not have an install program. It is possible for various reasons that not all the files get updated properly. If things seem stable I will make a 1.3.4 release soon to combat this.

**Comment by Mates-K1** [comment]
After deleting files and reinstaling there is no new error.

**Comment by sbillard** [comment]
Thanks for confirming.
