### ISSUE TITLE
GPS to video

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/ZenPhoto20#545]
It would be nice to have GPS coordinates in video via video thumbs. Now if video thumb has GPS coordinates, it does not show in a map.

**Comment by sbillard** [comment]
Seems like a reasonable request, but not so simple as it would appear. I will ponder on this and see if I can find a way to make it work.

**Comment by sbillard** [comment]
Ok, I have done some experimenting and probably need to have your example video and video thumb files. I made an FLV video with a thumbnail and added gps data to the thumbnail image. This does show for me on the Google Map.

You could also try refreshing the video's metadata as well. Also look to see if there the database entry for the video has data for EXIFGPSLatitude and EXIFGPSLongitude and for GPSLatitude and GPSLongitude.

**Comment by Mates-K1** [comment]
ZP20 1.3.4.0
If I refresh video metadata there are GPS cords and I am able to show video on the Google Map - in single img page and album page too (hmmm - standard function fo ZP20 yet - I didnt know about it). It is almost ok - but there is no overlay GPS icon on video thumb.

For sample video and thumb please check your email.

**Comment by sbillard** [comment]
Thanks for the example video.

I guess I misunderstood the issue. I have fixed the thumbnail flags in my development build https://github.com/sbillard/ZenPhoto20-DEV

Please give it a try and see if there are any other issues.

**Comment by Mates-K1** [comment]
I apologize for the misunderstanding.
Now it works the way I imagined. Thanks.
