### ISSUE TITLE
Some bugs from my log

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/ZenPhoto20#548]
```
{36485:Sun, 04 Dec 2016 21:54:53 GMT} ZenPhoto20 v1.3.4.2
  POZNÁMKA: "Undefined index: sortby" in /net/home/skaut.zamberk.cz/html/galerieonline/zp-core/admin-functions.php on line 2467
 URI:/galerieonline/zp-core/admin-edit.php?page=edit&action=save&album=stredisko/vypravy/2016_12_02_vyprava_s_KD/zaza
 IP `87.249.128.78`
 uživatel:Mates
  processAlbumEdit called from admin-edit.php [335]
{36485:Sun, 04 Dec 2016 21:54:53 GMT}
  POZNÁMKA: "Undefined index: subalbumsortby" in /net/home/skaut.zamberk.cz/html/galerieonline/zp-core/admin-functions.php on line 2482
 URI:/galerieonline/zp-core/admin-edit.php?page=edit&action=save&album=stredisko/vypravy/2016_12_02_vyprava_s_KD/zaza
 IP `87.249.128.78`
 uživatel:Mates
  processAlbumEdit called from admin-edit.php [335]
{36485:Sun, 04 Dec 2016 21:54:53 GMT}
  POZNÁMKA: "Undefined index: publishdate-" in /net/home/skaut.zamberk.cz/html/galerieonline/zp-core/admin-functions.php on line 2499
 URI:/galerieonline/zp-core/admin-edit.php?page=edit&action=save&album=stredisko/vypravy/2016_12_02_vyprava_s_KD/zaza
 IP `87.249.128.78`
 uživatel:Mates
  processAlbumEdit called from admin-edit.php [335]
{36485:Sun, 04 Dec 2016 21:54:53 GMT}
  POZNÁMKA: "Undefined index: expirationdate-" in /net/home/skaut.zamberk.cz/html/galerieonline/zp-core/admin-functions.php on line 2500
 URI:/galerieonline/zp-core/admin-edit.php?page=edit&action=save&album=stredisko/vypravy/2016_12_02_vyprava_s_KD/zaza
 IP `87.249.128.78`
 uživatel:Mates
  processAlbumEdit called from admin-edit.php [335]
```

**Comment by sbillard** [comment]
Is this something you can reproduce? The error messages make no sense to me. If you can reproduce it, please add a line to the beginning of processAlbumEdit:
`2447: debugLogVar('trap missing POST items', $_POST);`

**Comment by Mates-K1** [comment]
I think I cant reproduce it. I dont know what is happend. I added album and subalbums as many times (via FTP create folders and via FTP upload images).  But now one of subalbums was uncommonly unpublish and comments wasnt allowed after creating.

**Comment by sbillard** [comment]
Is the album still unpublished/comments not allowed? The errors shown in your log really must be from some kind of data transmission problem with the POST of the album save. Those fields are not conditional, they should therefore always be present.

**Comment by Mates-K1** [comment]
No, when I found it, I published them and allowed comments. Now all works normally.

**Comment by sbillard** [comment]
This error would have happened when you "saved" an album. Is "stredisko/vypravy/2016_12_02_vyprava_s_KD/zaza" the album that was unpublished? Do you remember any problems when saving it?

**Comment by Mates-K1** [comment]
Yes, I think "zaza" album was unpublish. There was no error.

Is possible to have those errors when I open one browser tab with album "2016_12_02_vyprava_s_KD" and another browser tab with album "zaza" and make some saved changes in first tab? I usually use more tabs when editing albums and subalbums.

**Comment by sbillard** [comment]
I do not think that could cause the problem. Sometimes that can cause "XSRF" errors, but the POSTs should still be intact. 

I guess all we can do for now is see if the error happens again. If you keep your log emptied then as soon as something is put into it you will see the tab being yellow. Maybe then we can get closer to when the problem happens.

**Comment by Mates-K1** [comment]
Ok, I will do it. 
Thanks for replies.

**Comment by sbillard** [comment]
I guess this can be closed now. If you get a recurrence with more data, please submit a new ticket.
