### ISSUE TITLE
Challenge phrases in user profile - hide them when they are disable

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/ZenPhoto20#550]
If it is posible I would like to hide challenge phrases from user profile when they are disable.
There are two rows to fill in belong to challenge phrases in user profile.

**Comment by sbillard** [comment]
Can you give me some more information on what you are doing and what you wish to accomplish? In particular, how is this disable established? It is certainly possible to hide the fields, I just want to understand the whole situation.

**Comment by Mates-K1** [comment]
When I disable challenge phrases (Options - Security - uncheck Enable Challenge phrase), they are still available in user profile.
![untitled 1](https://cloud.githubusercontent.com/assets/7648991/21422335/7fe82fa8-c837-11e6-9084-a6e356ce6df6.jpg)

I would like to hide them from user profile when they are disable because they are always visible there.

**Comment by sbillard** [comment]
Ok, I understand. The fields will not show unless the challenge phrase option is enabled.

**Comment by Mates-K1** [comment]
Thank you for fast support and solution. 👍
