### ISSUE TITLE
DEV release notes.htm typo

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/ZenPhoto20#558]
There is a small typo in "themeSwircher" (line 96) in DEV.

**Comment by sbillard** [comment]
Thanks. 

I hope you are not using this development build on a production site. There are some substantial changes in it that I am still testing. Mostly to do with options. Anyway, any site that has run this build recently should be considered suspect.

**Comment by Mates-K1** [comment]
No, I am not using DEV now (but I used to...). I read release notes, so I know about changes you are working on. I use DEV only when we solve some of my problems.
I´ll wait for stable 1.4 👍
