### ISSUE TITLE
email notification

### ISSUE THREAD

**Issue by zorodimanche** [ZenPhoto20/ZenPhoto20#560]
Send an email when someone replies to a comment.

**Comment by sbillard** [comment]
There is not the concept of replying to specific comments. Comments are simply posts and there is no way of relating one comment to another.

So, exactly what do you want to accomplish? 

A. Be able to monitor all comments on a particular object? That can be done by using RSS and subscribing to the feed for the object.

B. As administrator to know when a comment has been posted? Again, the RSS feed is the most economical way of achieving this.

C. Some other use? Please explain.

**Comment by zorodimanche** [comment]
Is not the notification for the administrator but for a registered user.
For example Mr A comments on a picture and Mr B replies to the comment of Mr A. Then Mr A receives an email telling him that Mr B answered his comment.

**Comment by sbillard** [comment]
It is simply not the case that Mr B can respond to the comment of Mr A. There is no concept of a "response" to another commenter. Comments are all made about the object (image, album, etc.) for which the comment form is displayed, not about a comment in the thread of comments. The only option is for Mr A to subscribe to the RSS for the object comments. He will then see all comments posted about the object.

**Comment by zorodimanche** [comment]
Is that a notification system is provided please.

**Comment by sbillard** [comment]
This is not really possible. As mentioned, there is no means to understand that a particular comment has anything at all to do with another comment. Comments are made about the objects and only about the objects. There exists a notification system for comments about objects--that is the RSS feed. If you subscribe to the RSS feed for comments on an object you will see all comments posted on the object. That is the purpose of RSS. 

There is really no need to invent a different means to accomplish the same thing.

Comments are not a bulletin board system. ZenPhoto20 does not provide BBS feature, that is not its target application.
