### ISSUE TITLE
flags in dropdown

### ISSUE THREAD

**Issue by zorodimanche** [ZenPhoto20/ZenPhoto20#561]
It would be interesting to display the flags in dropdown shapes and name them all unnecessarily to save space.
<img width="200" alt="language-02_1x" src="https://cloud.githubusercontent.com/assets/25553946/23514114/93b611ba-ff66-11e6-9580-5c123b02d735.png">

**Comment by sbillard** [comment]
I will look into this. Seems like a good idea, as was your idea to not use the UL for the language editing.

I did think the flags might take too much space, especially when a lot of languages were enabled.

**Comment by zorodimanche** [comment]
Tanks You @sbillard

**Comment by zorodimanche** [comment]
Hello @sbillard I hope that once you read this post you are not going to energize because maybe I was not precise. In fact, when I said menu rolling it was for the front end and not for the back end. So please restore the old files.

I'm really sorry

**Comment by sbillard** [comment]
Well, this actually solves an issue with the previous implementation--that too many enabled languages spread the flags beyond reasonable space  usage. 

Images cannot normally be part of <select> options. This is an HTML restriction. It takes special javascript to enable this. In light of minimizing the overhead required of themes we will not make this feature available on the front end. But we can provide the infrastructure to make it possible for a theme to enable it the author chooses to include the relevant javascript support. In this case it is msDropdown, a JQuery dependent script system.
