### ISSUE TITLE
Use a vertical menu in backend

### ISSUE THREAD

**Issue by zorodimanche** [ZenPhoto20/ZenPhoto20#563]
The vertical menu can make an interesting change, a modern breath and a fun look. A vertical menu is excellent tool to bring to a site an original and sophisticated touch. This type of menu offers a very interesting layout freedom since it is located to the left of the site and allows the leisure to play with the space of the screen as it seems.

In addition all cms uses a vertical menu: wordpress, drupal, piwigo ...
![screenshot1](https://cloud.githubusercontent.com/assets/25553946/23545536/10895c66-fffc-11e6-9cbb-7dc6ee7d2873.png)

**Comment by sbillard** [comment]
While this is an interesting presentation there is no plans for such a total revamp of the back-end. However it this is an undertaking you would be interesting in implementing we would welcome the changes.

**Comment by zorodimanche** [comment]
Not sorry I do not have a company but I'm interested and I am passionate about new tehnologies.

**Comment by sbillard** [comment]
I am sure you understand that we have limited development resources, so have to apply them to the features that most interest our users. I suggest you engage in the forum to see if this idea has any traction. 

For now we will apply our resources to things which add features, not to revisiting this interface.

**Comment by sbillard** [comment]
Now that the 1.4 release is complete we have time to investigate this suggestion. It does seem that judicious use of a vertical menu with pop-out sub menus would be a better use of the browser page realestate.
