### ISSUE TITLE
 custumized checkboxes and radio buttons

### ISSUE THREAD

**Issue by zorodimanche** [ZenPhoto20/ZenPhoto20#566]
In order to give a modern look to the interface and give a good image of the administration interface it would be interesting to apply a css style to inputs, checkbox as in this example: http://icheck.fronteed.com/

**Comment by sbillard** [comment]
This particular implementation appears to add considerable overhead including fairly extensive source changes for no practical benefit. We would consider a css only approach if you can identify an appropriate one.

**Comment by zorodimanche** [comment]
Okay I just made the suggestion for better visual rendering.

**Comment by sbillard** [comment]
No problem. But please keep in mind that the admin pages are a tool for managing your site, not the front-facing part of it. Cosmetic change suggestions are welcome, but they need to meet cost/benefit constraints. So if there is a simple implementation that does not require extensive code modification (there are about 230 radio buttons and checkboxes) then, so long as it does not impact the real estate of the layout, they can be implemented.

A good example of what to look for is the implementation of the back button (although this is a functional change, so would be considered anyway.) That change adds a bit of JavaScript to the page bottom, an <a> tag to the top of the body and some CSS. A small change for a great benefit. 

Of course you should not expect me to do the research for cosmetic changes. My time is better spent elsewhere.
