### ISSUE TITLE
Replace images with css

### ISSUE THREAD

**Issue by zorodimanche** [ZenPhoto20/ZenPhoto20#567]
In the administration panel there are images in background of gray color is useless and can replace it by css3.
background : url(images/admin-headerback.jpg) : delete

Moreover it will slightly accelerate the display

**Comment by sbillard** [comment]
This can be done, but the visual effect of the background image cannot be replicated in CSS. I suggest you post on the Google Group (https://groups.google.com/forum/#!forum/zenphoto20) to see if there is support for this change.

**Comment by sbillard** [comment]
In my opinion, removing the background image makes the page look flat and uninspiring. So unless there is a consensus for change it shall be left the way it is.
