### ISSUE TITLE
Not recognizing ITPC Headline as the photo title

### ISSUE THREAD

**Issue by nerdykit** [ZenPhoto20/ZenPhoto20#568]
Just uploaded a group of photos with the same formatting as others for the metadata and for this group, ZP20 didn't pick up the IPTC headline and use it as the photo title.  Is this a setting that somehow has changed?  Same for the IPTC descriptions.  These are also missing.  Yesterday it worked, today it doesn't.

Thanks

KD

**Comment by sbillard** [comment]
Some more information please. Did you upgrade/change your install between when it worked and not? If so, from what version to what version?

What is the value state of the radio buttons for "Image Headline {IPTC}" on the image options tab?

The processing has not changed so far as I know. The priority for the title is:

IPTCObjectName

IPTCImageHeadline

EXIFDescription
			
The first field found should get stored in the title.

Also check the actual metadata field in the database to see if it was correctly captured.

**Comment by nerdykit** [comment]
Thanks.  I'd forgotten that I DID change the IPTCImageHeadline setting thinking that it was changing what appears in the information popup window only and not realising that it also affects the title etc.  So this problem is closed.... operator error.

**Comment by sbillard** [comment]
Just to be sure. If you set it to "hide" it will still be used for the title. If you set it to "disable" then it will be totally ignored. So if you set it to "disable" then, yes, operator error. But if you set it to "hide" there may still be an issue.

**Comment by nerdykit** [comment]
> On Mar 6, 2017, at 7:15 PM, Stephen <notifications@github.com> wrote:
> 
> Just to be sure. If you set it to "hide" it will still be used for the title. If you set it to "disable" then it will be totally ignored. So if you set it to "disable" then, yes, operator error. But if you set it to "hide" there may still be an issue.
> 
> 

No issue, works exactly as you say it should.  I just didn’t know this stuff.  Thanks.

KD
