### ISSUE TITLE
Improve the progress of image caching

### ISSUE THREAD

**Issue by zorodimanche** [ZenPhoto20/ZenPhoto20#578]
Improve the progress of image caching because when caching the script loads thumbnails which is unnecessary, it would be interesting to replace that with a progress bar.
As you can see below it is useless
![cache](https://cloud.githubusercontent.com/assets/25553946/24464724/034f492a-14ab-11e7-9608-9d524279c72f.png)

**Comment by sbillard** [comment]
These images are in effect the progress bar. They are not thumbnails, the browser is simply told to render them in a small container.

There is really no inefficiency in loading these thumbnails. The generation must take place, so the only thing you might be able to save is the transmission of the images from the server to the browser. If you are not interested in knowing when the caching process is completed you can simply leave the page. Of course if there is a failure to render one of the images you will not be aware of it if you don't wait for the page to complete.

**Comment by zorodimanche** [comment]
Ok I understand
