### ISSUE TITLE
Change photo vote

### ISSUE THREAD

**Issue by zorodimanche** [ZenPhoto20/ZenPhoto20#581]
Replace the stars with buttons I like or I do not like like on youtube facebook or in piwigo it's more consistent because the stars are inaccurate.

**Comment by sbillard** [comment]
I do not see how this is an improvement. "Like/do not like" is binary. The stars give you a multi point grading. I also do not understand why you think they are "inaccurate." Do you mean to say you cannot assign a degree of preference? Most people are quite competent of assigning a value of 1-5 (for instance) to something--this happens all the time in surveys.

Anyway seems you want a plugin to do something different from what the "rating" plugin was designed to do. ("Rating" after all implies more than a binary choice.)  if you do want just a binary choice you can change the plugin's number of stars option to "1." If you wish to change the "star" icon you can make a copy of the plugin into the user plugin folder and change the css to use whatever icon you wish.

**Comment by zorodimanche** [comment]
I am not open this ticket for my personal interest but for the general interest. Can you read this discussion sbillard to have another vision : http://ux.stackexchange.com/questions/4200/rate-vs-like-dislike

**Comment by sbillard** [comment]
Perhaps you should limit your suggestions to things that are an actual benefit to you. No other user has thought that the ratings plugin did not do what they desired for their site.

As to the conversation you cite--the conclusion is ambiguous.
