### ISSUE TITLE
Add a plugin to log in and to register with twitter

### ISSUE THREAD

**Issue by zorodimanche** [ZenPhoto20/ZenPhoto20#582]
Facilitate registration and login of users using their Twitter account : https://dev.twitter.com/web/sign-in

**Comment by Mates-K1** [comment]
I am not fan of any social login. :/ 
If it will be added, I am sure I will not allow it for my users.

I think FB login would be more usefull because it is more popular then TW..

**Comment by sbillard** [comment]
If this is added it would be an addition to the federated logon plugin which already handles this kind of thing for google accounts. Perhaps Facebook would also be a useful addition. It all will depend on how well twitter (and Facebook) folow the OAuth standards. Twitter, at least, has been known in the past to want to go its own way.

**Comment by sbillard** [comment]
The Twitter documentation is, to say the least, lacking in specificity. However, they claim an OAuth authentication path, so it should be possible to make this work. If this is something that is important to you then you can do the research and make a working federated logon handler for Twitter.

Start by reading the document block of the federated logon plugin. (This is also displayed by the info icon on the plugins list.)

Then retrieve the DevTools20 repository and use the "yahoo-demo" handler as a template. Substitute the Twitter specifics for the Yahoo specifics and give it a test run. When everything is working, submit your handler code for consideration for inclusion in the ZenPhoto20 release stream. Alternatively you could self publish this code and announce it on our google group forum.
