### ISSUE TITLE
Orphan tags

### ISSUE THREAD

**Issue by zorodimanche** [ZenPhoto20/ZenPhoto20#583]
Add a function that detects orphaned tags ie that are not attached to any image.

**Comment by sbillard** [comment]
We probably will not do this for two reasons.

First, it is quite reasonable to have tags that are not attached to any object but just waiting to be used. For example your "categories" might be presently empty but that does not mean they should not exist.

Second, on the tags page you can order the tags by "most used" which will put all the ones with zero use at the bottom of the list, easy to find, check, and delete.

**Comment by zorodimanche** [comment]
Maybe not delete them but detect all tags that are not linked to an image so the webmaster will assign the orphan tag to an image.

**Comment by sbillard** [comment]
Please read responses to your submissions and understand the software. You are wasting my time with things that are not issues! In this case look at the TABS page you can see exactly how many uses there are for a tag which naturally includes zero.
