### ISSUE TITLE
Save space in the front end

### ISSUE THREAD

**Issue by zorodimanche** [ZenPhoto20/ZenPhoto20#584]
Save space in the front end through a dropdown menu of enabled languages. Because when all the languages ​​are activated all the flags are displayed and it is useless for the surfer.
You can see attached as it is more practical and aesthetic:

![universe-whmcs-template-language-select-w-flags](https://cloud.githubusercontent.com/assets/25553946/24837601/054807b8-1d38-11e7-8cf8-bbce99098c82.jpg)

**Comment by sbillard** [comment]
If you wish to save space use the selector type language selection rather than the flags. This is an option of the plugin and it is there for this very reason!

As mentioned before, selectors (such as you show) do not natively support image content.

**Comment by zorodimanche** [comment]
Since the selectors do not natively support the image content one could remove the images like this:
![menu langue](https://cloud.githubusercontent.com/assets/25553946/24852918/80fcd55e-1dd9-11e7-9e21-fabcabaa57a8.jpg)

**Comment by sbillard** [comment]
Somehow I get the feeling that you do not really use the software nor read the responses to these posts. This feature ALREADY EXISTS in the software. Please refrain from wasting my time in the future. Become familiar with the things the software already can do before you make a request.
