### ISSUE TITLE
Backup tag link/adress

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/ZenPhoto20#587]
1.4.0.7
From Menu - Overview - Backup - there is link to zp-core/utilities/backup_restore.php?tab=bacakup.

Is "bacakup" really ok?

**Comment by sbillard** [comment]
Fumble fingers, thanks.

**Comment by Mates-K1** [comment]
Fumble fingers that make this great gallery. :)

You are welcome.

**Comment by sbillard** [comment]
Do you plan to update the Check language files any time soon? I think the 1.4.1 release is close, but no problem waiting for an update.

**Comment by Mates-K1** [comment]
I work on update. I will send you update by mail in the evening (in next 8 hours).
