### ISSUE TITLE
Image rating - size of font and stars

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/ZenPhoto20#590]
After update I think font size is too large. And stars are big too. Compare with Add to favourites (Přidat k oblíbeným).

zp-ardoise
![ardoise](https://cloud.githubusercontent.com/assets/7648991/25066399/a01073e8-2224-11e7-9bbc-197263ef8bdb.jpg)

basic
![basic](https://cloud.githubusercontent.com/assets/7648991/25066401/a1d31424-2224-11e7-8b44-eca835fc0f09.jpg)

**Comment by sbillard** [comment]
Size of the stars is now an option of the plugin. Options are "large", "medium", and "small". Small is the original size.

**Comment by Mates-K1** [comment]
Oh yes, I change it back to small and now all is fine. Sorry - my fault.

For me we can close this.
