### ISSUE TITLE
Footer in short page in back-end

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/ZenPhoto20#591]
Normal long page - text in footer is in lighter area, there is no darker area
![normal](https://cloud.githubusercontent.com/assets/7648991/25066536/91a67b78-2228-11e7-8dcd-1fdd51ed6766.jpg)

Short page - text in footer is in darker area, there is no light margin
![short_page](https://cloud.githubusercontent.com/assets/7648991/25066539/a1b6dfbc-2228-11e7-8a8c-ac1687cd642d.jpg)

I wish whitesmoke color on short pages in footer too.

**Comment by sbillard** [comment]
This is probably a page that did not get updated. Can you tell me which page it is so I can check it out?

**Comment by Mates-K1** [comment]
Logs, development, Rewrite Tokens, Legacy converter, third party plugin (there is another bug - I will post), E-mail plugins, Categories.

**Comment by sbillard** [comment]
Thanks, got it.
