### ISSUE TITLE
Most of stat graphic bars are not showing

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/ZenPhoto20#594]
For example:
![cd47b276-4edc-4297-911b-7226c99ef456](https://cloud.githubusercontent.com/assets/7648991/25069556/d9f8e0da-2284-11e7-9c89-d818ef18063e.jpg)

**Comment by sbillard** [comment]
I am not seeing this at all. Could you look at the HTML for bars 7 and 8? Maybe a localization issue with the numbers. The bars should look something like:
`<td class="statistic_title"  style='background-color: #f4f4f4'>
					<strong>news_en</strong> 				</td>
				<td class="statistic_graphwrap"  style='background-color: #f4f4f4'>
					<div class="statistic_bargraph" style="width: 88.56%"></div>
					<div class="statistic_value">492</div>
				</td>
				<td class="statistic_link"  style='background-color: #f4f4f4'>
					<a href='/cache_html/rss/news_en.xml' title=''>View</a></td>			</tr>
						<tr class="statistic_wrapper">
				<td class="statistic_counter" >
					2				</td>
				<td class="statistic_title" >
					<strong>news</strong> 				</td>
				<td class="statistic_graphwrap" >
					<div class="statistic_bargraph" style="width: 6.84%"></div>
					<div class="statistic_value">38</div>
				</td>
`
Where the size of the bar is a percentage of the area to show.

**Comment by sbillard** [comment]
Also maybe try changing line 439 of utilities/gallery_statistics.php from

`<div class="statistic_bargraph" style="width: <?php echo round($barsize, 3); ?>%"></div>`

to 

`<div class="statistic_bargraph" style="width: <?php echo ceil($barsize); ?>%"></div>`

**Comment by Mates-K1** [comment]
There is "," in percentage value, in your post there is ".". Integers (I dont know how it is in english) are OK.

**Comment by sbillard** [comment]
That is what I thought might be the case. The code change I posted 
should fix that. (Hope there are not more of those issues hiding 
somewhere.)

-Stephen

**Comment by Mates-K1** [comment]
Fix works for me. Thanks for fast respond.

If there are bugs, I will find them for you, says Martin, The Bug Hunter. 🔨 :-)
