### ISSUE TITLE
Spontaneous theme switching

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/ZenPhoto20#600]
1.4.0.14
Gallery theme: zpArdoise
plugin mobilTheme is ON with:
- phone mode: zpBootstrap
- tablet theme: gallery theme

Log in from mobile (Lumia 640 XL with Windows Mobile 10), see my gallery with zpBootstrap theme - that is OK.
Log in (or only refresh gallery page) in PC and there is zpBootstrap theme as default for gallery instead of zpArdoise.

**Comment by sbillard** [comment]
I tried to reproduce this on my test system. It is not quite the same situation since I cannot connect from my phone and tablet. But I can simulate with the attached debug version of the mobileTheme plugin.

So I took three different browsers, Chrome, Firefox, and Microsoft Edge. I added ?mobile=phone to one, ?mobile=tabled to another and left the third with the standard URL. With this testing the proper theme showed up in each case.

I did use "basic" for the desktop theme so it was easy to tell the difference.

Anyway the attached version of the theme will record its decisions in the debug log. Maybe this will tell us something of what is happening.


[mobileTheme.zip](https://github.com/ZenPhoto20/ZenPhoto20/files/949318/mobileTheme.zip)

**Comment by Mates-K1** [comment]
Log starts when I change theme from zpBootstrap back to zpArdoise (in PC), then logout in mobile, and afther that login in mobile. And last was refreshing main page in PC.

[debug.txt](https://github.com/ZenPhoto20/ZenPhoto20/files/949622/debug.txt)

**Comment by Mates-K1** [comment]
And when I logout there were errors/notices.

![wp_ss_20170423_0001](https://cloud.githubusercontent.com/assets/7648991/25312881/2403e2ac-2824-11e7-8cc5-1eb2f81d0a66.png)

**Comment by sbillard** [comment]
It would appear that I managed not to upload the debug version of the mobileTheme. Sorry. I will do so now.

The error you had with the MySQLi is indeed a bug, but it will show up only if you have the "EXPLAIN" option selected for debugging. You have quite a number of debugging options selected. Probably that is unintentional. But at least for this exercise please turn them off. Go to the "debug" plugin options and deselect everything but possibly the 404 error reporting. That is the only one I have set on a regular basis, and that is only so I notice if I have mis-typed the name of an image or script I will see that it did not load.

So, proper debug version of the plugin is below. I did have another thought on this, though. Do you  have HTML caching enabled? 

[mobileTheme.zip](https://github.com/ZenPhoto20/ZenPhoto20/files/949843/mobileTheme.zip)

**Comment by Mates-K1** [comment]
```
{14311:Sun, 23 Apr 2017 17:18:06 GMT}
  Passed theme: zpArdoise; detected desktop; returned theme: zpArdoise.
{14311:Sun, 23 Apr 2017 17:20:16 GMT}
  Passed theme: zpArdoise; detected phone; returned theme: zpBootstrap.
{14108:Sun, 23 Apr 2017 17:20:16 GMT}
  Passed theme: zpArdoise; detected phone; returned theme: zpBootstrap.
{9633:Sun, 23 Apr 2017 17:20:22 GMT}
  Passed theme: zpBootstrap; detected desktop; returned theme: zpBootstrap.
```

Problem is only after logout in mobile. Until that all is OK.

Caching plugin is ON. When I cleared html cache and disable plugin, problem persist.

**Comment by sbillard** [comment]
Can you please report what the "setupTheme" filters are?

On the overview page click on "active filters" link and scroll down until you find "setupTheme".

The log above indicates that the theme is being set before the mobileTheme gets into the act.

**Comment by Mates-K1** [comment]
Hmm... sometimes... no need to logout
```
{14311:Sun, 23 Apr 2017 17:46:24 GMT}
  Passed theme: zpArdoise; detected phone; returned theme: basic. (PC)
{9633:Sun, 23 Apr 2017 17:46:52 GMT}
  Passed theme: basic; detected desktop; returned theme: basic. (Android tablet)
```

```
setupTheme
5: mobileTheme.php => mobileTheme::theme
```

**Comment by Mates-K1** [comment]
Sorry... my titles were vice versa

```
{14311:Sun, 23 Apr 2017 17:46:24 GMT}
  Passed theme: zpArdoise; detected phone; returned theme: basic. (refresh in Android tablet)
{9633:Sun, 23 Apr 2017 17:46:52 GMT}
  Passed theme: basic; detected desktop; returned theme: basic. (refresh in PC)
```

**Comment by sbillard** [comment]
Do you have hitcounter enabled? If so, try with it disabled to test my current theory.

**Comment by Mates-K1** [comment]
You are right. With hitcounter disabled all is OK.

**Comment by sbillard** [comment]
Good news. Fix is on the way. Good catch!

**Comment by sbillard** [comment]
Give this build a try.

**Comment by Mates-K1** [comment]
It works. 👍 Thanks.

Menu seems OK.
