### ISSUE TITLE
RSS plugin - wrong tooltip or value?

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/ZenPhoto20#609]
In RSS plugin there is row called "Image feed sort order:" and value is integer but tooltip says "Choose between latest by id for the latest uploaded, latest by date for the latest uploaded fetched by date, or latest by mtime for the latest uploaded fetched by the file’ last change timestamp."

I think value should not be integer.

**Comment by sbillard** [comment]
You are correct. It should be a selector drop-down like for the album order.
