### ISSUE TITLE
Login via Google 

### ISSUE THREAD

**Issue by The-Edge-Malaysia** [ZenPhoto20/ZenPhoto20#614]
I can't make the federation login works accordingly. It keeps saying that i do not have the valid username/password and go back to login screen.

On another hand, I was thinking whether it is possible to use Google as authentication provider without using OpenID, i.e. google username, and password -> google authenticate -> zenphoto20 acknowledged and create user if it is first time login, or allow access if user has been verified by administrator.

**Comment by sbillard** [comment]
I presume you are attempting to use federated logon via the Google OpenID path. I have not tried that in a while, so I will see if there might be a problem now.

Currently all we have is the OpenID external authentication mechanism. It does seem that there is a PHP api for Google Authenticator, so it should be possible to implement that.

**Comment by sbillard** [comment]
It would appear that Google has deprecated OpenID 2.0 authentication. Thus the federated logon no longer works. I am not sure when this occurred. But I have also discovered that the OAuth library included with ZenPhoto20 has issues with PHP 7. There is an update for this, but it makes me wonder if anyone is actually using the federated logon feature. Verisign and Yahoo also do not work. Verisign authentication, at lease, has been discontinued.

I will look into what is involved in migrating to Google OpenID Connect. I rather suspect that Yahoo is a dead end, as obviously is Verisign. I do not expect to have any solution in the short term.

**Comment by The-Edge-Malaysia** [comment]
Thanks.

Assuming that we need to write one for Google Oauth2, how the custom script
can interacts with zenphoto20?

I.e. When user sign in using Google, google authenticate with token, then
how to trigger zenphoto20 to acknowledge whether it is new sign up,
revisited, etc?

**Comment by sbillard** [comment]
The federated_logon plugin is probably the model to use. But that certainly depends on how the Google OpenID Connect works. The other approach is to use the external authentication extensions. 

Are you interested in doing work on this? I can provide an external authentication example that supports single logon with MyBB scripts.

**Comment by The-Edge-Malaysia** [comment]
Hi!

I will try using google OAuth2 via your external authentication instead of
trying to figure out openid connect.

Thanks in advance

**Comment by sbillard** [comment]
This is the example I mentioned. I hope it helps. Please share your results.

[MyBB_auth.zip](https://github.com/ZenPhoto20/ZenPhoto20/files/1065905/MyBB_auth.zip)

**Comment by The-Edge-Malaysia** [comment]
Sure will try and update, thanks.

**Comment by sbillard** [comment]
I have located sufficient examples that I believe I can implement the Google Login protocol for ZenPhoto20. I have a working test case, so all that is needed is to integrate it into the ZenPhoto20 code.

**Comment by The-Edge-Malaysia** [comment]
Great!!

**Comment by sbillard** [comment]
I have attached the preliminary implementation of Google Login. There are some things you need to be aware of. (First is that I will be traveling and not responding to questions until June 20.)

1. You will need to create Google developer credentials and supply them to the plugin. You may already have an API key if you use the googleMap plugin. The OAuth credentials will need to be created. There is an explanation of what is needed and where to get them in the plugin documentation.

2. I had some issues with PHP CURL on my localhost test site. There is code in the plugin to set PHP CURL to ignore "invalid" ssl credentials to get around this. I have not tried on a "real" server to see if there are issues there as well. The plugin code is active for 127.0.0.1 so it should not be used on an open web server.
[setup-1.4.1.8.zip](https://github.com/ZenPhoto20/ZenPhoto20/files/1076223/setup-1.4.1.8.zip)


3. There is a strange failure that happened during my testing and is "explained" here: https://stackoverflow.com/questions/17813621/oauth2-0-token-strange-behaviour-invalid-credentials-401. I believe that the session_unset() solution works--it has so far in my testing. But who knows.

4. I obtained the Google API library via Composer. I have removed files that I (think I) know are not needed. There may be more, but I have not done any research on these details. (If you want to volunteer....)

**Comment by The-Edge-Malaysia** [comment]
Thanks a million!

**Comment by The-Edge-Malaysia** [comment]
Hi!

tested the code,

the following changes made in
zp-core/zp-extensions/googleLogin/user_authentication.php

require_once 'googleOAuth2/autoload.php';

managed to get the google login screen, just wanted to confirm whether the
callback URl is

http://myhost/zp-core/zp-extensions/googleLogin/user_authentication.php

however, it goes back to login screen and nothing happened.

**Comment by The-Edge-Malaysia** [comment]
according to zenphoto security debug claimed admin login success when using
google login, but I have set new google login user to fall under newUser
group.

when looking at the user profile, the user is created with no group attached

**Comment by sbillard** [comment]
Thanks for the note on the require path. Missed fixing that up from the initial hard coded test cases.

At least on my installation, the group "newuser" (no capital U) is a template and has no rights assigned. Is that the "group" you selected? Templates will set the user's rights, etc., but do not get assigned permanently to the user. Perhaps the plugin should not offer templates for assignment.

When I setup set the group to "newuser" and logged in with a new gmail ID form the login to admin.php I get the admin pages with a message stating "Your user rights do not allow access to administrative functions. " When I login from a link on the site web page I get redirected back to the web page and am logged in. After login in, can you visit the web home page and the admin page and see what you get. On the home page there should be the "admin" icon in the upper right. Hovering on it should show the user name.

Please also look at your server and zenphoto logs to see if there are any errors reported.

**Comment by sbillard** [comment]
[setup-1.4.1.11.zip](https://github.com/ZenPhoto20/ZenPhoto20/files/1095386/setup-1.4.1.11.zip)

Now only proper groups will be offered as default groups for the Google User. You should check your plugin options since this does not override an already set value.

The size of the extract.php file  has increased. I had to update my server's PHP.ini file to change the default memory size to 128. If you get a server error runing extract.php, check that setting.

Other fixes have been applied. I have now tried this on a web hosting server as well as locally. All seems to work.

**Comment by The-Edge-Malaysia** [comment]
Thank you sir!

**Comment by sbillard** [comment]
[setup-1.4.1.12.zip](https://github.com/ZenPhoto20/ZenPhoto20/files/1096412/setup-1.4.1.12.zip)

Just for grins, now supporting Facebook. Maybe I'll add others, if they are as simple as Facebook was. Any requests?

**Comment by sbillard** [comment]
[setup-1.4.1.17.zip](https://github.com/ZenPhoto20/ZenPhoto20/files/1100074/setup-1.4.1.17.zip)
 Now includes Linkedin and Twitter logons. Also functions to put logon buttons on the web page.

**Comment by sbillard** [comment]
[setup-1.4.1.25.zip](https://github.com/ZenPhoto20/ZenPhoto20/files/1136240/setup-1.4.1.25.zip)
Now includes Instagram.

NOTE: The callback URIs for Google and Facebook have been changed as part of this update. This was to make the plugins all consistent and allow a parent class for the code. BUT it does mean that if you have setup these login plugins you will have to change your callback URI in the Google and/or Facebook Developers Console.
