### ISSUE TITLE
image or folder name with &

### ISSUE THREAD

**Issue by The-Edge-Malaysia** [ZenPhoto20/ZenPhoto20#615]
How to avoid error when image or folder name contains &?

thanks

**Comment by sbillard** [comment]
You can run the seo_cleanup plugin (ADMIN=>SEO CLEANER)

This will fix up all your album and image names so that they are seo friendly. The & will be replaced by an underscore.

It seems not practical to try to handle this character in image and album names.

**Comment by The-Edge-Malaysia** [comment]
Thanks.
