### ISSUE TITLE
Error after installing 1.4.1.35

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/ZenPhoto20#616]
When acessing /zp-core/admin.php I get

Parse error: syntax error, unexpected '[' in /xxxxx/zp-core/zp-extensions/common/gitHubAPI/Github/Helpers.php on line 16

**Comment by sbillard** [comment]
Can you confirm that you are running PHP version not version 7?

Please change the lines to 

`private static $jsonMessages = array(
			JSON_ERROR_DEPTH => 'The maximum stack depth has been exceeded',
			JSON_ERROR_STATE_MISMATCH => 'Syntax error, malformed JSON',
			JSON_ERROR_CTRL_CHAR => 'Unexpected control character found',
			JSON_ERROR_SYNTAX => 'Syntax error, malformed JSON',
			JSON_ERROR_UTF8 => 'Invalid UTF-8 sequence',
	);`

That is change the brackets to array(....). I believe this is a PHP version issue.

**Comment by Mates-K1** [comment]
Running PHP 5.3.29

Error changed to:
Parse error: syntax error, unexpected '[' in /net/home/skaut.zamberk.cz/html/galerieonline/zp-core/zp-extensions/common/gitHubAPI/Github/Http/**Message.php** on line 16

**Comment by sbillard** [comment]
Ok. There appear to be several places that are version dependent. What other versions of PHP do you have access to?

**Comment by Mates-K1** [comment]
I have access to PHP 7.0 and 5.3.29.

**Comment by sbillard** [comment]
> But there is no ZP20 instalation in PHP 7.0. I am able to install it.

I am not sure I understand. ZP20 is fine with PHP 7.0, Anyway, you should probably move to PHP 7. See http://php.net/supported-versions.php for PHP support. Versions prior to 5.6 are not in support and have security issues.

I am going to make use of the version check dependent on version 5.5 which is the requirement for the library it uses. (That is the feature that caused the error.) Also all the federated login plugins will require PHP version 5.6.

But at least your tests uncovered this dependency. Thanks.> But there is no ZP20 instalation in PHP 7.0. I am able to install it.

I am not sure I understand. ZP20 is fine with PHP 7.0, Anyway, you should probably move to PHP 7. See http://php.net/supported-versions.php for PHP support. Versions prior to 5.6 are not in support and have security issues.

I am going to make use of the version check dependent on version 5.5 which is the requirement for the library it uses. (That is the feature that caused the error.) Also all the federated login plugins will require PHP version 5.6.

But at least your tests uncovered this dependency. Thanks.

**Comment by sbillard** [comment]
[setup-1.4.1.36.zip](https://github.com/ZenPhoto20/ZenPhoto20/files/1188405/setup-1.4.1.36.zip)

This version should not have the error. But of course, it will also not check for a newer version.

**Comment by Mates-K1** [comment]
I have two different domains from different providers - one with PHP 7.0 and another with PHP 5.3.29. I wrote to my provider to update PHP.

Your patch did not work for me. :( I had still same error. So... I think you will not like it, but I crippled many files with GitHub API (yes, there are a lot of dependencies) and I am able to access admin page. Now I wait until my provider updates the PHP and then I will update ZP20 to actual version.

I am going to send you updated language file in few hours.

**Comment by sbillard** [comment]
The 1.4.1.37 version should not have loaded any GitHup API files. Was that not the case? (I do not have a site which has PHP version 5.3 so I cannot make a test.)

**Comment by sbillard** [comment]
Maybe this version works better
[setup-1.4.1.38.zip](https://github.com/ZenPhoto20/ZenPhoto20/files/1189152/setup-1.4.1.38.zip)

**Comment by Mates-K1** [comment]
Yes, it works. Thank you very much.
