### ISSUE TITLE
Small typo - main setup page

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/ZenPhoto20#621]
![setup](https://user-images.githubusercontent.com/7648991/28986103-e9aa3834-7965-11e7-80b5-d1ecffcf40a4.jpg)

**Comment by sbillard** [comment]
That is actually not a typo. The diacritical mark is needed. ZenPhoto20 looks at the file to see how it is encoded. This is how it determines the filesystem encoding.

**Comment by Mates-K1** [comment]
Sorry.
Thank you for the explanation.
