### ISSUE TITLE
Improve backend design

### ISSUE THREAD

**Issue by You85** [ZenPhoto20/ZenPhoto20#622]
Hi, Currently, the backend is not very pretty it would be interesting to integrate adminlte

AdminLTE Control Panel Template
Best open source admin dashboard & control panel theme. Built on top of Bootstrap 3, AdminLTE provides a range of responsive, reusable, and commonly used components.
https://adminlte.io/

Thank You very much

**Comment by sbillard** [comment]
I am sorry you feel that the back end is not pretty. But your opinion appears not to be shared by other users. At any rate, if you are interested in contributing an implementation of a different kind please do so. We will evaluate your results and if it really does improve things it will be included.

I am going to close this ticket as there are no plans by the development team to change the back end presentation as we have just recently done so. 

Your pull request to provide an implementation will automatically create a new ticket should you choose to proceed with this endeavor.
