### ISSUE TITLE
Request : Improve the installation process

### ISSUE THREAD

**Issue by You85** [ZenPhoto20/ZenPhoto20#623]
Hi,
Currently when installing zenphoto 20 all the information is displayed on a page (mysql, php, ...) It would be interresting to improve the user experience and not to leak users to do the " Step installation. 
Step 1: Welcome message on Zenphoto20
Step 2: Configure the database.
Step 3: Administration and user passwords.
...

Thank You

**Comment by sbillard** [comment]
I am not sure I fully understand your request. 

Why would one want to force an extra step on a new user simply to display a welcome screen. Most users want to eliminate unnecessary clicks, not add them. Also, one only configures the database and user/password once but may run the setup application many times as one upgrades to newer versions of the software.

The rest of the information displayed by the setup program is there to help users who have issues with their server. The tests and prompts have been included based on a long history of noticing what goes wrong and understanding what information is necessary to help a user correct the situation.

For smooth running sites the upgrade process runs to completion without any interventions. It would make a far worse user experience to force the user to interact when interaction is not necessary.
