### ISSUE TITLE
Improve the storage system

### ISSUE THREAD

**Issue by You85** [ZenPhoto20/ZenPhoto20#624]
Zenphoto according to store the photos according to a tree that cuts the year, the month, the day of the addition of the photo.
![50f5b6ea28f48f44fbb6c2c5f95a3423 media 400x250](https://user-images.githubusercontent.com/30325749/29230996-acca11c0-7ee5-11e7-97ef-2753b68dc59e.png)

**Comment by sbillard** [comment]
I think you do not understand the philosophy of ZenPhoto20. Unlike other photo presentation software, ZenPhoto20 makes use of the file system to describe the content and hierarchy of its photo structure. You, the user define your structure, not the software.

So, if this is the organization you wish, simply define the folders on your site in this manner and distribute your images appropriately.
