### ISSUE TITLE
Replace icons by Font awesome in the backend

### ISSUE THREAD

**Issue by You85** [ZenPhoto20/ZenPhoto20#625]
These icons are more beautiful and follow current trends
http://fontawesome.io/icons/

Also I asked for an icon for zenphoto 20 click here to see : https://github.com/FortAwesome/Font-Awesome/issues/11379

**Comment by sbillard** [comment]
We always welcome contributions to the code base. If you wish to provide an implementation of this feature please create a branch of ZenPhoto20 and make your implementation. When you have thoroughly tested and verified the implementation you can make a pull request to get your work included into the base.

**Comment by sbillard** [comment]
Please note that we have used standard Unicode font icons. Using a custom font seems both unnecessary and overly complex, possibly even causing issues with some browsers.
