### ISSUE TITLE
bxslider_thumb_nav plugin - typo

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/ZenPhoto20#628]
![untitled 2](https://user-images.githubusercontent.com/7648991/29328481-04c7d3b6-81f3-11e7-842a-baf1cf801f90.jpg)

(translating to czech... so I find these typos...)

**Comment by sbillard** [comment]
fixed by c17692c0cd6b35104fe5bb0e1fb6445251127dd2

**Comment by Mates-K1** [comment]
Sorry, there is another one typo in this sentence.
I think there should be two L in "milliseconds".
