### ISSUE TITLE
dynamic-locale plugin - selector setting does not work in some themes

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/ZenPhoto20#630]
Selector does not show in:
- Gray Highlights 
- zpArdoise 
- zpBootstrap 
- zpEnlighten 
- zpFocus 
- zpMinimal
- zpskeleton

There are only flags in both of setting variant.

**Comment by sbillard** [comment]
I have taken a first look at this. As you know, themes may for their own reasons restrict what they show.  The call on printLanguageSelector() has a parameter that can be used to force a flag mode. This is certainly the case for Gray Highlights. It passes a 'true' to the function to force the flags.

The others all pass  the string "langselector" which is the same as passing 'true'. I haven't got a clue as to what their authors intended by this, maybe an option? But if so they should have just used the plugin option.

I will change them to use the setting and see what happens. If all behaves reasonably then I will release the change. If not the theme will be left forcing the flags selection.

**Comment by sbillard** [comment]
In addition to Gray Highlights, Enlighten and zpMinimal are coded to use flags and the selector does not work for them. The other themes seem ok with the selector.
