### ISSUE TITLE
Add icons to the menu

### ISSUE THREAD

**Issue by You85** [ZenPhoto20/ZenPhoto20#633]
![full-image](https://user-images.githubusercontent.com/30325749/29558289-f186835e-872b-11e7-87c2-2c02ad61ad87.png)

**Comment by sbillard** [comment]
Sorry, what is your point?

If you are simply advertising fontawesome then please be advised that is inappropriate for this venue.

**Comment by You85** [comment]
It's no advertising, i delete the link.

**Comment by sbillard** [comment]
The design of ZenPhoto20 includes a simple menu. We deliberately did not include icons. The design calls for icons on buttons, but not on the menu. 

If you think differently please state your case.

**Comment by Mates-K1** [comment]
I think icons would be required only if the menu has been shrinking/responsive - like Wordpress.

**Comment by sbillard** [comment]
The general philosophy is that menu items "take" you somewhere and buttons "do" some action. As such, the menu items do not have need for icons. They should be considered the same as general links. The icons for the buttons attempt to give some indication of the action. Of course, some actions are difficult to portray visually, so some icons are simply stand-ins.

Anyway, if no defense is put forward for menu icons this ticket will be closed shortly.

**Comment by Mates-K1** [comment]
I agree... 👍

**Comment by You85** [comment]
When a visitor discovers your CMS online for the first time, it starts with the scanner by operating a diagonal reading. It is during these first few seconds that he decides if your CMS deserves to be linger. The icons not only capture people's attention, they also encourage them to find out more and understand your CMS more easily.

The use of pictograms in the graphics chart in the backend is a very effective way to communicate with potential users. Here's why:

-an icon allows you to instantly communicate an idea by transcending language barriers. Do we not say that an image is better than a thousand words?

**Comment by sbillard** [comment]
I do not agree. What icon connotes the idea of "Overview", "Cache Images", "Site statistics", etc. I think none. A meaningless icon is less than useful. It takes up valuable real estate on the page.

Anyway, a user of a foreign language will see these labels in his native language so long as that language is supported and his browser properly identifies his preferred language.

The design choices will stand.
