### ISSUE TITLE
Groups vs Users - different order of "Managed..." items

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/ZenPhoto20#636]
I know... it is a very small thing, but I think it will make the gallery a little bit better...

![untitled 1](https://user-images.githubusercontent.com/7648991/29670680-b198291a-88e7-11e7-92c8-5a4d53057b39.jpg)

Thanks.

**Comment by sbillard** [comment]
fixed by 469c0df3e8da62ba2a378eaf40c918e3ade88a09

For some reason the git system did not recognize the fix in the commit
