### ISSUE TITLE
If user group has exactly one member, drop down menu is not visible

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/ZenPhoto20#637]
In Admin - Users, if user group has exactly one member, drop down menu is not visible.

One menber: 
![6acff6a5-8677-4037-b68a-cb29b8c54b85](https://user-images.githubusercontent.com/7648991/29684396-189be32a-8912-11e7-9a48-67e4b91c90cc.png)

Zero member:
![261024a5-e32d-4f95-8c3c-3c516a9143ec](https://user-images.githubusercontent.com/7648991/29684450-4aeed0ee-8912-11e7-8e05-48cd3c6a572d.png)

More then one member:
![aeef7e0d-7b93-4ecc-a36d-3de4d8606d20](https://user-images.githubusercontent.com/7648991/29684532-9c8503a6-8912-11e7-9bad-db3c1c8c7cb0.png)

**Comment by sbillard** [comment]
I am not sure I completely understand.

This drop-down is to "filter" the users that are displayed. I think you are describing a case where there is only one user (does not matter if part of a group or not.) If so, when there is only one user there is no need to filter the display, that user is shown as he is the only choice.

**Comment by Mates-K1** [comment]
Yes.... but how I change the filter to another group if there is not drop down menu?

The only solution is go to Admin - Users again...

**Comment by Mates-K1** [comment]
I do not understand the difference between exactly one and more then one members to show.

**Comment by sbillard** [comment]
I do not mean one member of the group, I mean only one user for the site.
