### ISSUE TITLE
Login screen - "ugly" show password title

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/ZenPhoto20#639]
For example in zpArdroise - light area on dark background:
![f6d7427a-72d3-4e4e-a340-245589c3ce08](https://user-images.githubusercontent.com/7648991/29822561-2c0c759c-8ccc-11e7-9aa2-547c4b6778c5.png)

Please make it nice again. :)

**Comment by sbillard** [comment]
This fix is against the current development. When I tried to back fit it to the 1.4.3.4 branch it did not quite work. I think there is too much change that may have impacted the code. Anyway, the next major build is not far off, so I will release the fix there.

I did encounter some issues that are not "fixed." Some themes CSS does damage to the form that is difficult if not impossible to locate a root cause.

gray_highlights seems to hide all text on the form (but not the actual checkbox.) I could not discover where/how it did this, so I simply hid the checkbox as well.

libratus and zbase both somehow pad the "Show" string so that if it has a background too much is blotted out. These I have made the background transparent.

Other themes have fooled with the vertical positioning of the checkbox itself. I have not corrected this as it is not too objectionable.

Some themes do not provide a logon form. I have left them as is. 

Generally the philosophy is to make minimal stylistic changes to themes.

[setup-1.4.3.4d1.zip](https://github.com/ZenPhoto20/ZenPhoto20/files/1261930/setup-1.4.3.4d1.zip)

This is the current state of the next release. Mostly it changes from images to unicode characters for the button (and other) icons. If you can install it somewhere and run it through its paces it would help me. I think it is time for fresh eyes.

**Comment by Mates-K1** [comment]
Instaled. :) 
So... Some icons I like, others not so many (icon for Back, Add...). Do you need this type of feedback?

Plugins list
There are three icons - info, setting, warning.
Info - in whole gallery INFO works only on hoover mouse action. There you must click but mouse cursor dont change on hoover. Warning is the same.

Icon formating when there is longer description.
![89e6b549-b8c6-48ae-a39e-544817acb87f](https://user-images.githubusercontent.com/7648991/29865700-765340a4-8d76-11e7-92ad-c8e0bfd4e343.png)

**Comment by Mates-K1** [comment]
I think changing mouse cursor on hoover (in plugin list) and click will be better.

**Comment by sbillard** [comment]
I'm away for a small vacation. I appreciate your feedback on this (and other reports) and will address them later next week. But in general I agree. 
On Wednesday, August 30, 2017 at 2:40 AM MartinKroul <notifications@github.com> wrote:

I think changing mouse cursor on hoover (in plugin list) and click will be better.

**Comment by Mates-K1** [comment]
Enjoy your vacation! 👍 


I would suggest:

Setting - &#9881;	2699
Warning - &#9888;	26A0
Back - &#10094;	276E
Info - &#8505;	2139
Reset - one of recycling icons? - &#9850;	267A
Add - &#63490;  F802 - lower left pencil - but this does not work for me (Vivaldi, Chrome, Edge), so another pencil, for example &#9998;  270E

**Comment by sbillard** [comment]
I think that the icons without colored backgrounds look cleaner. Besides most of the choices don't have backgrounds. So I will stick with the original Warning and Info icons.
I will use your suggestion for the Back and Settings Icons and will use a "bolder" one of the Recycle icons.

The pencil icon you show is the exact one that is used.

**Comment by Mates-K1** [comment]
Ok, I think it is a good compromise. 👍

**Comment by sbillard** [comment]
[setup-1.4.3.4d3.zip](https://github.com/ZenPhoto20/ZenPhoto20/files/1279399/setup-1.4.3.4d3.zip)

See how this  one looks.

**Comment by Mates-K1** [comment]
Back icon is OK.
Setting icon (in Plugins) didnt changed - there is still &#9788; , no &#9881;
Reset icon is OK.

I'm not entirely happy with the automatic opening of the window after moving the mouse over info icon. I would prefer the original solution - that is opening the window after clicking but I would just change the mouse cursor to the icon to make it clear that it can be clicked on.

And in this plugin info window link to google translate dont work (error 404).

**Comment by sbillard** [comment]
Please try clearing your browser cache. I have the gear with hub icon when I view the plugins pages.

As for the info window, the maybe a longer delay. When I first implemented the automatic opening I had the same issues you did. It now waits for 1 second mouse hover before opening. Maybe a longer wait? Line #387 has the delay value. currently it reads "}, 1000);" Just up the 1000 value and see what might work. 

The 404 is probably a case sensitivity issue. I did find a few of those when I was implementing this. But I am on Windows and it doesn't care, so it is easy for me to miss them.

**Comment by sbillard** [comment]
I do not see the "google translate". Is this a plugin or a link within one of the documents? If so, which.

**Comment by sbillard** [comment]
404 was because Google changed the mechanism for requesting a page translation. New way is now incorporated.

Changed the info window to require a click and changed the pointer.

[setup-1.4.3.4d4.zip](https://github.com/ZenPhoto20/ZenPhoto20/files/1283013/setup-1.4.3.4d4.zip)

**Comment by Mates-K1** [comment]
Mouse cursor and opening window work as I expected.
Google translate works too. Thanks.

But info and setting icon work only in Edge browser, not in Chrome and Vivaldi - cache cleared severeal times. :/

**Comment by sbillard** [comment]
This is a screenshot from Chrome (Firefox looks the same) on my Windows PC. I also downloaded and installed Vivaldi and it looks as well the same. What OS are you running? The html codes are info:#8505 and options:#9881

![capture](https://user-images.githubusercontent.com/2474007/30172159-d2ea7606-93a8-11e7-8507-dd26c8ccd823.PNG)

**Comment by sbillard** [comment]
I found a means of telling what fonts are being used: https://stackoverflow.com/questions/884177/how-can-i-determine-what-font-a-browser-is-actually-using-to-render-some-text

On my system these icon fonts are all Segoe UI Symbol.

**Comment by Mates-K1** [comment]
I use Windows 10.
My icons look the same as yours (Vivaldi/Chrome). 

But in http://www.zaposphere.com/html-icons-reference-unicode-character-list and here they look differently:

![6d90f6ea-534c-41f7-9fb4-2b66742ce660](https://user-images.githubusercontent.com/7648991/30196298-fc88845a-945f-11e7-9a69-52242fc904a4.png)

In gallery in Edge the look the same as on the picture.

My browser (Vivaldi) use Segoe UI too. But in Gallery it says Arial (via WhatFont extension).

**Comment by sbillard** [comment]
Different fonts do render these icons differently. But I guess I don't know why your system seems to be using different fonts than mine. All my browsers, edge, IE, Chrome, FireFox, and Vivaldi render them like my screenshot. Only Safari is different and it does not render some at all. But I decided not to worry about that. Safari on Windows would be an unusual choice.

I will upload a new version later today that will load the FreeSerif font and designate it as the preferred font for these icons. Maybe that will help. (But on my system the actual selected font is still often Segoe UI, so who knows.)

**Comment by Mates-K1** [comment]
Ok. 

Are you planning to release it as a some bigger version? I have an updated Czech translation with many new phrases that I can send you.

**Comment by sbillard** [comment]
Yes, this will be probably 1.4.4.

Once we get all these icons resolved it will be ready for release, I 
think. But there is not a hurry, so whenever you want to send me the 
updated translations will be fine. I will also have to re=run all the 
mechanical translations, and that takes a few days (otherwise I use too 
much of PoEdit server time!)


-Stephen

**Comment by sbillard** [comment]
So here is the current situation. I have added a font "FreeSerif" to the software which contains most of the icons used. Only the clock and the clipboard are not in it. These will revert to the Segoe fonts if those exist. if not, maybe they will be found in some other present symbol font. I suppose I could just make them images. If someone reports them missing I guess that is what I will do.

[setup-1.4.3.4d6.zip](https://github.com/ZenPhoto20/ZenPhoto20/files/1289429/setup-1.4.3.4d6.zip)

**Comment by Mates-K1** [comment]
It works now. :) Thanks.

Two last little thing:
1. Can you please make those icons a little bit smaller (height)? They are as high as whole row.
2. Can you please add some space between icons and text?


![412bfc14-f2ff-42e4-9c31-98aef957ab5b](https://user-images.githubusercontent.com/7648991/30237920-a3e60132-953c-11e7-9819-3cc0d9405c6e.png)

Many thanks.

**Comment by sbillard** [comment]
I am quite frustrated with all this. Yesterday these were rendering in the FreeSerif font. Today they are in Segoe Emoji. The emoji are too large. I can force them back to Segoe UI Symbol which is the rendering I prefer anyway, but I wish I knew why they are not using the FreeSerif version. 

Please change your admin.css file to be:

.font_icon {
	font-family: FreeSerif, Segoe UI Symbol, Segoe UI Emoji;
	display: inline-block;
	width: 18px !important;
	height: 18px !important;
	text-align: center;
}

(Reverses the order of Emoji and Symbol)

When the browsers were honoring the FreeSerif designation then the Emoji was prefered for the clipboard icon. But if it is going to use the Emoji for everything....

**Comment by sbillard** [comment]
I think I have figured out how to have *most* browsers use the Free Serif font. Seems css loading sequence is important. I ended up putting the FreeSerif css code into the admin.css file.

Some of my Android browsers don't seem to load the Free Serif, so I have chosen icons that "work" for them when they fall back to whatever they are using. I made a plugin to show all the icons ZP20 uses. You don't need to enable it, just click on its Options and the page will show the set.

[icons.zip](https://github.com/ZenPhoto20/ZenPhoto20/files/1291103/icons.zip)



[setup-1.4.3.4d8.zip](https://github.com/ZenPhoto20/ZenPhoto20/files/1291102/setup-1.4.3.4d8.zip)

**Comment by sbillard** [comment]
[setup-1.4.3.4d10.zip](https://github.com/ZenPhoto20/ZenPhoto20/files/1300073/setup-1.4.3.4d10.zip)

Version with added debug info.

**Comment by Mates-K1** [comment]
I am online again. :)
My icon set (identify as Free Serif) in Vivaldi (Chromium):
![b7cc0c39-db05-40c1-8c3b-038a198c1ec7](https://user-images.githubusercontent.com/7648991/30413144-b69886d6-991c-11e7-8f88-af449bd9ef56.png)

Icons look the same in Edge (this is a change from the original state).

**Comment by sbillard** [comment]
Great. These are what I expect to see. I do see a difference on my Android browser but have decided that the difference is acceptable. So I think we are near ready for a release. I await your translations.
