### ISSUE TITLE
Text overflowing/spacing in Overview tab

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/ZenPhoto20#642]
![untitled 2](https://user-images.githubusercontent.com/7648991/30413976-94d136c4-9921-11e7-973a-8f8516402bcd.jpg)

Is possible to fix it or should I try to shorten the text?

**Comment by sbillard** [comment]
I can add a bit more space. See how this update works for you.

**Comment by Mates-K1** [comment]
Yes, it works. Thanks.
![b49d0de6-bdb4-4c67-bbc4-bb5c9a64ff1e](https://user-images.githubusercontent.com/7648991/30510588-6b3a0c94-9ac7-11e7-8f02-bf6a156e9bae.png)
