### ISSUE TITLE
User sorting - dropdown menu don't hold current group

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/ZenPhoto20#656]
1. Choose one of user groups.
2. In user dropdown menu choose another page.
![001](https://user-images.githubusercontent.com/7648991/31465182-75518782-aed3-11e7-8f3e-64d619c5c2c2.jpg)

Result:
![002](https://user-images.githubusercontent.com/7648991/31465191-79e5d37a-aed3-11e7-8509-36093cf619d0.jpg)

List ends by "Profesor" (not "robin") because there is my master account too. I think dropdown menu with usergroups don't hold them after changing page (I expect it). Next and Prev button don't works in this case too.

**Comment by sbillard** [comment]
Please try the development build and see if all these issues are indeed corrected.

**Comment by Mates-K1** [comment]
Thanks for fast response - as usually. 👍 

All works and was repaired except "Images edit page - top menus alignment". I tried it in three browser, always after cache cleaning, nothing changed.

**Comment by sbillard** [comment]
Please try the updated dev build.
