### ISSUE TITLE
Another text overflowing

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/ZenPhoto20#658]
In Slovak (English and Czech are OK):
![6e978713-169b-4cef-9e48-b02119872472](https://user-images.githubusercontent.com/7648991/31483916-9af9b7c4-af2e-11e7-80fe-82af962071d2.png)

In Czech (album edit page - "Cache album images" text):
![d7255fc1-c915-43c7-ac23-163c783049af](https://user-images.githubusercontent.com/7648991/31483856-67b0bbce-af2e-11e7-8033-47ec6a4cef8e.png)

**Comment by sbillard** [comment]
That is probably too much text. To make it work the whole set of buttons would have to be enlarged. In my opinion that would be too much real estate. I think in these instances, the work "album" is redundant and can be omitted. Does that help?

**Comment by Mates-K1** [comment]
Yes, it does help. I think I never use this button (propably any of cache button).

**Comment by sbillard** [comment]
I'll close this, then.
