### ISSUE TITLE
Fast link to my user profile + users displaying

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/ZenPhoto20#659]
I often need to change my language, so I would like to have fast link to my profile, for example by clicking my name in the top-right corner - "login as...".

Now I have to click Administrator - Users, then go to third page and click to my name.

Also, I'm a little upset that when I save changes to the user profile I get first page with users.

Overall, I did not get used to the way users are shown (x user per page with unrolling). I prefer one user per page style. I dont have reason to display ten users per page for some changes - for this case I have group view.

It would be better for me to have X users per page and when I click on the name the new page is shown. There I can do changes and can save this single page. Maybe searching in users will be useful too.

**Comment by sbillard** [comment]
> I often need to change my language, so I would like to have fast link to my profile, for example by clicking my name in the top-right corner - "login as...".

Could you provide some more detail? Would you have a user name for each language? Or do you want a language qualifier when you log in? Is this on the administrative pages or theme pages?

When saving users you should be on the page that contained any user saved. I will look into that.  You can change the number of users per page to 1, does that do what you like? This is on the general options page down near the bottom.

Users should now be listed properly alphabetically, so finding one should not be so difficult.

**Comment by Mates-K1** [comment]
I would like to have some quick option to get to my user profile on admin pages.

In the top-right corner there is my login name, it would by nice when I click this name and page with my profile would display.

Thank you for your directions -  one user per page is OK for me. But can you divide this options (user per page) to users and groups? Now this options affect groups too.

**Comment by sbillard** [comment]
try these changes

**Comment by Mates-K1** [comment]
Wow! Works great - link and single user page.

Thank you very much for bringing my requests into reality. 🥇
