### ISSUE TITLE
Database update error

### ISSUE THREAD

**Issue by JimBrown** [ZenPhoto20/ZenPhoto20#672]
Every time I run setup, I get the following error in the setup log:
```
Begin database creation and update
Query Failed: ALTER DATABASE rcairg2_zen-rcairgallery CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci; 
 Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-rcairgallery CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci' at line 1
```

PHP version is 5.4.34.
MySQL version is 5.6.14.
(I am not allowed to upgrade these.)

No issues with running the site.

Thanks.

**Comment by JimBrown** [comment]
Found the issue.

In `database.php`, line `214`, the following query needs backticks around the database name:
```
	$sql = 'ALTER DATABASE ' . db_name() . ' CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;';
```
Like so:
```
	$sql = 'ALTER DATABASE `' . db_name() . '` CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;';
```

Thanks.

**Comment by JimBrown** [comment]
Also in file `migrate.php`, line `46`

**Comment by sbillard** [comment]
Thanks. Should have realized this when MySQL said the error was at "-rcairgallery". The hyphen needed to be quoted. Fis shortly.
