### ISSUE TITLE
Error when showing un-categorized news

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/ZenPhoto20#676]
Have some news, all of them without category.
Create a new category.
Show un-categorized news.

![40a34c92-d07f-4e5d-a699-fdff40e02fa2](https://user-images.githubusercontent.com/7648991/33162550-5e9b2138-d02a-11e7-828a-8e23d5ebc31b.png)
(there is some string in the circle)

**Comment by sbillard** [comment]
I found the issue with the string in circle, but I did not reproduce the SQL error. Please try the fix in the development repository to see it the error goes away.

**Comment by Mates-K1** [comment]
Yes, it works without error. Thanks.

**Comment by sbillard** [comment]
closed by https://github.com/sbillard/ZenPhoto20-DEV/commit/21b7e715851f32ce8fbab7b4fed793d7fb2677c7
