### ISSUE TITLE
News dropdown menu shows "dots"

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/ZenPhoto20#677]
![untitled 1](https://user-images.githubusercontent.com/7648991/33162639-df5384f0-d02a-11e7-9de8-6ec5e9ea8658.jpg)

**Comment by sbillard** [comment]
I cannot tell from your image what you are sorting by. I presume it is a date, though. You will get these dot-dot-dot items when there is no date set. So if the you are sorting by publish date and there are articles with no published date you will get these in the list. If you have a suggestion of how better to show dates in the list that are "empty" I am open to change.

**Comment by Mates-K1** [comment]
You are right. No one of articles are published.
Is possible to disable sorting by published (or expired) date in this case? Or add/show text like "none of the articles have been published yet"?

And another strange text when sorting these unpublished articles by title descending

![untitled 1](https://user-images.githubusercontent.com/7648991/33188894-1ae9c4b6-d09e-11e7-9b78-23af6f8952e8.jpg)
and by title ascending
![untitled 2](https://user-images.githubusercontent.com/7648991/33188900-2b637378-d09e-11e7-8e28-9d6927073ea5.jpg)

Is possible to keep the size of the letters? The first letters of article titles are small now...

**Comment by sbillard** [comment]
It would be possible, but there is still the case where some articles are published and others not. So in that case the dot-dot-dot will still occur.

I saw the title issue too when looking into the dates. It is fixed by 8f09292b33c37598527e5bc58d9f5be59bbfac0a

**Comment by Mates-K1** [comment]
Ok, but if there is only one published article, dropdown menu has three rows. I would expect only one row.
![image](https://user-images.githubusercontent.com/7648991/33207146-ea041a12-d10c-11e7-9264-04dfec09a951.png)

Bug from second picture is fixed. Many thanks.

**Comment by sbillard** [comment]
Maybe, but when there are multiple pages of unpublished articles, how do you select the second and later ones?
