### ISSUE TITLE
Question on workflow

### ISSUE THREAD

**Issue by JimBrown** [ZenPhoto20/ZenPhoto20#679]
I have a fork of ZenPhoto20. If I want to do a pull request, should I fork ZenPhoto-DEV first, make the changes there, then PR to your fork of ZenPhoto20-DEV? If so, should I create a temporary branch within ZenPhoto20-DEV and use that for the PR?

Or should I just do the PR against ZenPhoto20?

Thanks,
...jim

**Comment by sbillard** [comment]
So, kind of depends. All my new development goes first into ZenPhoto-Dev, so if you fork it you will be working with the bleeding edge. For a new feature that is probably the best approach. But for general fixes or small changes there should be no issue doing with the master repository.

The bit difference is that if the change is involved I will want to first stage it against the DEV repository to be sure nothing gets broken.  I can do that with a PR against the base, but it is more work. For simpler changes I will normally eye-ball the change and approve it if it looks good.

**Comment by JimBrown** [comment]
Got it. Thanks.
