### ISSUE TITLE
ExtraContent, Custom and Codeblocks are not displayed in admin>news/pages

### ISSUE THREAD

**Issue by vincent3569** [ZenPhoto20/ZenPhoto20#699]
hi
the fields ExtraContent, Custom and Codeblocks are not displayed in admin>news and admin>news.

**Comment by sbillard** [comment]
Custom data is a deprecated field. You can re-enable it by enabling the _customData_ plugin. But better is to define the fields you need via the _fieldExtender_ mechanism as described in the plugin doc block. The old use of this field caused many multiple use conflicts.

ExtraContent and Codeblocks are optional fields. These are enabled by the _optionalObjectFields_ plugin.

**Comment by vincent3569** [comment]
Custom data field don't miss me.
But I don't really understand why you made ExtraContent and Codeblocks optional fields.
You could have keep them in admin, and themes are free to use it or not.
And lats, for those who want to migrate from zenphoto, it cause lost of data.

**Comment by sbillard** [comment]
The _optionalObjectFields_ plugin is enabled by default. Probably when you purged your options that disabled it.

**Comment by vincent3569** [comment]
ok
btw, something optional but enabled by default, it does not seem consistent to me.
and probably very dangerous as we can purge options and lost data.

a little early, I wish you a very happy new year 2018

**Comment by sbillard** [comment]
No data is purged until you run setup. There should be a setup request message displayed when you change the enabled state of these plugins. I will see if I can make the message more clear.

You can certainly lose a lot of data if you arbitrarily purge options. This should always be done selectively.

Happy New Year to you as well.
