### ISSUE TITLE
zpMasonry - cant save images size setting

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/ZenPhoto20#714]
Cant save images size in zpMasonry setting - size (in pixels) can be saved, but allways there is "longest side" setting after I click Apply button.

**Comment by sbillard** [comment]
This is because the theme forces the settings of thumb size, thumb crop and thumb side. I do not know the reasoning for this, one would have to ask the original theme designer. But the theme should "disable" these choices if it is going to force the setting. That I can add.
