### ISSUE TITLE
Error in admin Comments

### ISSUE THREAD

**Issue by Elinth** [ZenPhoto20/ZenPhoto20#721]
I see the following error in the comments overview in the admin section
NOTICE: "A non well formed numeric value encountered" in /srv/disk6/279773/www/website/zp-core/functions.php on line 386 

The error is displayed in red 5 times in a row above the comments and dissapears when I change the language of the site from Dutch to English.

**Comment by sbillard** [comment]
What is your timezone (General options page?) Also highlight the info icon and see what is show for the offset.  I presume there are 5 comments on the page? What are the dates shown for each comment? Are they different between English and Dutch?

**Comment by Elinth** [comment]
Time zone is Europe/Amsterdam.The date format for the 5 comments is year-day-month , while the format from the admin comment settings is day- month- year. Is this causing the error? The error now happens in both languages.

**Comment by Elinth** [comment]
Ah, I just saw your commit. Did you fix it?

**Comment by sbillard** [comment]
[setup-1.5.3.01.zip](https://github.com/ZenPhoto20/ZenPhoto20/files/1682419/setup-1.5.3.01.zip)

Please try this version to see if it corrects the issue. It changes things, but since we don't actually know what was wrong, not sure if it will be the fix.

**Comment by Elinth** [comment]
That did the trick, no more errors
