### ISSUE TITLE
Forgot user name and password page in theme style

### ISSUE THREAD

**Issue by Elinth** [ZenPhoto20/ZenPhoto20#722]
Hi Stephen, is it possible to have the "forgot user name and password page" in the style of the theme?
I do not see a page for this in the theme pages and it seems part of the admin.

**Comment by sbillard** [comment]
I am not sure exactly what you are asking. The logon form (of which the forgot password is a sub part) can be styled by your theme CSS.  But it is not possible to change the content of the form.

**Comment by Elinth** [comment]
Are you sure? The login form is in theme style and has a password.php page in my theme that I can style. However, when you click on the link that says forgot password it takes you to a page which is not part of the (in my case ZpArdoise) theme. It takes you to zp-core/admin.php?logon_step=challenge&ref=
I'd like to style that page with my theme style. But it seems to me there is no page for this in the theme.

**Comment by Elinth** [comment]
I'd like to put my header and footer in this page.

**Comment by sbillard** [comment]
Once you click on that link you are no longer on the theme, so the theme CSS does not apply. The link redirects you to the administrative  handling pages. The primary logon form is displayed by the theme which is why it can be styled. There is no means to apply theme styles to the administrative pages.

**Comment by Elinth** [comment]
ok, thanks!

**Comment by sbillard** [comment]
I actually think that this can be changed. I am experimenting with some changes that leave the user on the front-end when the link is checked.

**Comment by Elinth** [comment]
That would be brilliant! Thank you!

**Comment by sbillard** [comment]
I have a version implemented in my development branch. The only problem is that it does not have the debug code for your issue #715. Do you have the ability to run two different versions of ZenPhoto20?

**Comment by Elinth** [comment]
Unfortunately, I only have the possibility for one version..

**Comment by sbillard** [comment]
Not a problem. Once you have trapped the details on the lost rights you will be able to move to the version with this change.
