### ISSUE TITLE
Tooltip for password strength

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/ZenPhoto20#726]
Please add tooltip with actual setting (number of characters) for password strength in Setting-Security (slider). This information is only hide in info on the end of row.

**Comment by sbillard** [comment]
The password strength value is not actually a character count, it is a function based on the number of Capital letters, Special characters, and numbers. It is not an exact science, so I am not sure that the actual number is all that important. The slider bar gives you an indication of the strength by the color of the slider. Green is desired.
