### ISSUE TITLE
User registration questions

### ISSUE THREAD

**Issue by Elinth** [ZenPhoto20/ZenPhoto20#728]
Hi Stephen, You are such a great help and I love this Zenphoto20 build!!
A coupe of questions regarding the registration plugin I hope you can answer. 

1. When a new user registers, he or she fills in the registration form and receives an email confirmation email. When they follow this email hyperlink they are taken to the admin part of Zenphoto20 and in my case they do not have admin rights. Zenphoto20 will throw a message that the user does not have admin rights. Why does the new user registration after verification end up in the admin part? (zp-core/admin.php?from=/zp-core/admin-users.php) Is it possible for the user to go straight to the gallery? In my case users do not do anything in the admin part and this is confusing for them.
2. When a user registers, is it possible that it could be in a "pending administrator approval" mode? This way the admin can control the user rights. 
Many thanks for your help!

**Comment by sbillard** [comment]
The link needs to be visited to confirm the e-mail address. Normally a user would have at least USER rights to be able to change his password, etc. In that case he would land on the USER tab for his user. Also you can assign a user group to the registration and the user will get the rights from that group when he is registered.

**Comment by Elinth** [comment]
I think its good that they have to confirm their email adress, but when they click on the link, can they be taken to the front end (gallery), instead of the Zenphoto20 admin part of the site?

**Comment by Elinth** [comment]
And is there a way for an admin approval of the user registration?

**Comment by sbillard** [comment]
Assign them to a group with no rights when they register, then approval would be assigning them to the desired group.

**Comment by Elinth** [comment]
Thanks for the fix! The assignment to no rights is something I already did as a setting.
Is that fix part of the 1.5.3.04. build?

**Comment by sbillard** [comment]
That fix is in 1.5.3.04

**Comment by Elinth** [comment]
Hi Stephen, this is awesome!!! 
I just did the set-up. One more question, is it maybe possible to create another field in the registration plugin where you can edit the text: "Your registration has been accepted, an email has been send to you for verification". That would help greatly for flexibility. This way I can warn my users that after email verification they have to wait for admin approval.  (Where I set their group rights.) Thank you so much!

**Comment by sbillard** [comment]
No problem, the change will be in the next update.

**Comment by Elinth** [comment]
You are a genius!! Thanks so much! Have a nice weekend!

**Comment by sbillard** [comment]
[setup-1.5.3.05.zip](https://github.com/ZenPhoto20/ZenPhoto20/files/1734231/setup-1.5.3.05.zip)

Give this a try. Also, any update on issue #715?

And your colorbox issue? See https://github.com/ZenPhoto20/ZenPhoto20/issues/674 for the previous instance of this problem (which is fixed.)

**Comment by sbillard** [comment]
This fix is rolled  up into the current bug fix builds.

**Comment by Elinth** [comment]
Thanks!!! Sorry for the late reply!!
