### ISSUE TITLE
command line extract.php

### ISSUE THREAD

**Issue by mebels** [ZenPhoto20/ZenPhoto20#732]
Hello,
the URL query string for extract the extract.php is uncool. I will extract the file in the command line like
```php extract.php```
not in a browser.

**Comment by sbillard** [comment]
Sorry, is there a problem here?

If you have the means to run PHP from the command line, by all means do so. Not everyone has that ability, though.

**Comment by mebels** [comment]
Yes, i download it via command line "wget" and extract it via "unzip", and than i can't run it via "php" only about a query string. Is the query string really necessary? Remove it! That would be a nice thing.

**Comment by sbillard** [comment]
Unfortunately the query string necessary due to how web browsers work (which is the primary target for this script.) You could create a PHP shell that runs the script after setting $_GET['process']=1;

**Comment by sbillard** [comment]
You could also simply download the zipped repository from GitHub and unzip it on your command line. The extract.php script is really intended to be run from a web browser--that is the way most clients use it.
