### ISSUE TITLE
security-logger.php

### ISSUE THREAD

**Issue by mebels** [ZenPhoto20/ZenPhoto20#733]
CentOS Linux release 7.4.1708 (Core)
PHP 7.1.13
10.1.29-MariaDB

By the first watching the backend are display a "secure scripts" warning. I click the Link. Then i become this errors.

``` NOTICE: "Undefined variable: pattern" in /.../zp-core/zp-extensions/security-logger.php on line 101 WARNING: "preg_match(): Empty regular expression" in /.../zp-core/zp-extensions/security-logger.php on line 101 ```

By the next clicks are hidden.

**Comment by sbillard** [comment]
Secure scripts warnings do not come from ZenPhoto20 but rather from your site configuration. What link exactly did you click on that lead to the Notice message? The actual error reported is now fixed, but what lead up to it might still be a problem

**Comment by mebels** [comment]
No idea. I did not notice the link. The warning was this: The scripts are not secure (something with file permission) and then the link: make it secure here.
