### ISSUE TITLE
Overview - Gallery Statistics - SQL error

### ISSUE THREAD

**Issue by mebels** [ZenPhoto20/ZenPhoto20#734]
CentOS Linux release 7.4.1708 (Core)
PHP 7.1.13
10.1.29-MariaDB
ZenPhoto20 1.5.3.09

Fresh installation.
Overview - Gallery Statistics:

```USER ERROR: "MySQLi Fehler: (DELETE FROM `zen_search_cache` WHERE `date`<'2018-02-26 16:02:23') fehlgeschlagen. MySQLi gab den Fehler Table 'xxx_xxx.zen_search_cache' doesn't exist zurück" in /.../zp-core/functions-common.php on line 55 ```

**Comment by mebels** [comment]
Same in:
Cach images stored in the database

```USER ERROR: "MySQLi Fehler: (SELECT * FROM `zen_pages` WHERE `extracontent` REGEXP "<img.*src\s*=\s*\".*i.php((\.|[^\"])*)") fehlgeschlagen. MySQLi gab den Fehler Unknown column 'extracontent' in 'where clause' zurück" in /.../zp-core/functions-common.php on line 55```

**Comment by sbillard** [comment]
There are two different issues here. The first error message tells us that the table 'search_cache' is missing. That really cannot be the case if the setup program has successfully run. Perhaps the error in #733 happened during setup? If so you will need to re-run the corrected version of setup program.

The second error could also be from setup not successfully completing. But is is also a logic error in the cache manager. The 'extracontent' field is optional and this code did not take that into account. That is fixed.

**Comment by mebels** [comment]
Sorry. Yes, the errors becomes after fresh installation.

**Comment by sbillard** [comment]
Ok, then I believe that the current support build fixes the problem. Please install it.
https://github.com/ZenPhoto20/ZenPhoto20/releases/download/ZenPhoto20-1.5.3.0/setup-1.5.3.10.zip
