### ISSUE TITLE
Video player no longer working

### ISSUE THREAD

**Issue by JimBrown** [ZenPhoto20/ZenPhoto20#736]
I have my own video player plugin, using VideoJS. I have just updated to the most recent version of ZenPhoto20 (1.5.3.10) and my plugin is no longer working. Also, the JPlayer plugin is not working either.

I notice that the class-video plugin now has an option to use HTML5. Whether I turn that on or off, neither VideoJS nor JPlayer will work.

If you would like debug logs, please let me know what you need.

Thanks.

**Comment by sbillard** [comment]
What type file are you playing? I have JPlayer playing mb4 files.

**Comment by JimBrown** [comment]
mp4, along with webm and ogv. Last working version was 1.5.2.something. Page source does show the JS from my VideoJS plugin being added, but does not show the html from the plugin.

Attached is a debug log after enabling a few of the extra debug items.

[debug.log](https://github.com/ZenPhoto20/ZenPhoto20/files/1769368/debug.log)

**Comment by JimBrown** [comment]
If you want to check my plugin, it is here: https://github.com/JimBrown/VideoJS

**Comment by JimBrown** [comment]
And the theme is here: https://github.com/JimBrown/zenfluid. Although the same issue was present in the other themes.

**Comment by JimBrown** [comment]
Problem exists in 1.5.2.22, but not in 1.5.2.0. So, somewhere between those two versions, something happened. I do note that the 1.5.2.0 class-video plugin does not have the html5 checkbox, but 1.5.2.22 does. Do you remember when you introduced that change? (Will take a look at the commits to see if I can spot it...)

**Comment by sbillard** [comment]
I have found the issue. Class Video was grabbing mp3 and mp4 even with the html5 option reset.

**Comment by JimBrown** [comment]
Excellent. I'll stop trying to find it myself... ;-) Much thanks for the quick work. Will keep an eye out for the fix.

Quick question, will the extract.php file overwrite a newer installation? For example, if I have 1.5.3 installed and want to go back to 1.5.2, can I just run extract.php, or should I delete the files in zp-core, plugins and themes folders first?

**Comment by JimBrown** [comment]
To answer my own question, yes, extract.php will overwrite newer files. And provide an option to delete files that are not in the older version. Bonus!

**Comment by sbillard** [comment]
Yes, the extract file will overwrite any files of the previously installed version. But it will not delete anything, so you may end up with extra files. But Setup will flag those.

I am creating a build with the fix in it as I type. There is a new feature in this update that applies mod rewrite suffixes to articles and pages. It will not change any existing articles or pages. But I thought I should warn you.
[setup-1.5.3.12.zip](https://github.com/ZenPhoto20/ZenPhoto20/files/1769508/setup-1.5.3.12.zip)

**Comment by JimBrown** [comment]
Copied the class-video.php file from the dev fork and replaced the one in zp-extensions. All working as it should now. Much thanks. Will grab the latest setup and do that as well.

**Comment by sbillard** [comment]
Are you interested in your theme and/or video plugin becoming part of ZenPhoto20?

Also, this ticket should remain open until the fix is incorporated in the base. Right now it is just in my development branch. It will close automatically when it is merged.

**Comment by JimBrown** [comment]
If you think it is worthy, sure, I'm interested.

Note that as well as VideoJS, the theme has support for my other plugins, Facebook_Like, GoogleAdsense (limited options) and GoogleAnalytics.

**Comment by sbillard** [comment]
ok, I will try to take a look.

**Comment by sbillard** [comment]
[VideoJS.zip](https://github.com/ZenPhoto20/ZenPhoto20/files/1773300/VideoJS.zip)

For some reason GitHub is giving me fits today. I tried to clone your repository and open it in the GitHub client--no dice. Could however "clone" the clone from the client but then could not sync anything. So no way to create a pull request for these changes.

These are some updates to make the plugin conform the the 1.5.2 (and beyond) release. I would be interested in making this a standard plugin. I suspect that all that would be needed would be to change the USER_PLUGIN_FOLDER define to PLUGIN_FOLDER and move the files. If you wish to do that and create a pull request to ZenPhoto20 that would be cool. I will probably have to rely on you for any fixes not directly related to ZenPhoto20 changes, though.

I looked at your zenfluid but there seems to be a wide difference between it and the distributed theme, so I went no further.

**Comment by JimBrown** [comment]
Will work on a PR for VideoJS.

Can you elaborate on the zenfluid theme issue? I'm not understanding what you mean...

**Comment by sbillard** [comment]
I am not sure there is an issue, it is just that there are a significant number of differences between your theme and the distributed one. I don't have the time to examine them all.

**Comment by JimBrown** [comment]
Ah, you mean between my theme and the other ones that are included in ZenPhoto20? Yeah, I did do my theme pretty much from scratch using bits and pieces from other themes but bending them to what I wanted to do. No worries if you don't have time for it right now.

I have successfully implemented VideoJS as a standard plugin using your file above. Before I do a PR, do you want me to do anything with zenphoto.package? Setup is warning about the extra files.

**Comment by JimBrown** [comment]
Also, do you want me to do the PR against ZenPhoto20 or ZenPhoto20-Dev?

**Comment by sbillard** [comment]
There is a package generator in theDevTools repository that you could run to be "complete" but I can also run that after I do the merge. You can do the pull request for either. If you do ZenPhoto20-Dev it will not show up in ZenPhoto20 until I do a pull. That should happen regularly, but the quickest route is directly to ZenPhoto20. 

As to the theme, if it is intended to be different from the distributed zenFluid Then the question is should it replace zenFluid or should it have a new name.

**Comment by JimBrown** [comment]
Ummm... You have me confused. I'm not aware of a distributed theme called zenFluid. You are referring to the themes that are in the themes folder of the full ZenPhoto20 package, right? I don't see a zenFluid there...

As for the PR, looks like I'll have to do it for ZenPhoto20. Github won't let me fork ZenPhoto20-Dev, it just sends me back to my fork of ZenPhoto20. And I'll let you take care of zenphoto.package.

**Comment by sbillard** [comment]
Ah. my mistake. I have an older version of your theme from 2014 in my test site that I did not realize was not part of the release. So, I will ditch it and let you add your current version in your pull request.

**Comment by nerdykit** [comment]
I've been using the mediaelementjs_player plugin for my videos up until now but I've just tried out your new jPlayer and it works well.  I'll be making it my video player of choice from here on out.  I use a slightly modified version of a basic ZP20 theme.  Can you outline briefly the changes I'd need to make to use any of the asterisked larger video sizes?  Congratulations and thanks for your contribution to ZP20.

NK

**Comment by JimBrown** [comment]
@nerdykit, the video player I wrote is VideoJS, not JPlayer. JPlayer has been included with ZenPhoto20 for some time now.

**Comment by nerdykit** [comment]
Apologies for the unintended insult.  I've trialed your new VideoJS plugin and appreciate the HD and SD implementation you've achieved.  For my modest site it's overkill but congratulations (again!)  : )

NK

**Comment by JimBrown** [comment]
No insult perceived! Just wanted to be sure we were all on the same page. ;-) And thank you for the compliment.
