### ISSUE TITLE
mysqli error on update to 1.5.3.10

### ISSUE THREAD

**Issue by nerdykit** [ZenPhoto20/ZenPhoto20#738]
User Error "MySQLi Error: (SELECT 'id'.... see attached screen grab

![screenshot 2018-03-01 at 8 49 13 am](https://user-images.githubusercontent.com/3220548/36857618-d1bc8f8a-1d2d-11e8-8f34-bc13c1bd900e.jpg)

ZP20 still seems to be functional.  Setup has not completed though. On my admin screen I get both a warning invitation to protect my startup scripts and a request to run setup (but it gets same result) because .10 has been copied over .9 but is not yet setup.

NK

**Comment by sbillard** [comment]
[setup-1.5.3.13.zip](https://github.com/ZenPhoto20/ZenPhoto20/files/1772354/setup-1.5.3.13.zip)

Note, this does not have the issue #739 possible fix.

**Comment by sbillard** [comment]
fix is in 1.5.3.15

**Comment by nerdykit** [comment]
Problem persists after 1.5.3.15 attempted update.  
![screenshot 2018-03-02 at 6 38 58 pm](https://user-images.githubusercontent.com/3220548/36929693-78af47f8-1e49-11e8-9fef-89604d3adedd.jpg)
![screenshot 2018-03-02 at 6 41 56 pm](https://user-images.githubusercontent.com/3220548/36929699-904d5bca-1e49-11e8-8eb9-5aafef6191b2.jpg)

**Comment by sbillard** [comment]
[setup.zip](https://github.com/ZenPhoto20/ZenPhoto20/files/1777817/setup.zip)

please see if this fixes the issue

**Comment by nerdykit** [comment]
Ta da!!  Trumpets sound. Problem resolved with this setup.  Thanks.   Also looking forward to trying out the new video player, I've been using mediaelementplayerjs_player up until now.  Cheers

NK

**Comment by sbillard** [comment]
If you like the  new Video player give thanks to Jim Brown. He created it!

**Comment by sbillard** [comment]
How about #739? did this setup resolve that issue?

**Comment by nerdykit** [comment]
No, I just got the warnings.... (also commented on 739 re possible solution in simply changing the wording of the warnings).

![screenshot 2018-03-03 at 1 00 44 pm](https://user-images.githubusercontent.com/3220548/36939675-d7b8ea6a-1ee9-11e8-90c2-251aa93152e5.jpg)
