### ISSUE TITLE
Possible issue with Setup and theme options

### ISSUE THREAD

**Issue by JimBrown** [ZenPhoto20/ZenPhoto20#743]
If a theme option default is set to "false", the database ends up with a "NULL" instead of "0" for that option after running setup (with theme options purged first). This causes some issues. If the option is set to "true", the database has a "1" for that option. If the theme options are then updated in the admin backend, the unticked options then get the "0" value in the database. Perhaps a bug in setup? Everything works fine if I specify "1" or "0" instead of "true" or "false" for the option defaults in theme options.

**Comment by sbillard** [comment]
The database pretty much cannot deal with real booleans since the option values are stored in text fields. But the option handler functions can force 0 or 1 given a boolean. I will correct that.
