### ISSUE TITLE
Image alt tag

### ISSUE THREAD

**Issue by You85** [ZenPhoto20/ZenPhoto20#745]
Hi, I'm coming to you because I just saw that the image alt tag used the file name.
it's not good for SEO because often the file names do not describe the content of the image.
why doesn't use the category and title or username related to every pic as alt tag instead of use the file name?

`<img src="http://www.domain.com/k48.jpg" style="width:640px;height:426px;" alt="ch06bei148.jpg">
`
change the alt="ch06bei148.jpg"

(that is a non sense name when an image is searched by google or other search engine)

**Comment by sbillard** [comment]
This alt text is specified by the theme. In most cases they specify the title of the image page. Of course if you have not provided a title it will default to the name of the image.

So, bottom line, if you don't want this alt you must either modify the theme or insure that your images all have titles.
