### ISSUE TITLE
Login Logout plugin uses admin environment login

### ISSUE THREAD

**Issue by Elinth** [ZenPhoto20/ZenPhoto20#746]
Hi Stephen,

I have a question that I noticed after I changed the code that disabled the colorbox plugin (Setup turns off colorbox plugin #674). When I now click on the hyperlink "login" in the top right corner in this page: https:/xxx/page/contact/ 
it takes me to the admin login, instead of the theme login. This is the login/logout plugin.
Is it possible to change this into the theme login?
 
Many Thanks

Ewoud

**Comment by sbillard** [comment]
No problem, fix is created. But note, the theme must have a password.php script. Also, current themes need to be updated as they did not expect this script to be loaded directly. The call on printPasswordForm()n should now read
 `printPasswordForm($hint, isset($show) ? $show : TRUE, false)`
as the variable $show will not be defined for the new invocation.

**Comment by Elinth** [comment]
Thanks! Worked like a charm!

**Comment by Elinth** [comment]
The only thing is that my site went in error as soon as I changed: zp-core/index.php
I had to redo setup after that. It's working fine though without this change:
-	if (!checkAccess($hint, $show)) { // not ok to view
+	if (!checkAccess($hint, $__show)) { // not ok to view

**Comment by sbillard** [comment]
did you make the change to the printPasswordForm() call as indicated above? If not then you will get the error. BTW, there are some slight changes in the released version of this change. You should update again.

**Comment by Elinth** [comment]
Jeah, I did made the change in the theme, I coded the changes manually, maybe that's where it went wrong. Is the released version 1.5.3.17? I will update then.

**Comment by Elinth** [comment]
It works but when I click logout, and put in my credentials to log back in it does not redirect you to the gallery, it stays on the password.php page. It logs you in in the background as a user but no redirection to the gallery. Is this the expected behavior?

**Comment by sbillard** [comment]
The changes are up.

**Comment by Elinth** [comment]
Thanks!!! Is there a new build for these changes?

**Comment by sbillard** [comment]
No new build yet. But they are in the repository.
