### ISSUE TITLE
Greet user after login

### ISSUE THREAD

**Issue by Elinth** [ZenPhoto20/ZenPhoto20#749]
Hi Stephen,

Can you help me with a small request? 
I'd like that the site can greet the user when he/she logs in.
Just as simple as "Welcome Stephen" in the description of the gallery page. (in the users preferred language). I really lack coding skills and hope you can help me. :-)

Many thanks for all your help. I am so glad I switched over to ZenPhoto20!

**Comment by sbillard** [comment]
So long as you are not too concerned about grammar, turns out that ZenPhoto20 uses the single word "Welcome" to it would be available in the native language.

if (isset($_GET['newlogon'])) echo "`<p>`".gettext("Welcome")." ".$_zp_current_admin_obj->getName()."`</p>`";

should work

**Comment by Elinth** [comment]
Thanks soo much for your help. I am using a modified ZPArdoise theme. I put it before printGalleryDesc() in the gallery.php page.  When I put in your last codes it does not show anything. No errors, nothing. I changed the printLogonForm() in the password.php too.

**Comment by Elinth** [comment]
Forgot to mention, I'd like it just after logon.

**Comment by sbillard** [comment]
Sorry, now you see why this kind of request is not really appropriate as an issue. Maybe ask for help on the forums in the future. I did not test the code (time is money!) But now I have, here is the correct code. (No modification to the password.php script needed.)

`	<div class="headline-text"><?php
		if (isset($_GET['userlog']) && $_GET['userlog']) {
			echo '<p>' . gettext('Welcome ') . $_zp_current_admin_obj->getName() . '</p>';
		}
		printGalleryDesc();
		?></div>
`

**Comment by Elinth** [comment]
Sorry, next time I will put it in the forums. Kinda new to Github. You really helped me with one, thanks for going the extra mile!
