### ISSUE TITLE
Feature Request | Category

### ISSUE THREAD

**Issue by You85** [ZenPhoto20/ZenPhoto20#752]
Hi, I'm coming to make a suggestion that I think is important. Categories are not present, currently the only way to classify images is tags and albums. Categories can be complementary. an image can have only one category but several tags.

Can you implement it in the heart of zenphoto or develop a plugin.

Thank You

**Comment by You85** [comment]
The difference that can exist between tags and categories. The fact is that the tags can be used to describe the image, whereas the categories can be used to classify the images in a big theme.
For example :

MYIMG45
Category: Nature
Tags: forest, river, sea, ocean

MYIMG46
Category: Funny
Tags: Game, Entertainment, toy, child

**Comment by sbillard** [comment]
This difference is only in your mind. If you tag an image as Nature then you can present your images with that organization. It would be a needless waste to make a parallel implementation simply for some semantic difference as how you "read" a word.

Stop and think of how you would use this. Maybe search for every image which had your category of Nature? That is a tag search. Maybe all images which are "nature" and "forrest"? That is a tag search of nature & forrest.

Why would "forrest" not be a category in your sense? Or, for that matter, what is the difference in usage of any of your tags vs. categories?

**Comment by You85** [comment]
agree @sbillard I will follow your analysis
Thank You
