### ISSUE TITLE
Integrate Blur Admin for Admin Panel

### ISSUE THREAD

**Issue by You85** [ZenPhoto20/ZenPhoto20#754]
# Features
It has documentation to integrate it
Responsive layout
High resolution
Bootstrap CSS Framework
Sass
Gulp build
AngularJS
Jquery
Charts (amChart, Chartist, Chart.js, Morris)
Maps (Google, Leaflet, amMap)
etc

# Why

Because the current design of zenphoto 20 seems to be a premature version unlike other cms of photo management. In addition, the colors that are used are very painful to the eyes if we use a lot of the administration panels. Besides, one of the advantages of a framwork css for the backend is that it is optimized. 
Currently when a user lands in the backend he is immediately drowned in a lot of information.
It would be interesting to remove the information on the version of php mysql ... and show that the important information like the number of photos, the space used, the number of users, the best tags ...The colors are well chosen to improve user experience.

I think you will take into account my zenphoto20 user experience. to integrate it into the roadmap. looking forward to reading you.

![687474703a2f2f692e696d6775722e636f6d2f4133544d76694a2e706e67](https://user-images.githubusercontent.com/30325749/37245842-95edba88-249e-11e8-8f95-51ff8046aa03.png)

**Comment by sbillard** [comment]
We would welcome a submission that ported the Admin pages to this tool. However, a revamp of these pages is not a priority for our implementation time, so short of someone offering to do the work it is  unlikely this will be undertaken.

**Comment by You85** [comment]
Can you leave this ticket open and add a '' wanted help '' tag to see if anyone is volunteering to improve the backend design and help with the user experience.

**Comment by sbillard** [comment]
You would have a much better chance of getting attention if you post a request on the google groups forum. I am not sure how many users actually browse these issue tickets unless they themselves are experiencing a problem.

**Comment by sbillard** [comment]
There has been no response to this ticket and I have not seen a post on the forum requesting interest. Adopting Bootstrap seems of little actual benefit to ZenPhoto20. Although I have no objection to the schema I do not think it a good  use of my resources.

Your point about the installation information is probably valid. This display comes from a much earlier time where software incompatibilities abounded. Removing this display to a separate page will be considered. Once gone the display is essentially as you suggest. Other summary statistics could be added. Space used would be very expensive to compute and probably not be very useful in these days of inexpensive disks. Please feel free to suggest other statistics you think would be useful.

As to the colors, they were chosen by consensus of the users at the time. I certainly see no particular advantage to the color scheme shown above, for example.
