### ISSUE TITLE
Tag is not saved on mass edit img page

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/ZenPhoto20#766]
ZP20 1.6.0

On mass edit img page I write first letters of some tag, choose it and save whole page, but tag is not saved to img.

**Comment by sbillard** [comment]
Please be sure that your are executing the process correctly.

input field type the first letters. Select from the suggestions, then click on the "+" sign. You should then have:
![2018-03-21 15_31_33-main admin_ albums-images](https://user-images.githubusercontent.com/2474007/37741031-22405f96-2d1d-11e8-9179-b74d82d24981.png)

Pressing the plus sign is necessary to "add" the tag to the image.

Anyway, this does work for me.

**Comment by Mates-K1** [comment]
Yes, you are right. I didnt  click on the "+" sign.
Sorry, my fault. :(
