### ISSUE TITLE
register user creates errors and does not register new user

### ISSUE THREAD

**Issue by Elinth** [ZenPhoto20/ZenPhoto20#770]
Hi Stephen,
When I register a new user via register.php it throws different errors after I submit in the user information. It does work fine when I create the user from the back end admin part.
 NOTICE: "Undefined index: pass" in /srv/disk6/279773/www/site/zp-core/zp-extensions/register_user.php on line 199
WARNING: "Cannot modify header information - headers already sent by (output started at /srv/disk6/279773/www/site/zp-core/functions-basic.php:129)" in /srv/disk6/279773/www/site/zp-core/index.php on line 152
WARNING: "Cannot modify header information - headers already sent by (output started at /srv/disk6/279773/www/site/zp-core/functions-basic.php:129)" in /srv/disk6/279773/www/site/zp-core/index.php on line 153
WARNING: "Cannot modify header information - headers already sent by (output started at /srv/disk6/279773/www/site/zp-core/functions-basic.php:129)" in /srv/disk6/279773/www/site/zp-core/index.php on line 154
WARNING: "Cannot modify header information - headers already sent by (output started at /srv/disk6/279773/www/site/zp-core/functions-basic.php:129)" in /srv/disk6/279773/www/site/zp-core/index.php on line 155 

Thought I'd keep you busy ;-)

**Comment by Elinth** [comment]
Hi Stephen, your change fe0cf6c bricks my site at setup with the following error:
 WARNING: "Cannot modify header information - headers already sent by (output started at /srv/disk6/279773/www/site/zp-core/lib-auth.php:1)" in /srv/disk6/279773/www/site/zp-core/functions-basic.php on line 714
WARNING: "Cannot modify header information - headers already sent by (output started at /srv/disk6/279773/www/site/zp-core/lib-auth.php:1)" in /srv/disk6/279773/www/site/zp-core/setup.php on line 21

**Comment by sbillard** [comment]
Sounds like a stray line has been inserted in the lib-auth file. Here is a proper build with the fix in it.

[setup-1.6.0.05.zip](https://github.com/ZenPhoto20/ZenPhoto20/files/1877661/setup-1.6.0.05.zip)

**Comment by Elinth** [comment]
That worked very well, thank you. Just one more question on this topic.. When I register as a user, I receive the verify email. I follow the hyperlink in the email to the website and it takes me to the login page. When I login at this moment it takes me to a blank page that says user registration page. Also this page gives you an alert that you are already logged in which is strange. Is it possible to route users directly to the gallery page instead of this blank registration page? It seems better then when your first impression of the website is a blank page.

**Comment by sbillard** [comment]
I will have to check into this last issue. I thought it did take you to the gallery page.

**Comment by sbillard** [comment]
I( just tested this and it worked correctly for me. Can you provide a link to your site so I can look at things there?
