### ISSUE TITLE
unpublished subalbums within published album 

### ISSUE THREAD

**Issue by The-Edge-Malaysia** [ZenPhoto20/ZenPhoto20#784]
Hi!

we are uploading albums and images via file copy not via zenphoto uploading mechanism

I noticed that if the root album is published, all subfolders and images are marked as published as well. 

we are using file copy to copy images or subfolders, and all these copied images or subfolders are with published status which we do not want.

to elaborate further, when we create a subfolder in a parent folder (published) from file system, we wanted the created subfolder to be unpublished until someone manually publish the subfolder.

how to achieve this?

**Comment by sbillard** [comment]
The steps to follow are:

1. Insure that the "publishContent" plugin is enabled.
2. From the Admin flyout menu select PUBLISH CONTENT
3. From the Publish Content page set the _Discovery_ options to your choice.

**Comment by The-Edge-Malaysia** [comment]
Hi

it does not work for me.

when I create a folder under a published album, and copy images onto the
folder I have created, even the publishcontent's discovery does not check
the Publish images by default  and Publish album by default, it still
appears for anonymous user

**Comment by sbillard** [comment]
When you look at these albums and images on the administrative pages are they marked published or unpublished?

**Comment by The-Edge-Malaysia** [comment]
Published

**Comment by sbillard** [comment]
Found the problem.

**Comment by The-Edge-Malaysia** [comment]
Thanks!
