### ISSUE TITLE
Basic theme - Image info link

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/ZenPhoto20#785]
Link does not look like link.
![d26d3107-1fad-4e03-98b2-11b1566795f3](https://user-images.githubusercontent.com/7648991/39959287-a6e36890-560f-11e8-8ec4-d9b957f5e3bd.jpg)

**Comment by Mates-K1** [comment]
Google Map link looks different...

**Comment by sbillard** [comment]
Turns out it was not possible to make the google map link look like a button. So all the links are now link style.
