### ISSUE TITLE
GalleryArticles plugin tick box settings don’t work

### ISSUE THREAD

**Issue by Elinth** [ZenPhoto20/ZenPhoto20#786]
GalleryArticles is spewing out news articles when new images are created, while I only have the album box ticked. (The image box is unticked). (Latest build)

**Comment by sbillard** [comment]
I am not able to reproduce this behavior. Please provide the step by step process you followed, maybe I am missing some step. But I make a new album with new images in it and only the album gets a news article.

**Comment by Elinth** [comment]
My setting is that I only have a tick in the the album box. The image tickbox is empty. I am adding text to a lot of images that I already uploaded a while back via ftp. It will send a news article for every image that I edit.

**Comment by sbillard** [comment]
Are the images going from unpublished to published?

**Comment by Elinth** [comment]
Nope, I think they were already published. And I am sure I did not touch that status.

**Comment by Elinth** [comment]
(Side topic) Maybe a nice add on to the plugin. To create unpublished articles. This would help me greatly with my news setup.

**Comment by Elinth** [comment]
I just deactivated and activated the plugin and now it is not doing creating images as before. Maybe it was a glitch?

**Comment by sbillard** [comment]
I have been able to reproduce this now that I know where it happened. Still trying to figure out why, though.

**Comment by sbillard** [comment]
> (Side topic) Maybe a nice add on to the plugin. To create unpublished articles. This would help me greatly with my news setup with categories.

Sounds reasonable.

**Comment by Elinth** [comment]
Hi Stephen, the plugin galleryarticles is not creating news articles for new albums, while the Album is ticked in the setting. Also the create new album in dropdown list from the vertical admin menu, (the menu through the little wheel), is not working.

**Comment by sbillard** [comment]
I am assuming that you were using the "gear" menu to create the albums that did not get a gallery article. If not, please describe what you did since I the other new albums work correctly for me.

Thanks for the report. I think that the fix will have to wait until the next release (which should not be so long now.)

**Comment by Elinth** [comment]
Yes, the gear menu. The link to create a new menu in this menu does not work at all. I created albums via ftp. Maybe because I did it via ftp  is why it does not come up as a new album article?

**Comment by sbillard** [comment]
Creating the albums via FTP should have got them published. But maybe there was an interaction with the gear button creation. Anyway, I've fixed those issues. They are included in the current development release. SO far as I can see, everything now works correctly. 

I have created a test site that you can tryout. You might be able to try enough things to have confidence in the new release for your needs. Visit http://testalbum.sbillard.org/clone/

This site  has a number of new features. The first you will notice is that you will redirected to a "Policy" page the first time you visit. Check the checkbox and then the "Continue to site" button and you will be on the site.

You will note that you are logged in as "Visitor." There is a custom plugin that will let you visit the administrative pages. You won't be able to make any permanent changes, but you should be able to try out all your normal administrative functions and be sure that they work for you.

Same should be true of the theme. Obviously you won't have your content or custom changes, but the standard theme should give you an idea if everything is working for your uses. Click the menu (☰) button to select the theme you want to experience.

If you decide things are good you can download this release from https://github.com/sbillard/ZenPhoto20-DEV/releases If there are more than one setup files, just pick the most current one.

**Comment by Elinth** [comment]
Cool, i will look at this tomorrow. This is the build with the new jquery?

**Comment by Elinth** [comment]
Just thought of something..Could it be that I use unpublished albums?

**Comment by sbillard** [comment]
Unpublished albums will get the article generated when they are published.

Thanks for the error report, this is an artifact of the "pseudo login" that needs to be fixed. It is a bug in the plugin that grants admin access, not in the development release.

**Comment by sbillard** [comment]
The bug is an interaction with the GDPR plugin (which does the redirection to the policy page.) I will disable that plugin until I figure out how to fix the conflict.

**Comment by sbillard** [comment]
And, yes, this build has jQuery version 3,3

**Comment by Elinth** [comment]
Is setup-1.6.2.08.DEV_07.zip the last stable one? Do I need to make changes to my theme that is based on ZPArdoise?

**Comment by Elinth** [comment]
Running your setup-1.6.2.08.DEV_07. on production now. Seems to be working fine 👍

**Comment by sbillard** [comment]
Thanks for the update. We hope there are no changes you would need to make to the theme. But the jQuery 3.0 change could cause some need. I think all the javascripts that are part of the distribution are working correctly. But just a few days ago I found an incompatibility, so there may still be errors lurking.

Let me know of any issues you see.

**Comment by Elinth** [comment]
Will do, so far so good :-)
