### ISSUE TITLE
Help, I have a database issue!

### ISSUE THREAD

**Issue by Elinth** [ZenPhoto20/ZenPhoto20#787]
Somehow I have bricked the site.
I am trying to run setup again but it gives me the following error.
USER ERROR: "MySQLi Fout: (SHOW VARIABLES LIKE 'character_set_database') mislukt. MySQLi gaf de foutmelding: User '279773_zenphoto89c642cd' has exceeded the 'max_questions' resource (current value: 50000)." in /srv/disk6/279773/www/site/zp-core/functions-basic.php on line 71

**Comment by Elinth** [comment]
It gives me loads of errors... help!!

**Comment by Elinth** [comment]
Can I run a database back up somehow?

**Comment by Elinth** [comment]
This is what I see in MySQL
Error

Static analysis:

2 errors were found during analysis.

    Unrecognized keyword. (near "CHARACTER SET" at position 4)
    Unexpected token. (near "'utf8'" at position 18)

SQL query: Edit Edit

SET CHARACTER SET 'utf8';

MySQL said: Documentation
#1226 - User 'xxx' has exceeded the 'max_questions' resource (current value: 50000)

**Comment by Elinth** [comment]
fixed it

**Comment by sbillard** [comment]
Glad it is fixed. So what caused the problem?

**Comment by Elinth** [comment]
Yeah, this one really made me panic...
Just fiddled my database into corruption.. Bad move.
Currently I have a customized ZpArdoise theme. I am trying to customize the ZPFocus theme to my needs as I really like the left column set-up. I am absolutely lost in some really simple css thingie, that I cannot seem to get to work. I accidentally pasted some code in the gallery.php that I shouldn't have. My database really did not like that. I was not able to run setup anymore. So the fix came when I looked into my hosting account. I have a remarkable "fix database" tool at my host that fixed the database problem. 
So glad it worked...

**Comment by sbillard** [comment]
You might want to setup a test installation just for this kind of situation, You could install (or clone) Zenphoto20 in a subfolder and use that for testing "dangerous" changes.
