### ISSUE TITLE
Minor- change of album order not detected for save

### ISSUE THREAD

**Issue by nerdykit** [ZenPhoto20/ZenPhoto20#789]
If I change the order of a list of albums in "edit album", the "Apply" button does not turn green to indicate that I must save in order to preserve my change.  It may not be possible to detect and respond to the drag that changes the album order but if it is, then it could be helpful to have the Apply button change colour the way that it does for any other edit that I make.

Thanks

NK

**Comment by sbillard** [comment]
Should work, but at the moment I do not know why it does not.
