### ISSUE TITLE
Can only view new album if I'm logged in as admin

### ISSUE THREAD

**Issue by nerdykit** [ZenPhoto20/ZenPhoto20#790]
Just upgraded to 1.6.2.07 and then created a new album and populated it.  I can view the album if I'm logged in as admin.  If I log out, clicking on the album "cover" image gets me the comment form but not the album thumbs.  I've toggled publishing on and off and back on again to see if something was wrong there but no help.

NK

**Comment by sbillard** [comment]
Are the images marked as published?

Just trying to understand if it is not showing published images or if the images are wrongfully not published. (Note, changing the publish default won't matter to already discovered images.)

**Comment by nerdykit** [comment]
Bingo!  I mistakenly assumed that setting an album to published also set all of its contained images to published which  is wrong and also necessary otherwise you couldn't control individual images.  BUT along the way to correcting my problem, I discovered some problems with Bulk Actions.  I could get Bulk Actions to work if I used the Image Order sort page but I could not get any Bulk Actions to work on the page that lists images in groups (10 or 15 or 20 etc) along with all their properties also the published/unpublished filter drop down produced no changes in which images were displayed even when I was part way through the process of setting all images to published.

**Comment by nerdykit** [comment]
I've found the General setting to Publish Images by default which is the behavior I want.  The Filter problem noted in my reply above does not exist.  There is no problem with the Filter behavior for image lists.  There IS a problem with Bulk Actions on the Image List page and I've opened a new issue for this.

Thanks

NK
