### ISSUE TITLE
Text items in "Cache as" are not clickable

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/ZenPhoto20#792]
Options in "Cache as" are not clickable (text is not clickable).

Other items in galery are clickable.

![bbaacc1d-7f20-486b-98aa-ca8138cc8bf3](https://user-images.githubusercontent.com/7648991/40685989-16c34516-6396-11e8-943c-bc98307c8fa3.jpg)

**Comment by Mates-K1** [comment]
I know... it is trifle (hope google translator did his job well for this word)...
There are another items in gallery which are not clickable. Should I write them here?

**Comment by sbillard** [comment]
please do, saves me the time of finding them. (Translations seems appropriate.)

**Comment by Mates-K1** [comment]
Options-General:
Registration - **notify**
Security log limit and Debug log limit - **e-mail when exceeded**

Options-Image options:
Cache as - **original, gif, jpg, png** (in my first post)

Options-Search options
Cache expiry - **cache searches which...**
+Sort albums, images,... by -  switch check box and text (check box first, then text)

Options-Theme
+Gray scale conversion - switch check box and text (check box first, then text)

Admin - Backup
whole page

Edit album page - **Check all**

**Comment by Mates-K1** [comment]
I checked plugins, they are all OK.

**Comment by sbillard** [comment]
Thanks. I will probably include this in the next release rather than retrofit it.
