### ISSUE TITLE
User page - wrong alignment

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/ZenPhoto20#793]
Vivaldi 1.16.1183.3
![vivaldi](https://user-images.githubusercontent.com/7648991/40744069-bb4af81e-6453-11e8-882c-32ceaeb53b71.jpg)

MS Edge 42.17134.1.0
![edge](https://user-images.githubusercontent.com/7648991/40744110-e47071c4-6453-11e8-9b63-15ee8c75d706.jpg)

**Comment by sbillard** [comment]
Sigh, why don't all browsers work the same? But it can be fixed without breaking at least Chrome.
