### ISSUE TITLE
Categorization for albums/news/images does not work for search

### ISSUE THREAD

**Issue by Elinth** [ZenPhoto20/ZenPhoto20#796]
Hi Stephen, 

When I have a user that does not have viewing rights for a specific unpublished album, this user can still see the album in the results when he/she searches. It would be ideal if the search results would only display the album/page/article that he/she has rights to. Currently, when the user clicks on the album that he/she does not have rights to, he/she cannot access it. I think it would be more consistent if the content that the user does not have rights to is not displayed at all in the search results. What do you think?

**Comment by sbillard** [comment]
It should work as you suggest. I will check, but maybe you can give me full details on the situation:

All the user rights, details about the album (subalbum? published images in it? anything else you can think of.)

**Comment by Elinth** [comment]
I have a family site. In my site I work with unpublished albums and articles so I can assign rights so users from Family A only see albums from family A and news articles from family A. When my test user (who is part of family group A) puts in a query, and I put in a value from the family name B as a search query, I get all the family B content regardless of what viewing rights are assigned. The query result regardless what category or album assignment is all displayed as thumbnails. When the same test user from family group A clicks on the thumbnail he gets the login screen as he has no access as he does not have permissions for this album or image from family B. Isn't it better that this album is not displayed at all when you have no permissions? Hope I make sense...

**Comment by sbillard** [comment]
Well, things work correctly for me. I have setup what you describe, so I imagine that you have set the  user rights incorrectly. By any chance is the "access all" album right set?

**Comment by Elinth** [comment]
Maybe I figured it out, do images have to be unpublished as well? Is there a way to unpublish all?

**Comment by Elinth** [comment]
It had to do with some published albums. Apologies

**Comment by sbillard** [comment]
Answer to the first question is that published images in unpublished albums should not be found. But glad you figured it out.

There is no way to unpublish all images, the quickest would be to go to each album and on the image order page use bulk actions to unpublish.
