### ISSUE TITLE
Feature request: My account page

### ISSUE THREAD

**Issue by Elinth** [ZenPhoto20/ZenPhoto20#798]
Hi Stephen,
After all the help you have given me the last weeks I hope you are still open for a feature request.. 
It would be ideal if there would be a "my account" page added to the menu that would show a user's information such as first name, last name, address, email, and password etc. and the ability to change this information. Ideally this is a page that can be in theme layout. 
This page would be good considering the privacy laws of today in Europe, people need to see and be able to edit their personal information. 
Also I noticed that when a user only has viewing rights to an album or news (So no editing rights), albums and news are still displayed in the menu (the one with the little wheel). When they have nothing to edit, can these two items not be displayed in the menu?

Many Thanks, 

Ewoud

Cheers

Ewoud

**Comment by sbillard** [comment]
How would the "my account" be different from him clicking on his user 
name ("go to user profile") on the admin pages?
Seems really unnecessary to make a theme page of it. The toolbox menu 
has a "users" selection. That could be changed to "My account" if the  
user does not have user administrative rights.

I'll look into the view only suggestion. Seems reasonable if it can be 
done simply.


-Stephen

**Comment by Elinth** [comment]
You are right. I just noticed that user setting. Just tried it. My worry is that when a user does not have admin rights, they see too much. They can see where they do not have access to, also the albums that they do not have access to. This is in my point of view not ideal.

**Comment by sbillard** [comment]
The user can see only those things that you have allowed him to see. For instance, if all  he has is user rights, all he can see is his user page.

**Comment by sbillard** [comment]
All he can see is what rights he has. Which rights do you see as an issue?

**Comment by Elinth** [comment]
My Zenphoto20 works only with non-admin users that have viewing rights for unpublished items. This way I can control what albums they can see. This is an amazing feature of Zenphoto20. This means in my setup they only see the front end of the site. The only reason they would see the backend is when they need to change their personal information or password. Ideally (In case of my setup) this would be a my account page part of the theme, so they only stay in the front-end of Zenphoto20. In the current situation, they have to go to the admin where they can also see the tick boxes that they have rights to, in my case my non-admin users do not have to see these tick boxes, and ideally would not have to go to the admin back end at all. They only need to see the personal information and password. Maybe my request for a themed based page is too much based on the way I use Zenphoto20. I love the way Zenphoto20 handles viewing rights. This is genius. For my users to stay only on the front end keeps the setup simple.

**Comment by sbillard** [comment]
Well, of course, you could always make a page for their user info and 
just display whatever you want them to see.

I think there is no  harm for them seeing all rights and which they 
have. Rights are, after all, part of the data ZP20 does keep on them, so 
I guess by EU law they should be able to see it.


-Stephen
