### ISSUE TITLE
One time password for login

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/ZenPhoto20#804]
Hi,
is possible to implement one-time-password as another security layer for logging in please?

**Comment by sbillard** [comment]
I am not clear as to what you are asking. Are you looking for a two-step verification such as Google might use?

**Comment by Mates-K1** [comment]
For example I use Nextcloud or Wordpress with OTP and when I log in I write user name and password, afther that system ask for six numbers. These numbers are generated offline in my mobile phone and changed every about 30 seconds.

Odesláno z telefonu s Windows 10

Od: Stephen
Odesláno:středa 4. července 2018 18:08
Komu: ZenPhoto20/ZenPhoto20
Kopie: MartinKroul; Author
Předmět: Re: [ZenPhoto20/ZenPhoto20] One time password for login (#804)

I am not clear as to what you are asking. Are you looking for a two-step verification such as Google might use?

**Comment by sbillard** [comment]
Ok, I think I have a working implementation. https://github.com/sbillard/ZenPhoto20-DEV

New plugin: googleTFA implements 2 factor authentication using the Google Authenticator phone app.

Adds new database fields and a new item on the user profile for enabling/disabling 2 factor authentication and showing the user's QR code for Google Authenticator.

Caution when testing--use a secondary user, if it fails you won't be able to log in unless you remove the plugin.

Let me know how it goes.

**Comment by Mates-K1** [comment]
Sorry, I had short holiday.

There is some bug in autorization.
1. I allow google TFA plugin as administrator.
2. I try login as another user in another browser and I get:
![000](https://user-images.githubusercontent.com/7648991/42423890-9bceafc6-8302-11e8-86d7-f297be0af04f.jpg)

3. As admin I choose another user to allow TFA for him.
4. I cant allow it, it is disabled:
![001](https://user-images.githubusercontent.com/7648991/42423910-ca1e0fb6-8302-11e8-905a-73ba4edb4138.jpg)

5. If I set "viewers" group to this user, I cant still allow TFA.
![002](https://user-images.githubusercontent.com/7648991/42423952-9e8addd8-8303-11e8-99d6-42eee73af4de.jpg)
6. But if I set him group "uživatelé" and "viewers", I can allow TFA.
![003](https://user-images.githubusercontent.com/7648991/42424002-3bdd2da2-8304-11e8-8a3f-f34953be218d.jpg)

**Comment by Mates-K1** [comment]
7. Ok, now I can scan my QR code (for me issuer is blank, in plugin setting is set).
8. When I try to login (set name and password), I get blank page with adress

> zp-core/zp-extensions/googleTFA/auth_code.php

**Comment by Mates-K1** [comment]
Thanks, it solved groups issue.
But I still cant login if user have or had TFA enable. I get exception from nr. 2.

**Comment by sbillard** [comment]
The error can only happen if the login was not successful, e.g. the user or password was not valid. (Still itis a bug that you got the error.)

There was a bug (now fixed) where if the user was not able to alter some of his settings the checkbox for TFA was included so it could not be set. I think that is the problem with your "uživatelé" group.

Did you first run setup after enabling the plugin? That should have set your issuer to your site, e.g. skautskagalerie.cz. You can, of course, change that to the your site "name". Also if you did not run setup, the needed database columns in the administrator table would not be there. This might also be the reason for the blank page.

**Comment by sbillard** [comment]
I did find a but when logging with a theme form.

current set of fixes are at https://github.com/sbillard/ZenPhoto20-DEV/releases/tag/ZenPhoto20-1.7.0.0

**Comment by Mates-K1** [comment]
It works! Many thanks for implement this! 🥇

**Comment by sbillard** [comment]
closed by version 1.7.1
