### ISSUE TITLE
Re-running setup error (v1.7.0.02.DEV_02)

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/ZenPhoto20#807]
```
Query Failed: ALTER TABLE `_hlavnisearch_cache` ADD UNIQUE `criteria` (`criteria` (250)) COMMENT 'zp20';
Error: Specified key was too long; max key length is 767 bytes
```

**Comment by sbillard** [comment]
From the MySQL manual:
The index key prefix length limit is 3072 bytes for InnoDB tables that use DYNAMIC or COMPRESSED row format.

The index key prefix length limit is 767 bytes for InnoDB tables that use REDUNDANT or COMPACT row format. For example, you might hit this limit with a column prefix index of more than 191 characters on a TEXT or VARCHAR column, assuming a utf8mb4 character set and the maximum of 4 bytes for each character.

Attempting to use an index key prefix length that exceeds the limit returns an error.

The limits that apply to index key prefixes also apply to full-column index keys.

So I am presuming that your database must be using the REDUNDANT or COMPACT row format. Can that be changed to the DYNAMIC or COMPRESSED format?

**Comment by sbillard** [comment]
Should be fixed in DEV_5

**Comment by Mates-K1** [comment]
Yes, fixed... Many thanks. 👍
